### ISSUE TITLE
Remove Berkeley DB from Operating System Images

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#1]
Berkely DB comes with a problematic open source license and must be removed prior to the image being deployed.

There are apparently several places where it is being used (more detailed needed):
pam
apt

**Comment by marwinski** [comment]
Resolved, latest image does not contain Berkeley DB anymore

**Comment by vlerenc** [comment]
Great @marwinski :-)

**Comment by marwinski** [comment]
kudos go to @gehoern  :-)

**Comment by Vincinator** [comment]
Current images do not contain BerkleyDB. Tested with `576.12` and `862.0`.
