### ISSUE TITLE
update the kernel to latest LTS

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#100]
We run debian testing and the bare installation would already run a kernel like 5.6 or 5.7 but all those kernels are no LTS kernel so the change rate in ABI is rather high. Debian stable sticks currently to 4.19 what is for our requirements to feature set und security too old.
To have some stability the aim is a LTS kernel and therefore we need to maintain this (at the moment in hack/packages)
Make sure we are using the current [kernel.org](https://kernel.org) image for the latest LTS kernel atm it is 5.4.46. (current situation is we pinned to the latest 5.4 available in debian = 5.4.19)

**Comment by marwinski** [comment]
/assign @gehoern 

Can we close this one?

**Comment by marwinski** [comment]
long done :-)
