### ISSUE TITLE
ARM64: Compatibility [Meta]

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1028]
## General
This issue ensures that all used Garden Linux features are fully compatible on `arm64` / `aarch64` architecture. Therefore, we should cover several test cases with different scenarios.

## Test / Validate

- #1030
  - #1068 
  - #1069
  - #1070
  - #1071
  - #1063
  - #989 
- #1044
  - #1072
  - #1073 (Blocked by: #1045)
  - #989 
- PyTest
  - #1022
  - Unit Tests
    - #1032 
    - #1033
      - #1042
  - Integration Tests (all platforms)
    - #1035 
    - #1036 
    - #1037 
    - #1038 
    - #1039 
    - #1040 
- Features
  - #1116
  - KVM-Dev
  - CIS
  - Gardener 
    - #1065
    - #1064   
- Misc
  - Toolsets around GL
    - #1031
      - #1049
      - #1052
      - #1055 
      - #1056
      - #1079

## Enhancement
- PyTest
  - General Enhancements
    - #1057
  - ARM64 related Tests
    - Gardener
      - #1066
      - #1067

We will create subtasks for these points. It may make sense to zip them in some cases.

**Comment by marwinski** [comment]
I am missing the integration tests in the above list. As we have an image for AWS Graviton we should have that included in the list above.

**Comment by gyptazy** [comment]
> I am missing the integration tests in the above list. As we have an image for AWS Graviton we should have that included in the list above.

Thanks, good point. I've just added an issue for every supported platform type.

**Comment by nanory** [comment]
All sub tasks have been completed. There is still an issue with ARM64 on Azure since it can be started now but it doesn't boot properly. However, there is an follow up issue which takes care about this problem: https://github.com/gardenlinux/gardenlinux/issues/1482 

Other than that, this issue can be closed now.
