### ISSUE TITLE
ARM64: PyTest -> Integration Tests -> `OpenStack CCEE`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1035]
Meta Issue: #1028 

## PyTest
This issue covers the validation of `integration tests` of PyTest for the platform provider `OpenStack CCEE`  running on `ARM64` / `AARCH64` architectures.

## Tests
Within this issue the following components will be validated and tested:
- PyTest
  - Integration Tests
    - `OpenStack CCEE`

**Comment by gehoern** [comment]
I guess not supported for now.

**Comment by nanory** [comment]
OpenStack CCEE does not support ARM, so we can close this issue then.
