### ISSUE TITLE
ARM64: PyTest -> Integration Tests -> `AWS`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1036]
Meta Issue: #1028 

## PyTest
This issue covers the validation of `integration tests` of PyTest for the platform provider `AWS`  running on `ARM64` / `AARCH64` architectures.

## Tests
Within this issue the following components will be validated and tested:
- PyTest
  - Integration Tests
    - `AWS`

**Comment by nanory** [comment]
Quick update to this issue,

we discussed this topic and agreed to disable `rngd.service` on `arm64` machines. This has been done in #1124 
As a result, all tests are now passed, so once #1123 is merged, we can close this issue.
