### ISSUE TITLE
ARM64: PyTest -> Integration Tests -> `Ali`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1038]
Meta Issue: #1028 

## PyTest
This issue covers the validation of `integration tests` of PyTest for the platform provider `Ali`  running on `ARM64` / `AARCH64` architectures.

## Tests
Within this issue the following components will be validated and tested:
- PyTest
  - Integration Tests
    - `Ali`

**Comment by nanory** [comment]
There is no official ARM support for Alicloud as of now but a closed beta. However, since we can not test the ARM image there, we will close this issue then.
