### ISSUE TITLE
Overlayfs

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#104]
Currently we are pushing liveboot forward as of use in PXE boot. Liveboot brings some cool overlayfs features with it.

Try to test and document the following scenarios:

- overlay the whole / and persist to ram or a separate drive

and

- overlay /etc/systemd/system and /etc/kubernetes and persist to ram
- overlay /opt and /var/lib/docker and persist to disk

**Comment by marwinski** [comment]
@gehoern still relevant?

**Comment by 5kt** [comment]
This is already supported by the gardenlinux-live dracut module.
