### ISSUE TITLE
machine-id not set properly in readonly feature

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1053]
**What happened**:
I noticed that `systemd-journald` does not work properly by using a Garden Linux image build with the `readonly` feature. After some debugging, I've noticed that the `machine-id` is not set properly if one uses the `readonly` feature.

It seems that the `machine-id` is stuck in the initialization, so that `/etc/machine-id` returns `uninitialized` way after the image has been booted.

I assume it has something to do with `systemd-machine-id-commit.service` which returns the following information:
```
root@localhost:/etc# systemctl status systemd-machine-id-commit.service
○ systemd-machine-id-commit.service - Commit a transient machine-id on disk
     Loaded: loaded (/lib/systemd/system/systemd-machine-id-commit.service; sta>
     Active: inactive (dead)
  Condition: start condition failed at Mon 2022-06-27 13:50:17 UTC; 12min ago
             └─ ConditionPathIsMountPoint=/etc/machine-id was not met
       Docs: man:systemd-machine-id-commit.service(8)
```

Once the `machine-id` is set manually, everything seems to work normally.

**What you expected to happen**:
The `machine-id` should be set properly and `systemd-journald` should be able to show system logs.

**How to reproduce it (as minimally and precisely as possible)**:
Build Garden Linux like this and then run it.
```
./build.sh --arch amd64 --skip-build --features server,cloud,kvm,_dev,_readonly .build
```
Once started, you shouldn't be able to see logs via `journalctl`

**Comment by marwinski** [comment]
It would be great if you could add an integration test for this. Thanks
