### ISSUE TITLE
VM fail to reseolve its own hostname on Azure

### ISSUE THREAD

**Issue by vpnachev** [gardenlinux/gardenlinux#107]
**What happened**:

On azure shoot cluster I noticed the metrics server failed to fetch the metrics from the nodes because it cannot resolve the nodes hostname
```
...
Get https://shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff on 10.243.0.10:53: no such host]
...
```

On the VM level I noticed that the VM cannot resolve its own hostname
```bash
root@shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff:/# nslookup $(hostname)
Server:         168.63.129.16
Address:        168.63.129.16#53
** server can't find shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff: NXDOMAIN
```

It looks like the `systemd-networkd` register the node hostname in the DHCP server too early when the waagent still have not set it
```
Jun 24 13:17:07 localhost systemd-networkd[425]: eth0: DHCPv4 address 10.242.0.13/19 via 10.242.0.1
```

Restarting the `systemd-networkd` after the waagent is done register the node hostname with the DHCP properly
```bash
Jun 24 17:02:23 shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff systemd-networkd[414]: eth0: DHCPv4 address 10.242.0.13/19 via 10.242.0.1
``` 

And the VM now can resolve its own hostname, actually all nodes in the cluster can resolve the hostname of this VM.

```bash
root@shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff:/# nslookup $(hostname)
Server:         168.63.129.16
Address:        168.63.129.16#53

Non-authoritative answer:
Name:   shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff.<....>.ax.internal.cloudapp.net
Address: 10.242.0.13

```

**What you expected to happen**:
The nodes to successfully update the DHCP server with their actual hostname.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster with Garden Linux, get a shell on the node and try to resolve its own hostname.

**Anything else we need to know**:

**Environment**:

```bash
root@shoot--foo--bar-cpu-worker-z1-7744965d87-f82ff:/# cat /etc/os-release
PRETTY_NAME="Garden Linux"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://gardenlinux.io/"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_FEATURES=base,azure,_nopkg,_prod,_readonly,_slim,_slim,base,base,cloud,cloud,gardener,server,server
GARDENLINUX_VERSION_ID=20200427
GARDENLINUX_BUILD_ID=27.1.0
VERSION_CODENAME=bullseye
```

**Comment by marwinski** [comment]
Sorry, just exploded into my face during integration test development. Fix is coming.
