### ISSUE TITLE
ARM64: Run Images -> Secure Boot

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1073]
Meta Issue: #1028 

## PyTest
This issue covers the validation of running `ARM64` based Garden Linux images in a secure boot setup.

## Tests
Within this issue the following components will be validated and tested:
- Run Images
  - Secure Image Booting (secure boot)

**Comment by gyptazy** [comment]
This doesn't work. `PK` and `KEK` can't be written to `UEFI vars` on `ARM64`.
Bug #1045

**Comment by gehoern** [comment]
please check what is the limit of the cloud provider and ignore if the cloud provider is the problem.

In KVM everything should work

**Comment by gyptazy** [comment]
Updating the vars for secure boot key results in `Failed to update PK: Operation not permitted`.
@gehoern @nkraetzschmar, how should be proceed here? If I understand @gehoern correctly, we may currently ignore this for cloud platforms?

**Comment by gyptazy** [comment]
Ok, this is related to the machine type. On non-metal instances this works as expected:

```
[    0.000000] Kernel is locked down from EFI Secure Boot; see man kernel_lockdown.7
[    0.000000] secureboot: Secure boot enabled
[    1.725823] integrity: Loaded X.509 cert 'SAP SE: Garden Linux secureboot.db Signature: 7227db24d82157f98d879f15e7c47b38ab3ac7fb'
```
