### ISSUE TITLE
Documentation of requirements to build

### ISSUE THREAD

**Issue by mward29** [gardenlinux/gardenlinux#108]
**What would you like to be added**:
Documentation of requirements to successfully build gardenlinux

**Why is this needed**:
Currently there are several requirements to successfully build gardenlinux that are not documented.

Examples:
python version
jq awscli apt-utils
docker.io
make
make guile

**Comment by gehoern** [comment]
As i see it we should make sure the base requirements are really just make and docker. the rest should be in the build image. But you are completly right: we have more dependencies (lately we had a quota issue). So can someone check what is needed besides from support for losetup and kernelmodules for ext4, squashfs, vfat and gpt to build our environment on the host system? (and of course document this)

**Comment by mward29** [comment]
That would be great to see. Building the image on Debian works, but on other Linux variants not necessarily. Ran into several issues.
