### ISSUE TITLE
Get newest version of `dracut` in Debian upstream

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1089]
**What would you like to be added**:
The current version of `dracut` in `debian/testing` is `056-3`. There is already a newer version of dracut available that we want to use.
Ensure that `057` is integrated in Debian.

**Why is this needed**:
This version contains changes that we want to use.

**Comment by gehoern** [comment]
dracut has a core feature (that is obviously needed) and a dracut-network is needed for ignition and brings an unexplainable 99-default.network with it (was reality in 055) is this still there ? can one verify if e.g. the dhcp standard interfaces are initialized with this and if so ... can you make sure it is only limited to en*

**Comment by gehoern** [comment]
@5kt i guess it is now included but we should check if it works completely.

**Comment by nanory** [comment]
Since there has already been a new Garden Linux release and also Debian is offering the new dracut version `057`, I think we can consider this task as done. I'm therefore closing it.
