### ISSUE TITLE
Add open-iscsi to the base image

### ISSUE THREAD

**Issue by liorokman** [gardenlinux/gardenlinux#109]
**What would you like to be added**:

Add `open-iscsi` to the default installed packages.

**Why is this needed**:

This package is required to allow iSCSI volumes to be mounted on the node.

**Comment by marwinski** [comment]
A a temporary mitigation for Garden Linux 27.x the following will work via a privileged pod (will not work anymore with the next version):

    gardenctl shell <host>
    mount -o remount,rw /usr
    apt-get update && apt-get install -y open-iscsi
