### ISSUE TITLE
ARM64: Features -> `vhost`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1116]
Meta Issue: #1028 

## Features -> `vhost`
We need to ensure that all required services for the `vhost` feature will work on `ARM64`. Additional information for this need to be provided by @nkraetzschmar and @gehoern.

**Comment by chrinorse** [comment]
I took a look at the ```vhost``` feature.The feature has a file 'pkglist' that contains a list of packages.
```
libvirt-clients
libvirt-daemon-system
qemu-kvm
qemu-utils
```
As far as I understand this, the file 'pkglist' is not used, additional packages should be defined in a file named 'pkg.include'. Also there is no package in the Debian repository named 'qemu-kvm'.
To make the existing packages available, we need to mirror them in the Gardenlinux repository.

@nkraetzschmar, @gehoern What packages are needed in this feature?
