### ISSUE TITLE
Deprecate and archive `gardenlinux-selinux-module`

### ISSUE THREAD

**Issue by chrinorse** [gardenlinux/gardenlinux#1118]
**What would you like to be added**:
after adding the Fedora Selinux Policies, we need to extend the Gardenlinux Selinux policies
**Why is this needed**:

**Comment by gyptazy** [comment]
Hi @chrinorse,

as discussed within our weekly meeting, we may deprecate this package (and archive the GitLab project (https://gitlab.com/gardenlinux/gardenlinux-package-gardenlinux-selinux-module)) with finalizing https://github.com/gardenlinux/gardenlinux/issues/1115. `selinux-fedora` already covers these rules (and many more); additional Garden Linux specific ones will be applied as Debian patches. I've renamed this issue.

(cc: @nanory @gehoern)

**Comment by chrinorse** [comment]
As soon as PR #1186 is merged, we can archive the gardenlinux-selinux-module repository.

**Comment by gyptazy** [comment]
Closing this issue in favor of: https://github.com/gardenlinux/gardenlinux/issues/1199
