### ISSUE TITLE
Integrate platform tests in GitHub Pipeline

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#1128]
**What would you like to be added**:
Add platform tests to GitHub pipelines for the following platforms:
- aws
- azure
- gcp
- ali 
- openstack

The platform tests must run after the build step. 

**Definition of Done**
- [ ] Dedicated Accounts on all hyper scalers 
    - [x] aws
    - [x] azure
    - [x] gcp
    - [x] ali  
    - [ ] openstack
- [x] Setup of `oidc` connection
- [x] Glue code to invoke the platform tests 
    - [x] executes after each GitHub build stage successfully 
- [x] Documentation

**Why is this needed**:
- Start platform tests early with (potentially) every build, so that bugs and regression can be found early in the release process
- Automatically running the platform tests which where previously manually executed. This increase significantly the quality of Garden Linux Development

**Comment by marwinski** [comment]
Please do add OpenStack.

**Comment by Vincinator** [comment]
Added openstack to **definition of done**

**Comment by gehoern** [comment]
make sure to syncronise with the github actions pipeline for the explicit case of e.g. creating an beta realease and make such a "beta" release is triggered ~weekly.

(integration pipeline tests must be triggered somewhat manual but in a way that everybody understands how and we at least once a week test if it could be triggered)

**Comment by Vincinator** [comment]
I suggest to run integration tests automatically for pushes to a release branch

```
on:
  push:
    branches:
      - main
      - 'releases/**'
```

**Comment by Vincinator** [comment]
Additionally, we can add the option to manually run integration tests. Would look like this: 
```
on:
  push:
    branches:
      - 'releases/**' 
  workflow_dispatch:
```

**Comment by Vincinator** [comment]
related #246

**Comment by gyptazy** [comment]
Hey @Vincinator,

I think we should also add `vmware` and `firecracker` (which already got covered by #1318) to the DoD. As a result, we have all ones covered here instead of multiple issues.

Maybe you can provide a short list of todos for a potential `vmware` integration (hypervisor kit etc.)?
