### ISSUE TITLE
Provide Debug Toolbox/Container for Garden Linux

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#1134]
**What would you like to be added**:

As an operator I want to be able to use a variety of tools on my Garden Linux machine for debugging purposes. One option is to bing a script like the [CoreOS toolbox](https://github.com/coreos/toolbox) and provide a docker image for that purpose.

**Why is this needed**:

So far installing additional software for debugging purposes on Garden Linux was relatively simple. This is getting more difficult with `/usr` being a dm-verity volume and the removal of the package system. Even today it is not recommended as we maintain particular versions for quite some time and new software packages bring new versions of dependencies that might be harmful (just noticed that case).

Providing a garden linux container image based on Debian plus a toolbox script should do the job. The difficulty might be the `libdb` component which might get installed.

**Comment by Vincinator** [comment]
Related to: #496 

This debug container should come with either pre-installed kernel headers (for supported releases), or with a script that identifies the host kernel, and installs the matching kernel headers.

**Comment by gehoern** [comment]
i guess this could be a initial thought on this: https://github.com/gardener/ops-toolbelt.

at the moment create this container like the kernel/package build containers used in our pipelines. Base containers are not yet released.

**Comment by nanory** [comment]
We should probably complete this task first before we finish #1191. After some discussion with @marwinski, we probably don't need some packages that have been added for debug reasons especially once we are going to have this debug container:
Check what packages could be removed and discuss with the Gardener team.

**Comment by chrinorse** [comment]
The PR contains a script and systemd services to create and start a container that is accessible via ssh. Depending on the configuration, the container is build, imported from an archive or pull from a registry. The PR also has a readme with more details.
