### ISSUE TITLE
Make Garden Linux work with Azure Gen2 machines

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1141]
**What would you like to be added**:
Azure supports so called Gen2 machines which have some requirements for the Garden Linux images (e.g. bianry format etc).
More information about Azure Gen2 can be found here:
* https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2

Take a look at Azure Gen2 and identify issues that must be resolved before enabling Garden Linux to be deployable on Gen2 machines.
Then, those issues must be fixed.

**Why is this needed**:
Enable Garden Linux for Azure Gen2 machines

**Comment by gehoern** [comment]
duplicate #345
