### ISSUE TITLE
Add comparison with other popular Linux distros

### ISSUE THREAD

**Issue by matteoolivi** [gardenlinux/gardenlinux#1159]
**What would you like to be added**:
Hello, I'm new to Gardener and not too knowledgeable about Operating Systems internals.

It would be great if someone could add a brief comparison between `gardenlinux` and other common linux distros, or explain slightly more in detail what are the advantages of using `gardenlinux`. For example, why is it the best for `gardener`?

**Why is this needed**:
To help people better understand whether `gardenlinux` is what they need with `gardner`.

**Comment by gyptazy** [comment]
Hey @matteoolivi,

thanks for the suggestion. While this is only slightly covered by https://github.com/gardenlinux/gardenlinux#features we might really adjust and highlight the features and benefits of Garden Linux. Maybe you can provide some hints what new users might care especially for and which topics should definitely be covered like easy-updating, security focuses etc.?

Maybe you can provide some input for us.

Thank you very much!

Cheers,
gyptazy

**Comment by gyptazy** [comment]
Hey @matteoolivi,

unfortunately, no further feedback was given. Therefore, I close this issue. We continuously update the `feature` chapter within the `READM.md` to provide an overview of GL. However, feel free to (re)open (this) issue if you're missing something specific.

Thanks!
