### ISSUE TITLE
Get newer coreutils version into Debian

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1182]
**What would you like to be added**:
As of now, the newest `coreutils` version available in Debian is [8.32](https://tracker.debian.org/pkg/coreutils). However, the upstream project already provides a newer version [9.1](https://ftp.gnu.org/gnu/coreutils/)

We should ask the maintainer to update the current version in Debian.

**Why is this needed**:
Version 8.32 is more than 2 years old, so we should keep the Debian package up-to-date.

**Comment by nanory** [comment]
Quick update,

since Sunday there is already a wishlist bug report for `coreutils` that requests an update to the newest upstream release:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017354

I would suggest to wait a couple of days to see what happens with this bug report. Otherwise, we probably would need to update `coreutils` by ourselves.

**Comment by waldiTM** [comment]
https://tracker.debian.org/news/1363831/accepted-coreutils-91-1-source-into-unstable/

**Comment by nanory** [comment]
Since `coreutils` 9.1 has been released in `sid`, we are now taking this package for the Garden Linux repo instead of our self build version: https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/today.yaml#L39-43

Once the package has been moved to Debian testing, we will adjust the package configuration. For now however, this issue can be closed.
