### ISSUE TITLE
Make Garden Linux work with Azure Gen2 secure boot

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1189]
**What would you like to be added**:
During testing of #345 we noticed that Garden Linux works with Azure Gen2 machines in general but that there are still issues with secure boot. Things that must be considered:
* Ensure the image is started with the right parameters to enable secure boot.
* We must upload custom keys so that secure boot works with our signatures.

**Why is this needed**:
We will also need secure boot in Azure at some point, so it makes sense to adjust everything (especially the pytests) to work with Azure Gen2 and secure boot.

**Comment by gehoern** [comment]
can we boot with private bootkeys? or do we need a microsoft signed one?

**Comment by chrinorse** [comment]
After checking all options connected to Azures trusted launch feature and asking in the support forum. It is not possible to add your own keys for secure boot to Azure. That will may change in the future but for now it is not possible.

https://docs.microsoft.com/en-us/answers/questions/995916/secure-boot-with-custom-keys.html

**Comment by nanory** [comment]
Quick update to this issue. There will be a meeting on 25th of October with some Azure developers, in which we will discuss what other possibilities we have to ensure our signed secure boot variants can be verified by Azure and therefore successfully be booted on Azure instances. Once we have a proper outcome, we will update this issue again.

**Comment by chrinorse** [comment]
After meeting with Microsoft engineers, it does not look like there will be an option to use custom keys for  secureboot anytime soon. Closing ticket.
