### ISSUE TITLE
Evaluate what it would mean to remove SSH from Garden Linux

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1193]
**What would you like to be added**:
SSH isn't explicitly necessary for Garden Linux by default. However, it is installed by the `server` feature so it is part of most GL images.

Typically, SSH is used to debug running Garden Linux VMs on cloud providers but in such cases GL is also used with `gardener` which provides a container runtime and Kubernetes. This way, one could spawn a debug and troubleshot container with root privileges to debug the host system. SSH isn't necessarily needed then.

Next, we use SSH for pytest. Removing SSH could be more complicated, so we will probably not be able to remove SSH completely but we may be able to just install and provide SSH during our pytests but do not need to already provide SSH in the GL image right from the beginning.

There may be other cases, too. As a result, we should analyze the implications of removing SSH from GL, check if it is possible and verify what efforts and issues we would have to solve.

**Why is this needed**:
Without having SSH installed, we also lose a lot of hardening requirements which would make our life much easier.

**Comment by nanory** [comment]
After discussing this issue with @gehoern, we noticed that in some cases removing SSH completely might not work in some cases. 

However, we should at least try to disable SSH there it is applicable. Not every use case requires SSH and by default, we should disable SSH everywhere, where no issues are likely.

For this reason, we could try to move all SSH related configuration, packages and other related tools to a dedicated `ssh` feature. This way, one can disable the SSH feature then it's not needed but there is still the possibility to enable it, if required.

We should start with this then. Create a dedicated `ssh` feature, containing everything required to install and run SSH. It also makes sense to configure things like `fail2ban` in such a dedicated SSH feature.

**Comment by gyptazy** [comment]
I'm currently integrating this as an optional feature together with an optional fail2ban (#302). By providing feature sets, it's in the operators decision.
