### ISSUE TITLE
SELinux: Patch `selinux-policy-default` in GitLab

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1200]
### General
On Fri, 19 Aug 2022, a new version of refpolicy (Version: 2:2.20220520-2) got migrated to Debian Testing (see also: https://tracker.debian.org/news/1355553/refpolicy-2220220520-2-migrated-to-testing/). Luckily, this version fixed several issues we already had in the past but still needs some further patches to fit our needs.

### Task
Integrate this `selinux-policy-default` within our GitLab pipeline and add the needed patches to make SELinux work in `enforcing` mode for the regular base system services.

**Comment by gyptazy** [comment]
This got integrated within our GitLab pipeline including further patches regarding the `refpolicy`:
https://gitlab.com/gardenlinux/gardenlinux-package-refpolicy

While this is still untagged it can only be used by downloading the artifact from the pipeline. All further tests are based on `selinux-policy-default_2.20220520-2gardenlinux~0.620266804.e0f429ff_all.deb`.  To finish this task this needs to be tagged.

fyi @nanory

**Comment by nanory** [comment]
Hi @gyptazy,

in general, the new package for `refpolicy` looks good to me but we should align the project with other package projects in Gitlab. 

For example, we should have a dedicated `LICENSE.md` and `README.md` so that the project attributes are set properly. Check out the [cyrus-sasl2](https://gitlab.com/gardenlinux/gardenlinux-package-cyrus-sasl2/-/tree/main/) project as an example for this.

**Comment by gyptazy** [comment]
> Hi @gyptazy,
> 
> in general, the new package for `refpolicy` looks good to me but we should align the project with other package projects in Gitlab.
> 
> For example, we should have a dedicated `LICENSE.md` and `README.md` so that the project attributes are set properly. Check out the [cyrus-sasl2](https://gitlab.com/gardenlinux/gardenlinux-package-cyrus-sasl2/-/tree/main/) project as an example for this.

@nanory, ack done. Thanks.

**Comment by nanory** [comment]
Looks good to me, now. You can release it and keep in mind to add it here:
https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/today.yaml

**Comment by gyptazy** [comment]
Package release.
