### ISSUE TITLE
vhost feature: libvirtd are not starting

### ISSUE THREAD

**Issue by chrinorse** [gardenlinux/gardenlinux#1225]
**What happened:**
The vhost feature installs libvirtd, but the  systemd unit fail to start
* libvirtd can't find /etc/pki/CA/cacert.pem since there is no pki installed

**Comment by gyptazy** [comment]
Hey @chrinorse,

are you on the current `main` branch? At least the first one is fixed by https://github.com/gardenlinux/gardenlinux/commit/a4d0a6e142939510c3c8ca94d99eafdc36120a6b.
