### ISSUE TITLE
Unable to build ISO

### ISSUE THREAD

**Issue by mamachac** [gardenlinux/gardenlinux#1307]
**What happened:**
- I am not able to build onmetal iso image, please check error below

**Debug Logs:**
Drive current: -outdev 'stdio:output/metal_iso-amd64-today-f73656f7/rootfs.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  427m free
xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Added to ISO image: directory '/'='/tmp/CD_root'
xorriso : UPDATE :      16 files added in 1 seconds
xorriso : UPDATE :      16 files added in 1 seconds
xorriso : NOTE : Copying to System Area: 432 bytes from file '/usr/lib/ISOLINUX/isohdpfx.bin'
xorriso : WARNING : Boot image load size exceeds 65535 blocks of 512 bytes. Will record 0 in El Torito to extend ESP to end-of-medium.
libisofs: NOTE : Aligned image size to cylinder size by 312 blocks
xorriso : FAILURE : Image size 232448s exceeds free space on media 218888s
libisofs: MISHAP : Image write cancelled
xorriso : NOTE : -return_with SORRY 32 triggered by problem severity FAILURE
root@zero:~/gardenlinux# df -h .
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/zero--vg-root   28G  5.0G   22G  19% /

**How to reproduce it**:
apt-get install curl wget gnupg2 -y
source /etc/os-release
sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"

wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | apt-key add -

apt-get update -qq -y
apt-get -qq --yes install podman

echo 'unqualified-search-registries = ["docker.io"]' >> /etc/containers/registries.conf

git clone https://github.com/gardenlinux/gardenlinux.git

cd gardenlinux/
 ./build.sh --features server,metal,_iso
 
**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | main |
| Container runtime (version)  | podman (3.0.1)| 
| Host OS of build machine  | debian bullseye | 

- *Please feel free to add additional details*

**Anything else we need to know**:
Building of image is working with command: ./build.sh --skip-tests --features server,cloud,kvm out

Is it possible to fix it or i can use some other command? Thank you very much.

**Comment by 5kt** [comment]
@mamachac your problem here is because you don't have enough RAM on the build system. By default, we use a tmpfs to build everything and then move it to the build directory on the host. 
Please use --lessram when building if your build machine doesn't have enough RAM.
