### ISSUE TITLE
Ensure DISA Stigs compliance

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1352]
**What would you like to be added**:
We already have features which ensure that Garden Linux is either CIS complaint or FedRAMP complaint. It would be good to also have a feature which introduces [DISA Stigs](https://public.cyber.mil/stigs/) complaint Garden Linux images. For this, we should provide a DISA Stig feature.

In order to achieve this, the following steps needs to be fulfilled:
* [x] Get use to DISA Stig. Understand what criteria they have and what they require
* [x] Find a script/scanner which checks software or images according to DISA Stig.
* [x] Manually run the scanner and check what issues we have with Garden Linux
* [ ] Create a feature which fulfills the DISA Stig requirements
* [ ] Clarify all uncertainties and find proper solutions
* [ ] Integrate the script/scanner as an unit test to the newly created feature

**Why is this needed**:
We should be DISA Stig complaint.

**Comment by adaevitncar** [comment]
Requirements changed, actual only a description how to get the scanner up and running is neccessary:

1. Create a corresponding Image of Gardenlinux
2. Download latest SCC (for Ubuntu as deb) from https://public.cyber.mil/stigs/downloads/ (this will deliver the Ubuntu Baseline too)
3. Place downloaded file into the image and install the deb from the extracted file
4. Execute the command line scanner, configure it via an option and trigger the scan from the menu:

`sudo LD_LIBRARY_PATH=/opt/scc/lib64/ /opt/scc/cscc --setOpt ignoreCPEOVALResults=1 --config`

From the menu select "9". Scan will start and results will be saved.

**Comment by nanory** [comment]
Quick update to this issue. As @adaevitncar mentioned, the requirements of this issue slightly changed. We were able to run a DISA Stigs (SCC) scanner in a Garden Linux image and collect all findings.

Using the CIS feature increased the scanner scoring. For now, this is everything we need to know. Integrating the scanner into the pipeline and creating a dedicated DISA Stigs feature is not required at the moment and may be realized in the future. For now however, this issue is completed and can therefore be closed.
