### ISSUE TITLE
[META] Create Garden Linux container images

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1387]
# Overview
Currently, Garden Linux is built for metal, KVM and hyperscaler targets. However, we really want to see Garden Linux container images (artifacts) that can instantly be used with Docker or Podman. This also includes the publishing process to public registries, replacing the build images within the primary Garden Linux build pipeline and further implementations and tools to be `distroless` alike. To accomplish this, we'll create iterative tasks to solve this step by step.

# Tasks

## Overview:
- #1388
- #1389
- #1413
- #1390 
- #1391 
- #1392

## Build pipeline integration
Issue: #1388

The creation of the container artifact must be implemented within the Garden Linux build pipeline. However, we may have different approaches to solve this. Therefore, we need to evaluate the possibilities and integrate this. A possibility could lead into creating a `gardenlinux-base` container image when no platform type is defined but might break other things (e.g. `garden-feat` later). As a result, this must be analyzed.

## Add feature for building a basic container image
Issue: #1389

A new features for creating a basic container image must be introduced that creates a `gardenlinux-base` container image. This should also include all changes that are currently added on top of the currently used Debian testing slim image to fit our needs.
The final artifact should be a container compatible tarball file including its metadata file that can be used with common tools like `docker`, `podman`, `skopeo`, etc. for further usage.

## Push container artifacts to public registries
Issue: #1390

The newly created container image must be pushed to one or more public registries where users may consume the image. However, we still need to evaluate which registers to use, which version to use and how frequently to push. Maybe it could be done during the nightly jobs to push the container image.

## Replace image in build pipeline
Issue: #1391

Currently, the build pipeline is based on Debian testing slim. As soon as the newly created `gardenlinux-base` container image is published to public registries, we may replace the images within the build pipeline by this one.

## Distroless alike container image
Issue: #1392

To fit the users needs we might create and deliver additional toolsets for a distroless alike container image. This means, that a toolset must be created that identifies unneeded tools and libraries, removes `dpkg`, `apt-get` etc. This must be delivered as dedicated scripts to offer further modifying of the image by the user and only run as one of the last steps to "slimify" the image. This should be distroless alike and can optionally be called by a user.

**Comment by Vincinator** [comment]
Publishing of Container Images is implemented. 
PR https://github.com/gardenlinux/gardenlinux/pull/1712 closes this issue
