### ISSUE TITLE
GL Container Images: Push container artifacts to public registries

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1390]
## Push container artifacts to public registries

The newly created container image must be pushed to one or more public registries where users may consume the image. However, we still need to evaluate which registers to use, which version to use and how frequently to push. Maybe it could be done during the nightly jobs to push the container image.

**Comment by gyptazy** [comment]
Unfortunately, I do not have enough permissions to create, adjust and add the GitHub secrets to solve this issue. This can only be proceeded by placing the needed secret to push artifacts to the `Google Artifact Repository`.

**Comment by Vincinator** [comment]
Publishing of Container Images is implemented. 
PR https://github.com/gardenlinux/gardenlinux/pull/1712 closes this issue
