### ISSUE TITLE
GL Container Images: Replace image in build pipeline

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1391]
## Replace image in build pipeline

Currently, the build pipeline is based on Debian testing slim. As soon as the newly created `gardenlinux-base` container image is published to public registries, we may replace the images within the build pipeline by this one. Additionally, it should fix the `make slim` Makefile target.

**Comment by gyptazy** [comment]
This issue depends on #1390 and can only be proceeded afterwards.

**Comment by Vincinator** [comment]
todos left for this:
- change need slim script to use appropriate Garden Linux container
- update all `container/*/Dockerfile` to add debian testing apt repo if required
- remove container that we do not need anymore for builds with new builder (e.g. build-image)
