### ISSUE TITLE
image is not booting in libvirt kvm environment

### ISSUE THREAD

**Issue by ubi2go** [gardenlinux/gardenlinux#14]
we build the kvm image today and testing it in our cloud environment, but the image stales during boot.

is stales first at: [sda] Attached SCSI disk

if you tip on the keyboard the next line appears: random: crnd init done

could be related to your machine type: machine='pc-i440fx-4.2'

[output.libvirt.xml.txt](https://github.com/MalteJ/gardenlinux-manifest/files/4449338/output.libvirt.xml.txt)

![vnc-output](https://user-images.githubusercontent.com/42961839/78764758-50b7f380-7987-11ea-82ec-34012a49b906.jpg)

**Comment by marwinski** [comment]
Do you still have this issue? This is working fine for us. I have also introduced a script that starts a VM without KVM in ```bin/start-vm-no-kvm``` as I only have a VM on my development machine. 

We have seen a similar issue like the one above on VMware. The reason appeared to be (hardware) flow control on the serial console on VMware that stopped the output while the VM booted successfully. Can you provide additional input.

**Comment by marwinski** [comment]
Hi @ubi2go. Did you check this again? Do you still have the issue. A problem might have been a light mess-up in the kernel cmdline: the ttyS consoles must come before the tty0 console which messed up our boot on at least one other environment (no the boot worked fine but the machine did appear hung)

**Comment by ubi2go** [comment]
We ran the test with the last version and the problem is solved.
