### ISSUE TITLE
Use latest available garden linux suite for release builds

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#1401]
**What would you like to be added**:
Creating a new patch release for Garden Linux(e.g. 955.1) requires to update the VERSION file in the `rel-955` branch. 

I argue that if we create a `955.1` suite in our repo.gardenlinux.io, that we also intend to use `955.1` for the `rel-955` branch release builds. 

Therefore the manual step of updating the VERSION file `955.0 -> 955.1` can be eliminated. 

**Why is this needed**:
Reducing manual steps

**Comment by MrBatschner** [comment]
I agree, having the repo tree `xxx.Y` and having `xxx.Y` in Garden Linux' VERSION file should be intertwined.
