### ISSUE TITLE
Slim down images: Move packages from `server` layer to `_dev`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1404]
While updating all `README.md` files I encounter the following packages within the `server` feature:
https://github.com/gardenlinux/gardenlinux/blob/main/features/server/pkg.include#L27-L30

IMHO, we should keep the features minimal and move those packages to the `_dev` feature which would lower the overall image size.

Opinions? @credbbl @Vincinator @MrBatschner @gehoern @nanory

**Comment by MrBatschner** [comment]
Removing any of these packages would make debugging anything OS related in a productive environment an absolute pain in the  back. `wget` is required for Gardener bootstrapping.

**Comment by gyptazy** [comment]
I think currently you're absolutely right, but with upcoming features in the near future we might change this. I think we could solve this by #1134 as well as we could provide an "inject script" that copies needed binaries for this (we're always running on testing, so we might fetch the debs, extract them and inject them directly) for debugging. However, this might only work on these low dependency package where all required libs are already present. However, immutable systems might make some further trouble here.

Probably you're right and we shouldn't make such a big effort to just get rid of some small packages.
