### ISSUE TITLE
Replace tools in test containers with proper packages

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1405]
**What would you like to be added**:
As of now, we are using multiple external binaries in our `integration-test` container. In order to enhance security, it would be good to validate the integrity of such binaries and tools. Usually, this can be done by checksums like discussed in #1383. However, some binaries like `awscli` are not versioned, so they are updated continuously which makes validation based on checksums complicated.

A better solution would be the usage of signatures which leads to the question: "Why not using a package management system that already provides such functionality".

For that reason, we should take a look into the binaries used in the `integration-test` and `base-test` containers and replace them with equivalent packages from Debian or PIP.  

**Why is this needed**:
This is needed to enhance the overall security of our test pipeline.

**Comment by gyptazy** [comment]
PR available #1425
