### ISSUE TITLE
Building kernel modules for v934.1 (x86)

### ISSUE THREAD

**Issue by Molter73** [gardenlinux/gardenlinux#1410]
Hi, a few months ago I created an issue asking about availability of kernel headers for compilation of some kernel module and eBPF probes: https://github.com/gardenlinux/gardenlinux/issues/685

At the time, I was advised to use the `component-descriptor` asset in the release to get the version of the kernel being used, then extrapolate the URLs where the headers could be found. I went ahead and automated crawling of those headers based on that file, but the latest release (934.1) doesn't have a `component-descriptor` and http://repo.gardenlinux.io/ is still not browsable. Could I get some pointer on how I could automate crawling of the kernel headers used by Garden Linux again?

**Comment by Vincinator** [comment]
Hi, 

the source of truth for the available kernel version is the repo.gardenlinux.io, at least that is where the garden linux build is retrieving the kernel packages. Each released version has a corresponding suite in the repo.
The repo has indeed directory browsing via http(s) disabled.

Please note, that old kernel versions will not be deleted in the respective repo suite. 
Thus, you need to filter for the greatest kernel version available in that suite. 
But newer kernels will require a Garden Linux version upgrade; either in major, or in minor version - depending on the changes of that kernel.


Here are some pointers on how to browse the repo:

# apt search
Use this if you are on a Garden Linux system and want to search for a particular package. 
- required:`deb https://repo.gardenlinux.io/gardenlinux 934.1 main` is listed in either `/etc/apt/sources.list` or a `/etc/apt/sources.list.d/some-file`
- use `apt search linux-image | grep gardenlinux | sort -r | head -n 1` to search and filter for the greatest available kernel version

#  Use the Package file from the repository
Use this if you do not have apt available, or if you are concerned with the "apt does not have a stable CLI interface" warning.
```
curl -s http://repo.gardenlinux.io/gardenlinux/dists/today/main/binary-amd64/Packages | grep -e "Package: linux-image-5.15.[0-9].*" | sort -r | head -n 1 | cut -d'-' -f3
```

----
Let me know if this works for you.

Thanks,
Vincent

**Comment by Molter73** [comment]
Hi @Vincinator,

Thanks for the quick reply, I'll give your suggestions a spin and get back to you.

My main concern is finding a reliable way that we can automate crawling for the kernel headers, we've rebuilt the way we crawl them a few times over the past year and I'd think by now we would already have this solved, yet here we are, having to change it once more.

**Comment by Vincinator** [comment]
Sure @Molter73, looking forward to your feedback. 

However, I am not sure if I am happy with the `curl` solution myself. 
It is the closest to the source of truth, yes - but it is also a bit hacky.  

I like the idea of including the `component-descriptor` in the release assets. 
I need to check if this is a bug. I suppose it has not yet been ported to the new release pipeline.

**Comment by Molter73** [comment]
Any word on re-adding the `component-descriptor` back to the releases? I noticed 934.2 also doesn't have it.

If this is not coming back, I'll need to implement another way of collecting kernel headers using the `apt search` alternative.

**Comment by Molter73** [comment]
Hey @Vincinator,

Sorry to be insisting on this, we use the `component-descriptor` file to find the headers and build drivers for StackRox/RHACS, is there any update on it?

**Comment by Vincinator** [comment]
Hi @Molter73, sorry for the delay.
We will bring back the `component-descriptor`, I just got the development process rolling.

**Comment by Vincinator** [comment]
Quick update so you can plan accordingly: this will take probably 2-3 weeks. 

Please let me know If you need support for the `apt search` approach. 
Component-descriptor is currently build in a non-public infrastructure, getting it out there requires some extra steps.
On the long run, I see this `component-descriptor` created via the public github actions pipeline definitions, this is currently blocked and de-prioritized.

Sorry for the inconvenience. I will keep you updated.

Thanks

**Comment by Molter73** [comment]
Thanks for the update @Vincinator!

We will not need to support the `apt search` approach if the `component-descriptor` is added back, but I will need it to manually add new kernels released for Garden in the meantime.

As an example, I see that version 934.3 was released recently, I will need to use the `apt search` approach to check whether it uses a new kernel and add it to our infra. If it had the `component-descriptor` as part of the release, our crawler would do that by inspecting the file instead.

**Comment by Molter73** [comment]
@Vincinator any updates on this? 🙂

**Comment by Vincinator** [comment]
hi @Molter73 sorry for the late reply. 
I am taking the implementation over, working on it. Will come back to you

**Comment by Molter73** [comment]
First off, thanks for all the effort you've put into this @Vincinator!

I've manually added the URLs for the headers of all previous versions, so there's no need to add it to previous releases. Our crawler will run in about an hour, I'll let you know if it picks it up correctly.

Would this mean the next release will have the `component-descriptor` file?

**Comment by Molter73** [comment]
Looks like the component descriptor doesn't have the information for the non-cloud images. I can make a small change in our crawler to deduce the package though, so for our use case this is enough, but thought it might be something you'd like to look into.

**Comment by Vincinator** [comment]
> Would this mean the next release will have the component-descriptor file?

Still need to automated it, but I don't see any blockers for it. Will integrate it next week, so yes, next version should(tm) have the `component-descriptor` again. 

> Looks like the component descriptor for 934.6 doesn't have the information for the non-cloud images. I can make a small change in our crawler to deduce the package though, so for our use case this is enough, but thought it might be something you'd like to look into.

I'll have to look into this. Thanks for the info!

**Comment by Molter73** [comment]
Thank you for all the work on this @Vincinator!
