### ISSUE TITLE
Automatically create package manifest for patch releases

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#1427]
Every patch release of Garden Linux, i.e. a release that does not end in `.0` needs to have a package definition in for [repo.gardenlinux.io](https://repo.gardenlinux.io/) in [GitLab](https://gitlab.com/gardenlinux/gardenlinux-package-build/-/tree/main/packages) like [this](https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/934.1.yaml) for Garden Linux `934.1`.

**What would you like to be added**:

Upon releasing a Garden Linux version for productive use, this file should be automatically created for the next patch release by copying the existing file (for any release `XXX,Y` with Y > 1) or created with reasonable defaults (for any release `XXX.Y` with Y = 1).

**Why is this needed**:

Streamlining and automating the Garden Linux release process with as minimal manual interaction as possible.

**Comment by Vincinator** [comment]
Yes, I also think this is a good idea.

We need to agree where(1) and how(2) we want to trigger the process. 

Maybe:
1) github.com/gardenlinux/gardenlinux
2) create a git tag which triggers a github action. The github action could create an automated PR in [Gitlab Package build repo](https://gitlab.com/gardenlinux/gardenlinux-package-build/-/tree/main/packages)

**Comment by nanory** [comment]
Hi @Vincinator,

as discussed in our last meeting, it may be too complicated to fully automate this procedure. However, for a first iteration, we should introduce a helper tool, which makes the creation of such patch release and a corresponding package configuration file easier. 

For this reason, I've created the following issue, that is about implementing such a script:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/issues/51

**Comment by Vincinator** [comment]
Closing this issue, since we have established a process. Feel free to ping me, or re-open this issue if you think this is still relevant.
