### ISSUE TITLE
_readonly feature breaks kvm build

### ISSUE THREAD

**Issue by morbitzer** [gardenlinux/gardenlinux#1432]
**What happened:**

Adding the _readonly feature breaks the build, it stops with the error:

```
::/legacy/5.15.79-gardenlinux-cloud-amd64/initrd.img-5.15.79-gardenlinux-cloud-amd64: no match for target
Bad target ::/legacy/5.15.79-gardenlinux-cloud-amd64/initrd.img-5.15.79-gardenlinux-cloud-amd64
make: *** [Makefile:55: kvm] Error 1
```

**Debug Logs:**

[kvm_readonly-amd64-today-local.log](https://github.com/gardenlinux/gardenlinux/files/10074448/kvm_readonly-amd64-today-local.log)

**How to reproduce it**:
 
- Add `_readonly` to `make_targets/kvm`. 
- Execute ` make kvm BUILD_OPTS=--debug`

**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | *main, commit 69541ddf* |
| Container runtime (version)  | *podman (3.0.1)* | 
| Host OS of build machine  | *Debian 11* | 

While I'm aware that _readonly does currently not work with gardener (#1191), to my understanding it should be compatible with the kvm build. This did work around 3 months ago before the new Makefile was introduced.

**Comment by gehoern** [comment]
we are currently in an audit cycle regarding _readonly. i guess there ware a major update 5 days ago. Since the ticket is 7 days old ... can you retest plz? thanks

**Comment by morbitzer** [comment]
Indeed, the feature is working again!
