### ISSUE TITLE
`Pytest`: Change test platform for test `garden-feat`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1439]
### General
In Garden Linux, Pytest is used for all unit-, platform- and integration tests. Currently, the unit test for `garden-feat` (located in base/test/) uses the `chroot` platform. While this works it may be uncommon to use a remote platform for running local tests. We might change this to the `local` platform as soon as this is present. (Depends on #1437).

**Comment by chrinorse** [comment]
Solved with PR https://github.com/gardenlinux/gardenlinux/pull/1469
