### ISSUE TITLE
REPO_LAYOUT.md Feedback / Discussion

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#15]
I like the proposal but have some comments and suggestions.:

# Versioning Scheme

What are we doing with failed / broken builds? Are we only assigning build numbers to "release" builds and tag the other ones as something like "dev", e.g. ```10.2-dev``` and only upon release mark them as ```10.2```?

Apart from that this looks quite ok. BTW, April 1st is day 1, not 0 as you wrote further down below.

# Release Channels

I don't quite understand the difference between greatest and stable (no it is not self explanatory). I would have used them as synonyms. How about ```stable```and ```experimental```?

# Artifact / file names 

We probably need multiple levels: we don't just have dev and prod but also ghost (with docker) and chost (with containerd). 

# Example

I like the CoreOS notation where they store the AMI number for the various hyperscaler regions in txt files attributed with the region name.

**Comment by ccwienk** [comment]
I think this can be closed. repository layout is de facto there (documentation pending)
