### ISSUE TITLE
Check feasibility for adding the sssd package

### ISSUE THREAD

**Issue by kayrus** [gardenlinux/gardenlinux#1503]
**What would you like to be added**:

sssd is used for AD/LDAP based identity management on the PAM/NSS level

**Why is this needed**:

This adds an ability to use AD/LDAP as an authX source.

The list of dependency packages for sssd:

```
libavahi-client3
libavahi-common-data
libavahi-common3
libbasicobjects0
libcollection4
libcrack2
libdhash1
libini-config5
libipa-hbac0
libldb2
libnfsidmap1
libnl-route-3-200
libnss-sss
libpam-pwquality
libpam-sss
libpath-utils1
libpwquality-common
libpwquality1
libref-array1
libsmbclient
libsss-certmap0
libsss-idmap0
libsss-nss-idmap0
libtalloc2
libtdb1
libtevent0
libwbclient0
python3-sss
samba-libs
sssd
sssd-ad
sssd-ad-common
sssd-common
sssd-ipa
sssd-krb5
sssd-krb5-common
sssd-ldap
sssd-proxy
```

And the `base/test/test_password_hashes.py` must be adjusted accordingly, since sssd changes the `[success=1 default=ignore]` string to `[success=2 default=ignore]` causing the `Redundant options defined in /etc/pam.d/common-password` assertion test fail.

cc @Vincinator

**Comment by Vincinator** [comment]
sssd is now in today repo.
