### ISSUE TITLE
make stops during signature check

### ISSUE THREAD

**Issue by schucly** [gardenlinux/gardenlinux#152]
**What happened**:
Make process cannot pass target sign.pub.

**What you expected to happen**:
Ignore missing siganture to sign images and create images as requested.

**How to reproduce it (as minimally and precisely as possible)**:
```
user@localhost:~/gardenlinux$ make clean
rm -rf .build

user@localhost:~/gardenlinux$ make metal
gpg: error reading key: No secret key
No secret key for contact@gardenlinux.io exists, signing disabled
/bin/sh: 1: cannot create .build/sign.pub: Directory nonexistent
make: *** [Makefile:11: sign.pub] Error 2
```

**How to fix**
Directory .build is missing.
Can be added to Makefile to successfully pass target sign.pub.

**Comment by marwinski** [comment]
I have seen that yesterday, too. It helped to create the .build directory manually. I have also created pull request: #154
