### ISSUE TITLE
List of gardenlinux cloud images ID's not on release notes

### ISSUE THREAD

**Issue by flaviomoringa** [gardenlinux/gardenlinux#1564]
From releases 934.2 to 934.6 the release notes of Gardenlinux don't show the list of the cloud images.

Could it be added? Without those we cannot actually upgrade.

Thanks

**Comment by Vincinator** [comment]
Hi @flaviomoringa, I added the cloud image ids to the 934.6 release manually. I will integrate this also in our pipeline for upcoming releases.

**Comment by flaviomoringa** [comment]
> Hi @flaviomoringa, I added the cloud image ids to the 934.6 release manually. I will integrate this also in our pipeline for upcoming releases.

Thank you so much @Vincinator, it's really helpful.
