### ISSUE TITLE
Use of public Slack / Matrix / ... 

### ISSUE THREAD

**Issue by berendt** [gardenlinux/gardenlinux#158]
Currently a Slack channel on a SAP internal Slack server on gardenlinux.io is linked. A login there is only possible with SAP account or an existing guest account. A registration does not seem to be possible. It would be nice if the Slack from Kubernetes could be used like in the Gardener project. A channel #gardenlinux could be created there. Then the channels for Gardener and Gardenlinux would be in the same place, which makes sense in my opinion.

**Comment by marwinski** [comment]
/assign @msohn 

Weren't you involved in doing this for Gardener? Can you please take a look. Thanks!

**Comment by berendt** [comment]
Any news here? From a community point of view the use of an internal slack is quite suboptimal...

**Comment by berendt** [comment]
@msohn @marwinski After almost a year, this is still SAP internal. Could this be switched to Kubernetes' Slack?

**Comment by Natureshadow** [comment]
I'd like to propose to not do any public community communication on Slack. Slack is a closed, exclusive platform that is not open to everyone. It is restricted by age and, depending on the country, even by the profession of the users.

Gardenlinux should instead drive the migration to an open platform like Matrix forward, which has already been started by using Gitter.im

**Comment by berendt** [comment]
@Natureshadow That's fine too. The Kubernetes Slack was just an idea as it is definitely more open than an SAP internal medium. I'll adjust the topic.

**Comment by Natureshadow** [comment]
I would like to update the website in that regard. I already prepared a patch, but I can neither push to, nor fork, the website repository. Can you make that possible, @gehoern?
