### ISSUE TITLE
Make image format configurable for OpenStack images

### ISSUE THREAD

**Issue by berendt** [gardenlinux/gardenlinux#159]
Currently VMDK is used as image format for OpenStack images. This may make sense on the SAP CC EE. In most OpenStack environments RAW or QCOW2 images are used. Therefore the used image format should be configurable for OpenStack images. QCOW2, RAW and VMDK should be possible.

**Comment by marwinski** [comment]
/assign @berendt 

I currently don't have an OpenStack implementation which can consume qcow2 images and cannot test it however I think it is a good idea to add this format in addition. Not considering possible (and required) options, can you test adding something like this 

```
qemu-img convert -f raw -O qcow2 rootfs.raw rootfs.qcow2
```

to the image script in features/openstack.

**Comment by berendt** [comment]
@marwinski I look at this and open a PR.

**Comment by berendt** [comment]
With #167 it is now at least possible to get a qcow2 image directly.

**Comment by berendt** [comment]
Resolved by 291f38669c361da2aff9aaed5d823a92ddfac7e5. It is sufficient to generate qcow2 images.
