### ISSUE TITLE
Check and remove Python 2.7

### ISSUE THREAD

**Issue by berendt** [gardenlinux/gardenlinux#160]
Python 2.7 is deprecated. It should be checked if Python 2.7 is used. At least the patches directory contains files for Python 2.7.

**Comment by leonardlorenz** [comment]
I wrote a script to check all python files for python3 compatibility. It turns out all of our scripts are valid python3.

```bash
for f in $(find .); do
    if [ ! -d $f ]; then
        header=$(head -n 1 $f)
        contains_py=$(echo $header | grep python)
        if [ ! -z "$contains_py" ] || [[ $f = *.py ]]; then
            echo testing $f
            /home/mtrx/Git/gardenlinux-super/check-p3-compliance.py  $f
        fi
    fi
done
```
./check-p3-compliance.py
```python
#!/bin/python3
import ast
from sys import argv

def test_source_code_compatible(code_data):
    try:
        return ast.parse(code_data)
    except SyntaxError as exc:
        return False
    except IsADirectoryError as exc:
        return False

path = argv[1]
ast_tree = test_source_code_compatible(open(path).read())
if not ast_tree:
    print("Incompatible file:", path)
```
related: https://stackoverflow.com/questions/40886456/how-to-detect-if-code-is-python-3-compatible/40886697#40886697

Does this mean we can safely delete the patches?

**Comment by berendt** [comment]
I do not know if Python 2.7 is actively used anywhere.

If that is the case we should get rid of it in any case.

**Comment by leonardlorenz** [comment]
I've discussed this with @gehoern and @marwinski and we've come to the conclusion that this patch can be removed. I'll make a pull request for this.
