### ISSUE TITLE
component-descriptor file missing from release 934.8

### ISSUE THREAD

**Issue by Molter73** [gardenlinux/gardenlinux#1657]
**What happened:**
- The component-descriptor file that we use as part of the StackRox kernel crawler is missing from the latest release, which in turn prevents us from building our drivers. This was previously discussed on #685 and #1410.

**Debug Logs:**
- N/A

**How to reproduce it**:
- N/A
 
**Environment:**
- N/A

**Comment by Vincinator** [comment]
Yes, sorry. The automation is not done and I have to upload it manually.

**Comment by Vincinator** [comment]
Manually uploaded: https://github.com/gardenlinux/gardenlinux/releases/download/934.8/component-descriptor

**Comment by Vincinator** [comment]
component-descriptor is added to the 934.8 release artifacts now
https://github.com/gardenlinux/gardenlinux/releases/download/934.8/component-descriptor
