### ISSUE TITLE
mlock limit is set to too low value with containerd as runtime

### ISSUE THREAD

**Issue by vpnachev** [gardenlinux/gardenlinux#168]
**What happened**:
Basically, the same as https://github.com/gardenlinux/gardenlinux/issues/81 which was about when docker is used as runtime. 
The mlock limit is set to 64KB when containerd is used as runtile
```
$ ulimit -l
64
```

**What you expected to happen**:
The mlock limit to be increased so that golang binaries to not fail with 
```text
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```
when the runtime is containerd.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with Garden Linux and exec on a container, then run `ulimit -l`.

**Anything else we need to know**:

**Environment**:
Garden Linux version: 184.0

**Comment by marwinski** [comment]
Do you think we need a new Garden Linux release (184.1) for this?

**Comment by vpnachev** [comment]
We will need. Of course, we can also try to mitigate it via the gardener os-gardenlinux extension, but we should try to release Garden Linux firstly.
