### ISSUE TITLE
Remove the example feature

### ISSUE THREAD

**Issue by MalteJ** [gardenlinux/gardenlinux#1688]
The example feature should be part of the builder documentation.
Reference the builder documentation in the Garden Linux docs. We don't need to provide a builder feature example into the gardenlinux repo.

**Comment by gyptazy** [comment]
I think everything regarding this is already covered. This has been done with the following PRs:
* Garden Linux: https://github.com/gardenlinux/gardenlinux/pull/1744/files#diff-162e3e36b33273a45e72b7d45f8882fb18d90ac845ba67503f656ad45635f4e5
* Builder: https://github.com/gardenlinux/builder/pull/23
