### ISSUE TITLE
Outdated docs about build.sh

### ISSUE THREAD

**Issue by MalteJ** [gardenlinux/gardenlinux#1689]
There's still lots of outdated docs, which reference the `build.sh`. We should remove those docs/replace them with info reflecting the builder build-process.
We should not describe details of how the builder works in the gardenlinux repo - this should be done in the builder repo. In the gardenlinux repo we should describe details about gardenlinux-specific implementation.

**Comment by fwilhe** [comment]
As of today I see 4 findings left in the main branch:

tests/README.md
> 117:As described, `chroot` tests are automatically performed after each build. By default, this doesn't include the `kvm` platform and may be added by appending `--tests   chroot,kvm` to the `build.sh`.

bin/garden-integration-test-config
> 4:# helper script for the integration tests called in build.sh

features/_oci/README.md
> 18:$ ./build.sh --features server,cloud,gardener,gcp,_oci .build/

features/_oras/README.md
> 12:$ ./build.sh --features kvm,_oras .build/

I think the instructions in oci and oras should be simple to replace but I currently can't verity that the new commands work. 

Can't judge the other 2 mentions.

**Comment by Vincinator** [comment]
Only `features/_oci/README.md` and `features/_oras/README.md` remain. Updating the build instruction is straight forward, it is a `./build gcp-gardener_oci` or a `./build kvm_oras` respectively. 

However, both features currently do not work with the new builder. The plan is
1. clarify if we need the _oci feature - we will discuss next week
1. fix _oras feature - uploaded fix to `fix/oras-new-builder` branch, not tested yet, need help with setup. Also, next week
