### ISSUE TITLE
Dependency conflict in perl when adding debian testing repos in build process

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#1708]
**What happened:**
- When building GL and adding debian testing sources, running `apt update` fails because of issues with perl.

The expected behavior is that I can run `apt update` with the debian testing sources added.

A workaround is to pin the debian sources to a lower prio.

**Debug Logs:**
- *Build System debug logs if applicable*
  - *To generate debug logs, you may want to add `set -x` at the beginning of invoked bash scripts*
  - *Logs are located in the `<repo>/.build/` folder*
- *Runtime Debug logs if applicable* 

```
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]   Get:7 http://deb.debian.org/debian testing/contrib Translation-en [49.1 kB]
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]   Get:8 http://deb.debian.org/debian testing/non-free arm64 Packages [76.1 kB]
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]   Get:9 http://deb.debian.org/debian testing/non-free Translation-en [67.1 kB]
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]   Fetched 15.5 MB in 2s (6374 kB/s)
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]   Reading package lists...
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] Reading package lists...
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] Building dependency tree...
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] Some packages could not be installed. This may mean that you have
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] requested an impossible situation or if you are using the unstable
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] distribution that some required packages have not yet been created
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] or been moved out of Incoming.
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] The following information may help to resolve the situation:
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] 
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] The following packages have unmet dependencies:
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13]  perl : Depends: perl-base (= 5.36.0-7) but 5.36.0-7gardenlinux1 is to be installed
[.build/kvm-arm64-today-local.tar 2023-07-14 14:18:13] E: Unable to correct problems, you have held broken packages.
completed in 3 seconds
```
<img width="1637" alt="Screenshot 2023-07-14 at 16 18 42" src="https://github.com/gardenlinux/gardenlinux/assets/2292245/baf49f65-e415-49bf-87d0-7cb1e8c85fdd">

**How to reproduce it**:
- *Step by step with the given environment specified in the next section*
 
Take the `demo-apt-issue` branch from my fork at https://github.com/fwilhe/gardenlinux

run `./build kvm`

**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | main |
| Container runtime (version)  | 4.3.1 | 
| Host OS of build machine  | debian trixie/sid arm64 vm on macos host | 

- *Please feel free to add additional details*

**Anything else we need to know**:
- *e.g. last time it worked without the bug?* 
- *e.g. link to your garden linux fork*
- *e.g. tested on other build environments*

**Comment by fwilhe** [comment]
Hi @Vincinator, I just faced this issue again, I was wondering about the status.

My use-case now is that I'd like to install `strace` for debugging purposes which is not in the GL repos.

My workaround is this script in `exec.early`:

```
#!/usr/bin/env bash

set -eufo pipefail

echo 'deb http://deb.debian.org/debian/ testing main contrib non-free' >> /etc/apt/sources.list

tee /etc/apt/preferences.d/99debian-testing-upstream-repo <<EOF
# Never prefer packages from the debian-testing-upstream-repo repository
Package: *
Pin: origin deb.debian.org
Pin-Priority: 1
EOF

apt-get update
```

With this done, I can add `strace` to the pkg list.

The ` /etc/apt/preferences.d/99debian-testing-upstream-repo` config seems to hide the perl dependency issue, which still persists.

**Comment by Vincinator** [comment]
Hi @fwilhe, sorry I could not find a good solution yet and forget to follow up on it.

This is a general issue, and I think for this to work we need some sort of apt pinning. 
Either manually, as you already do, or via a convenient feature of the builder that does this for the user internally.

in the case of `strace`.. well, we definitely should have this in our repo.gardenlinux.io. 


Also, thanks for reporting this. Makes sense to me.

**Comment by Vincinator** [comment]
@nkraetzschmar added `strace` https://gitlab.com/gardenlinux/gardenlinux-package-build/-/merge_requests/378

I will test tomorrow

**Comment by alee-ntap** [comment]
I just reproduced this issue and additionally with `systemd` and `udev` version mismatch:
```
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51]   Get:7 http://deb.debian.org/debian testing/contrib Translation-en [49.5 kB]
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51]   Get:8 http://deb.debian.org/debian testing/non-free amd64 Packages [102 kB]
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51]   Get:9 http://deb.debian.org/debian testing/non-free Translation-en [68.3 kB]
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51]   Fetched 15.6 MB in 2s (9034 kB/s)
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51]   Reading package lists...
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:51] Reading package lists...
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] Building dependency tree...
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] Some packages could not be installed. This may mean that you have
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] requested an impossible situation or if you are using the unstable
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] distribution that some required packages have not yet been created
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] or been moved out of Incoming.
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] The following information may help to resolve the situation:
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] 
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] The following packages have unmet dependencies:
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52]  perl : Depends: perl-base (= 5.36.0-9) but 5.36.0-9gardenlinux1 is to be installed
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52]  systemd : Depends: libsystemd0 (= 254.5-1)
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52]  udev : Depends: libudev1 (= 254.5-1) but 254.5-1gardenlinux1 is to be installed
[.build/kvm-amd64-today-7647a25e.tar 2023-10-10 12:04:52] E: Unable to correct problems, you have held broken packages.
completed in 3 seconds

make: *** [Makefile:55: .build/kvm-amd64-today-7647a25e.tar] Error 100

```

**Comment by alee-ntap** [comment]
I found that it has `Pin-Priority: 100` for `Gardenlinux repo` and `Pin-Priority: 500` for `Debian testing repo` . So the packages from `Gardenlinux repo` are not installation candidates that cause this issue. If we want to accept such user case to build with `debian repo` co exist. We should consider to have `Pin-Priority` set to the same level.

**Comment by alee-ntap** [comment]
The default `Pin-Priority` for all native repositories of the distribution is set to `500`. I'm unsure if GardenLinux has configured the `vendor` settings correctly. Could you please verify this by using the command:
```dpkg-vendor --query Vendor```
in both the "exec.early" and "exec.late" stages?

Upon checking the issue reported in this ticket, it appears that "Debian" is shown in the "exec.early" stage. Consequently, it sets the Pin-Priority to 100 for the GardenLinux repository and 500 for the Debian testing repository. I believe the opposite should be true if the vendor settings were properly configured in GardenLinux.

You can find some examples here: https://salsa.debian.org/apt-team/apt/-/tree/main/vendor

Additionally, I believe we should patch the "apt" and "base-files" packages to include our appropriate vendor settings. This will help avoid any dependency conflicts.
