### ISSUE TITLE
start-vm: Is there any reason to exclude ubuntu from finding the uefi code?

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#1709]
We are testing for the os [here](https://github.com/gardenlinux/gardenlinux/blob/ac4d82e3cea0df3bd63cc5ab291129c14af716fb/bin/start-vm#L442). Ubuntu does not get recognised as debian but has its own entry which is not tested here. In my ubuntu vm, the path for debian also works for ubuntu, so I guess we can just extend the if branch for "if debian or ubuntu".

Anything that I overlooked?

**Comment by Vincinator** [comment]
fixed by https://github.com/gardenlinux/gardenlinux/pull/1714
