### ISSUE TITLE
Discuss solutions to deploy and publish packages while using Github Actions

### ISSUE THREAD

**Issue by alee-ntap** [gardenlinux/gardenlinux#1786]
**What would you like to be added**:
We need to have solution for package deployment and publish to public repository from GitHub Actions workflow.

**Why is this needed**:
Our objective is to streamline the process while ensuring security measures are in place. We have already initiated the creation of package builds using GitHub Actions. Now, we need to address the challenges associated with deploying and publishing these packages within the GitHub Actions workflow.

**Challenges**:
- Handling Multiple Package Uploads: A limitation of Aptly, our chosen package management tool, is that it can only run in a single instance. This raises the challenge of managing multiple package uploads simultaneously within the GitHub Actions workflow.
- Hosting the Aptly Instance: In order to access all deployed packages and store snapshots for publication, the Aptly instance needs to be hosted in a suitable location. This will be referred to as the "aptly instance" throughout this document.
- Security Concerns: Ensuring the security of our software development process. We need to address the following security concerns: 
  - Trusting packages built on public GitHub runners. 
  - Securely deploying the built packages to the aptly instance.
  - Establishing secure access to the aptly instance.

**Possible Solutions Investigated**:
- Utilizing Aptly HTTP REST API for Package Upload:
  - Directly exposing Aptly's HTTP API to the Internet is not recommended due to the lack of authentication and protection.
  - However, the API is not complete yet, as it does not support mirroring. Therefore, an aptly instance is still required to run aptly cli.
  - May do a security implementation as a HTTP proxy for the REST API is needed and maintained. 
- Implementing a Dedicated GitHub Runner:
  - Creating our own GitHub runner provides greater control over security measures.
  - This dedicated runner can internally access unsigned built packages.
  - It facilitates the deployment of unsigned packages.
  - Maintaining a single aptly instance for snapshot and publication becomes more straightforward.
  - This approach is similar to our previous experience with the GitLab runner and offers the potential for code reusability.
- Implementing a Package Upload Handling Pool:
  - Drawing inspiration from the Debian project, we can establish an "incoming/" pool within our aptly instance.
  - This pool can be hosted alongside our aptly instance.
  - Uploading packages to our own incoming/ pool can be achieved using the official Debian **dput** command.
  - Add a GPG signing mechanism ensures the authenticity and integrity of packages built on public GitHub runners.
  - A simple bash script to verify .changes files, import packages into aptly that matches with the gpg key we define, while discarding the rest to optimize disk space usage.

**Comment by nanory** [comment]
We had a discussion with Andre and Vincent last week in which we discussed that we might need to change the publishing part completely by replacing it by something different than Aptly.

We decided that we will wait for Nico's first draft of the publishing in order to compare it with the aptly solution in order to see what effort it would create to implement an alternative solution.

**Comment by nanory** [comment]
Since the publishing part is done by Niko and we finalized the releasing of packages built in Github, we are closing this issue here.
