### ISSUE TITLE
Migrate packages to Github Actions

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#1787]
**What would you like to be added**:
Before we can start to migrate each package pipeline, we need to finish the following issues first, before we can move on with this one:
* #1786 

Once those prerequisites are fullfilled, we can start to migrate each package pipeline to Github. These includes:
* [x] tar
* [x] systemd
* [x] syslinux
* [x] sudosh2
* [x] sops
* [x] selinux-policy-targeted-fedora
* [x] selinux-basics
* [x] runc
* [x] refpolicy
* [x] python3.11
* [x] python3.10
* [x] python3-defaults
* [x] perl
* [x] pam
* [x] ostree
* [x] oras
* [x] openssl
* [x] openssh
* [x] onmetal-image
* [x] microsoft-authentication-library-for-python
* [ ] metalbond
* [ ] linux kernel (6.1, 5.15, 5.10)
* [ ] tdx
* [x] libyang
* [x] libstoragemgmgt
* [x] libpam-ssh
* [x] kpatch
* [x] iproute2
* [x] ignition
* [x] golang-1.20
* [x] glibc
* [x] gardenlinux-selinux-module
* [x] gardenlinux-repo-manager
* [x] frr
* [x] ferm
* [x] ena dkms
* [x] docker.io
* [x] docker-machine
* [x] cyrus-sasl2
* [x] curl
* [x] containerd
* [x] cloud-init
* [x] aws-sdk-cpp
* [x] aws-kms-pkcs11

**Why is this needed**:
In order to streamline the whole Garden Linux build, we want to migrate all pipelines to Github Actions to streamline the whole building process end to end.

**Comment by alee-ntap** [comment]
I create https://github.com/gardenlinux/package-build/issues/38 to track the migration status.

**Comment by nanory** [comment]
All package repos that should be migrated, are migrated now. 

Some package repos shouldn't be migrated as stated in https://github.com/gardenlinux/package-build/issues/27
Others are already migrated but we still work on the build itself that might. Those packages are tracked in https://github.com/gardenlinux/package-build/issues/38

As a result, since the actual repos itself have been migrated, I'm closing this specific issue. The mentioned issues above will track the further progress.
