### ISSUE TITLE
`Feature`: `pkg2deps` should run in a recursion

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1793]
## General
While [pkg2deps](https://github.com/gardenlinux/gardenlinux/blob/main/bin/pkg2deps) makes it a lot easier to obtain missing or wrong dependencies this should also include the deps of deps of deps [...] of packages. The recursion should end if no further dependencies are left.

This feature request came up by @Vincinator after some tests.

## Task
* Adjust pkg2deps to run in a recursion

**Comment by Vincinator** [comment]
this has a very low priority
