### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by berendt** [gardenlinux/gardenlinux#1797]
Currently there is a tag 934.11, but no release 934.11 yet. I am currently not sure if the tag 934.11 is already usable or if your process is that you set the tag before the release is done and only when a release is created on Github the release is usable. As is currently the case for 934.10.

I think it would be good if the release process was documented somewhere.

**Comment by Vincinator** [comment]
#1376

**Comment by Vincinator** [comment]
#1755

**Comment by Vincinator** [comment]
Please re-open if you think these issues are not what you are looking for.

934.11 release tag exists before a GitHub release exists. we wait with creating a release page until it is deployed in gardener, which takes a few days and requires a release decision

**Comment by berendt** [comment]
Thanks for the fast reply.

**Comment by Vincinator** [comment]
Sure. I discussed with colleagues, and we do not need to wait for gardener. 

I will create the 934.11 release page today
