### ISSUE TITLE
`syslog.service` is missing and could lead to errors when restarting `syslog.socket`

### ISSUE THREAD

**Issue by plkokanov** [gardenlinux/gardenlinux#1864]
**What happened:**
- The `syslog.service` seems to be missing from `gardnelinux` version `934.11`. In general the service is required for proper function of syslog - it should be a symlink to the current syslog daemon - `rsyslog.service`. When `syslog.socket` is restarted it tries too start `syslog.service` and with that it actually manages `rsyslog.service`: https://www.freedesktop.org/wiki/Software/systemd/syslog/
- Currently when I try to restart `syslog.socket` I get the following error:
    ```
    Dec 08 16:25:23 ip-10-254-80-28.eu-west-1.compute.internal systemd[1]: syslog.socket: Socket service syslog.service not 
    loaded, refusing.
    Dec 08 16:25:23 ip-10-254-80-28.eu-west-1.compute.internal systemd[1]: Failed to listen on Syslog Socket.
    Dec 08 16:26:01 ip-10-254-80-28.eu-west-1.compute.internal systemd[1]: syslog.socket: Socket service syslog.service not 
    loaded, refusing.
    Dec 08 16:26:01 ip-10-254-80-28.eu-west-1.compute.internal systemd[1]: Failed to listen on Syslog Socket.
    ```
- On ubuntu, for instance, the `syslog.service` is created under `/etc/systemd/system/syslog.service` when `rsyslog.service` is installed via apt.

**How to reproduce it**:
- Create a machine with `gardnelinux` version `934.11`
- Execute `systemctl restart syslog.socket` 
 
**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | e.g.: *main* |
| Container runtime (version)  | e.g.: *podman (3.4.7)* | 
| Host OS of build machine  | e.g: *macOS* | 

- *Please feel free to add additional details*

**Anything else we need to know**:
- *e.g. last time it worked without the bug?* 
- *e.g. link to your garden linux fork*
- *e.g. tested on other build environments*

**Comment by 5kt** [comment]
_syslog.service_ doesn't exist because _rsyslog_ is not enabled by default. It is also not properly configured, it is just installed on the system and disabled.
If you check, _rsyslog.service_ has _syslog.service_ as alias and the proper symlinks under _/etc/systemd/system_ will get created once the _rsyslog.service_ is enabled (similar to your ubuntu example)

IMHO in your case, you should properly configure rsyslog, enable it, start it and then your issue should be resolved.

**Comment by plkokanov** [comment]
You're right, I was only trying to `start` the service without enabling it first which ends up not creating the symlink. 

I didn't encounter this error on ubuntu and suse since the rsyslog.service there was enabled by default and I didn't see that it is disabled on gardenlinux. 

Thanks for the answer.
