### ISSUE TITLE
Update workflows to artifacts v4

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#1875]
See https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

It looks like the upgrade to v4 of the upload/download artifacts is not 100% compatible, so we have to make an effort to upgrade it.

This issue should be open until we addressed this in the whole gh org.

**Comment by Vincinator** [comment]
done for gardenlinux/gardenlinux
