### ISSUE TITLE
Consider full migration to nftables

### ISSUE THREAD

**Issue by mvladev** [gardenlinux/gardenlinux#193]
**What would you like to be added**:

Today nftables [module is disabled](https://github.com/gardenlinux/gardenlinux/blob/4a019feea0321a40c9cec0bd60457ce3e24daca8/features/gardener/exec.config#L3-L8) due to previous limitation in `kube-proxy`, `nodelocaldns` and other K8S components. 

Lots of those components have already received support for nftables, but some workloads might require it (e.g. istio should use CNI instead of proxy-init).

- [x] calico [supports it](https://docs.projectcalico.org/reference/felix/configuration)
- [x] kube-proxy[ since 1.17](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#network-1)
- [x] istio supports it via CNI
- [x] nodelocaldns [supports it](https://github.com/kubernetes/dns/pull/367)
- [ ] https://github.com/gardener/apiserver-proxy needs support
- [ ] https://github.com/gardener/vpn needs support
- [ ] More components....

A problem might from the fact than you can have both firewalls up and running in the same time (e.g. some component loads iptables legacy modules and nftable is there). At some point it might be better to even black-list the legacy iptable modules.

**Why is this needed**:

Migration to `nf_tables` and switching the iptables to use it would have:

- better scalability
- better performance
- lower kernel module count than iptables

**Comment by marwinski** [comment]
I'd suggest to move this ticket to the Gardener organisation. I would also take the opportunity to propose a change in Garden Linux: we currently configure legacy iptables in Garden Linux (in features/gardener/exec.config):

```
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set arptables /usr/sbin/arptables-legacy
update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

We should not really do this but leave it to the operating system extension to decide what would be appropriate.

This said, I fully support the move to nftables.
