### ISSUE TITLE
Take ownership of kernel configuration - remove implicit dependencies to debian across kernel versions 

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#1981]
**Context**
The current kernel build for Garden Linux uses debian kernel config as starting point, and adapts this with own Garden Linux specific configurations (using the debian kernel config tooling).

**What would you like to be added**:

- [ ] Linux package owns kernel configuration, no implicit dependency from a debian git repo
    * kernel config will be maintained at `gardenlinux/package-linux` repo(s)
- [ ] Kernel config Tests in gardenlinux/gardenlinux
    * GL features that install a kernel, can add tests to check for important kernel configuration (firecracker, metal, cloud) 
    * These tests should be moved to this repository, testing the actual kernel installed in the Garden Linux image - removing potential de-sync error sources 
 - [ ] Add automation to detect kernel config changes in debian 
     * our kernel config is based on the debian kernel config.
     * we need to be notified about changed configs 

**Why is this needed**:
To simplify and to eliminate potential error sources, we want to own and maintain all parts of the kernel config, so that if debian changes a kernel config, we would need to actively pull those changes.

**Comment by fwilhe** [comment]
Just an idea for an extension: Maybe it would be useful/nice to have an automated script for finding new options set in new versions of the debian kernel (if they diverge from the kernel's default config)? Might help us find settings that we might want to pull.

Definitely not urgent.

**Comment by Vincinator** [comment]
+1 Added it to the issue
