### ISSUE TITLE
Delete 'garden-feat' tests if they are obsolete

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#1996]
If my understanding is correct, the 'garden-feat' tests can't work anymore as the script was removed [here](https://github.com/gardenlinux/gardenlinux/commit/ef0e0e6c0383494f9d72670a1e8585e709c808e2). Not sure what qualities the tests ensured but I don't think they work with the current code base. I think the old 'garden-feat' is now (partially) the parse features script in the builder, maybe that should have those tests?

https://github.com/gardenlinux/gardenlinux/blob/34bb8c96fcda3c53a5573e320ab5534141915c6e/tests/local/test_garden_feat.py#L1

**Comment by Vincinator** [comment]
garden-feat does not exist anymore in favour of the [parse_features](https://github.com/gardenlinux/builder/blob/main/builder/parse_features) from the new builder.

If I understand the [gardenlinux/tests/local/test_garden_feat.py](https://github.com/gardenlinux/gardenlinux/blob/34bb8c96fcda3c53a5573e320ab5534141915c6e/tests/local/test_garden_feat.py#L1) test correctly, it tested if the garden_feat script reduced the cname correctly. 

My conclusion: Testing `parse_feature` should be done in the gardenlinux/builder.
