### ISSUE TITLE
Provide a Garden Linux 1312 release with a disabled GDM module

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#2085]
**What would you like to be added**:

Please provide a 1312.x (x probably equals 4) release with the GSM module disabled similar to the upcoming 1443.4 release.

**Why is this needed**:

The vast majority of our users is still running Garden Linux 1312.x. Most of them haven't validated 1443.x yet.

**Comment by Vincinator** [comment]
[1312.5](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.5) disabled GSM module
