### ISSUE TITLE
Enable ARM64 support

### ISSUE THREAD

**Issue by ghost** [gardenlinux/gardenlinux#210]
We should enable Garden Linux on ARM64. This would enable us to go forward with enabling additional open source projects and ARM use cases.

Initial work started with @gehoern in https://github.com/gardenlinux/gardenlinux/tree/arm64

**Comment by PavelPavlov46** [comment]
@gehoern the work from the session we did is in https://github.com/gardenlinux/gardenlinux/commit/aa8ab0a02af3ad714cb4f3581c6dd428f4fc7a8d .

Next to-do we found:
1. Fix kernel build failing with "arm-linux-gnueabihf-gcc: not found" . The manual change i tried seems to work. We need to make it permanent with the rest of the changes to linux build
```
$ which arm-linux-gnueabihf-gcc
$ sudo apt install gcc-arm-linux-gnueabihf
$ which arm-linux-gnueabihf-gcc
/usr/bin/arm-linux-gnueabihf-gcc
$ manual/linux
```
2.  Fix 
```
make[2]: Entering directory '/home/dev/linux'
dh_testdir
dh_prep
kernel-wedge install-files 5.4.0-6
	install -D -m 644 debian/linux-image-5.4.0-6-arm64-unsigned/boot/vmlinuz-5.4.0-6-arm64 debian/kernel-image-5.4.0-6-arm64-di/boot/vmlinuz
	install -d debian/kernel-image-5.4.0-6-arm64-di/lib/modules/5.4.0-6-arm64
	install -m 644 debian/linux-image-5.4.0-6-arm64-unsigned/lib/modules/5.4.0-6-arm64/modules.builtin debian/linux-image-5.4.0-6-arm64-unsigned/lib/modules/5.4.0-6-arm64/modules.order debian/kernel-image-5.4.0-6-arm64-di/lib/modules/5.4.0-6-arm64/
	install -D -m 644 debian/linux-image-5.4.0-6-arm64-unsigned/boot/System.map-5.4.0-6-arm64 debian/kernel-image-5.4.0-6-arm64-di/boot/System.map
	install -d debian/kernel-image-5.4.0-6-arm64-di/usr/lib
	cp -a debian/linux-image-5.4.0-6-arm64-unsigned/usr/lib/linux-image-5.4.0-6-arm64 debian/kernel-image-5.4.0-6-arm64-di/usr/lib/linux-image-5.4.0-6-arm64
	kernel-wedge copy-modules 5.4.0-6 arm64 5.4.0-6-arm64
missing module analogix-anx6345
command exited with status 1
make[2]: *** [debian/rules.real:571: install-udeb_arm64] Error 2
make[2]: Leaving directory '/home/dev/linux'
make[1]: *** [debian/rules.gen:42: binary-arch_arm64] Error 2
make[1]: Leaving directory '/home/dev/linux'
make: *** [debian/rules:43: binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```
Not sure why we nee that package, but seems to be in linux-image-5.10.0-3-arm64:/lib/modules/5.10.0-3-arm64/kernel/drivers/gpu/drm/bridge/analogix/analogix-anx6345.ko (https://packages.debian.org/search?searchon=contents&keywords=analogix-anx6345&mode=filename&suite=testing&arch=any)

3. The outdated cfssl where we faced issue similar to 
https://stackoverflow.com/questions/57645888/this-certificate-lacks-a-hosts-field-this-makes-it-unsuitable-for-websites

**Comment by litalec** [comment]
arm-linux-gnueabihf-gcc is 32b ARM, not 64b

**Comment by gyptazy** [comment]
Hey,

I think this issue is deprecated by https://github.com/gardenlinux/gardenlinux/issues/1028 (meta ticket) where I created sub tasks for all ARM64 related topics. It covers the build pipeline, cross building, build support on different Linux distributions and macOS (Intel + Apple Silicon (ARM64)), feature compatibility and supported hyperscalers.

I think we may close this issue. If something is missing, this should probably be added within the meta issue.

cc: @gehoern @nanory
