### ISSUE TITLE
Enable Btrfs filesystem support

### ISSUE THREAD

**Issue by ArkadiuszSzczyrba** [gardenlinux/gardenlinux#211]
**What would you like to be added**:
Support for Btrfs file system
https://btrfs.wiki.kernel.org/index.php/Changelog#btrfs-progs_v5.4_.28Dec_2019.29

**Why is this needed**:
Our team provision and maintain [Concourse CI](https://concourse-ci.org/) on Gardener cluster. Btrfs is one of the filesystems [supported by Concourse Helm chart](https://github.com/concourse/concourse-chart/blob/master/values.yaml#L1712) therefore we would like to have the possibility to use Btrfs driver in our deployment.

**Comment by gehoern** [comment]
in next release in
