### ISSUE TITLE
Cloud-init failed on AliCloud for version v318

### ISSUE THREAD

**Issue by jia-jerry** [gardenlinux/gardenlinux#214]
**What happened**:
User(admin) can't log on VM backed by v318 on AliCloud.
**What you expected to happen**:
User can log on VM successfully.
**How to reproduce it (as minimally and precisely as possible)**:
Create a VM with customized Garden Linux image and admin user will fail to log on.
**Anything else we need to know**:
Root cause: cloud-init regression.
Here is the ticket for Cloud-init: https://bugs.launchpad.net/cloud-init/+bug/1917875
**Environment**:

**Comment by marwinski** [comment]
This issue has been resolved by going back to an older cloud-init version. In the meantime the cloud-init bug has been fixed.
