### ISSUE TITLE
APT Repo with Snapshots V2.0

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2158]
# Epic: APT Repo with Snapshots V2.0

## Tasks

**Comment by Vincinator** [comment]
### Implementation

https://github.com/gardenlinux/repo

##  Motivation 
apt repository was previously managed by a long running VM with a persistent disk. This disk contained the apt repository state. The tool [aptly](https://www.aptly.info) was used to create new distributions, add new packages (mirror, self build), and to publish the apt repo to an AWS s3 target. This design has some flaws such as a long running VM that is a "crown jewel" or in other terms, is a single point of failure. Another issue was that the old repo only mirrored packages explicitly, if we needed a build dependency for a patch release that we did not mirror before, then we would need to hope that https://archive.debian.org had a snapshot for us.  

## Design Principles

- No dependency on infrastructure maintenance => everything can be built with ephemeral workers, such as the public/free GitHub runners. 
- Reproducibility => If we loose the produced apt repository, we can rebuild everything based on source code 
- Consistency  => Inconsistent states must be avoided. If a distribution of the apt repo is created, it can not be changed after wards. This reduces the risk of introducing inconsistencies between repo states with the same name
