### ISSUE TITLE
Dracut fails DNS resolution on ipxe based install 

### ISSUE THREAD

**Issue by RiRa12621** [gardenlinux/gardenlinux#2204]
**What happened:**
Dracut is unable to pull the squashfs

**Debug Logs:**
```
[46596.439433] dracut Warning: can't fetch the squashfs from https://storage.googleapis.com/gardener-ipxe/root.squashfs
```

**How to reproduce it**:
* Start equinix on demand instance
* use custom ipxe
* set to ipxe script https://gist.githubusercontent.com/RiRa12621/ead924974c5ded1387531a8421876166/raw/80be1ecf801b09c7626d38160a7a52b406d71a27/ipxe-scrip.ipxe
* boot instance
* connect OOB
 
**Environment:**
 Equinix on demand c3.small.x86

**Anything else we need to know**:
The fact that we are able to get until this points, means that the ipxe script is loaded, which in turn means, that DNS by that time actually works.

Files in the GCP bucket are taken from [the releases ](https://github.com/gardenlinux/gardenlinux/releases/download/1443.9/metal-gardener_prod_pxe-amd64-1443.9-a9c614dc.tar.xz) and just uploaded there. Access is public.

**Comment by RiRa12621** [comment]
if you check, we also have a n ipxe script in the bucket and that's what we originally used, but gcp is caching anonymous pulls for a long time, hence we moved it temporarily to a gist, so we can experiment a little better

**Comment by RiRa12621** [comment]
presumably the error is coming from

```
if ! curl --globoff --location --retry 3 --fail --show-error "${url}" --output "${squashFile}"; then
       warn "can't fetch the squashfs from ${url#gl.url=}"
       exit 1
fi
```

in `features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.sh`

**Comment by RiRa12621** [comment]
when the run fails, we fall back to shell.
If in the shell, we manually add a nameserver like so `echo "nameserver 8.8.8.8" > /etc/resolv.conf` and resume the process via exiting the shell, the process continues.

Therefore, the assumption is that for some reason, the `nameserver` parameters aren't accepted

**Comment by nkraetzschmar** [comment]
looks like it is related to missing `systemd-resolved` and ca-certificates in the initrd

#2205 should fix it

**Comment by RiRa12621** [comment]
just built from master and seems to work fine.
