### ISSUE TITLE
Create 15xx patch 0 (initial release)

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2213]
### Package versions
- Latest Kernel 6.6 (v6.6.41)
- Latest systemd (v256) including new handling of NICs.
- Latest golang 1.22.5
- Latest containerd 1.7 possible (test with [containerd 1.7.20](https://github.com/containerd/containerd/releases/tag/v1.7.20). If problematic fall back to [containerd 1.6.34](https://github.com/containerd/containerd/releases/tag/v1.6.34) or as last backup [1.6.24](https://github.com/containerd/containerd/releases/tag/v1.6.24))

### Configuration
- Secureboot enabled on AWS
- NVMe enabled on Azure

## Fixes
- https://github.com/gardenlinux/gardenlinux/issues/2204
- https://github.com/gardenlinux/glci/issues/49
- https://github.com/gardenlinux/glci/issues/58

## Tasks
  - https://github.com/gardenlinux/glci/pull/91/files (@MrBatschner is working in it)
  - https://github.com/gardenlinux/gardenlinux/issues/2166
  - https://github.com/gardenlinux/gardenlinux/issues/2214
  - https://github.com/gardenlinux/gardenlinux/issues/2206
  - https://github.com/gardenlinux/gardenlinux/issues/2207
  - https://github.com/gardenlinux/security/issues/26
  - https://github.com/gardenlinux/gardenlinux/issues/2221
  - https://github.com/gardenlinux/gardenlinux/issues/2219
  - https://github.com/gardenlinux/process/issues/96
  - https://github.com/gardenlinux/gardenlinux/issues/2208
  - https://github.com/gardenlinux/gardenlinux/issues/2209
  - https://github.com/gardenlinux/gardenlinux/issues/2210
  - https://github.com/gardenlinux/gardenlinux/issues/2211
  - https://github.com/gardenlinux/gardenlinux/issues/2212

**Comment by fwilhe** [comment]
Goal: release version 1589 tomorrow

version checks:

- bump kernel to 6.6.44 https://github.com/gardenlinux/package-linux/pull/23
- [containerd 1.7.20](https://github.com/gardenlinux/package-containerd/commit/f48dea642adc8fdd9234b6572f4b67fffa225057) is the [most recent version as of now](https://github.com/containerd/containerd/releases)

**Comment by fwilhe** [comment]
Release is out now https://github.com/gardenlinux/gardenlinux/releases/tag/1592.0
