### ISSUE TITLE
Update kernel package-linux to v6.6.40

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2214]
Update Garden Linux builds to use latest released 6.6 kernel (6.6.40)

**Required by:** 
- https://github.com/gardenlinux/gardenlinux/issues/2213

**Comment by fwilhe** [comment]
Done in https://github.com/gardenlinux/package-linux/commit/777036f215f401a69525a31fd61840984143d1ce

In collaboration with @nkraetzschmar and @Vincinator 💯
