### ISSUE TITLE
Set nvme flag

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2219]
Fix
- https://github.com/gardenlinux/glci/issues/58
- https://github.com/gardenlinux/glci/issues/49

**Comment by MrBatschner** [comment]
See https://github.com/gardenlinux/glci/issues/58

**Comment by MrBatschner** [comment]
We might need to include https://github.com/azure/azure-nvme-utils for Azure images to prevent problems with CSI on NVMe machines.

**Comment by pnpavlov** [comment]
Azure done, Alicloud in Sept
