### ISSUE TITLE
Adopt SELinux in Garden Linux

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardenlinux/gardenlinux#222]
WHAT: Debian offers SELinux `enforcing=1` see [Debian Doku](https://wiki.debian.org/SELinux/Setup#Steps_to_setup_SELinux). Garden Linux currently provides SELinux only in its on metal flavor. Garden Linux should provide SELinux as well in all other flavors and should be regularly tested in Gardener context with this hardening option. Potential issues should be addressed either in Gardener or Garden Linux project.

WHY: [DISA STIG assessment](https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-12-14/finding/V-71989) requires to have VMs started with SELinux `enforcing=1`.

**Comment by chrinorse** [comment]
By now it is enabled in the CIS feature, but Debian has some major problems with SElinux enabled. See https://github.com/gardenlinux/gardenlinux/issues/1011
