### ISSUE TITLE
_iso image not working

### ISSUE THREAD

**Issue by dnan0s** [gardenlinux/gardenlinux#2224]
**What happened:**

Build of `_iso` image not possible. It's missing isolinux package. I expect isolinux to be needed for the feature, so i expect some issues with naming or availability in the gardenlinux sources.

- *Brief description of Bug*

**Debug Logs:**
#### 
build of metal_iso_dev on 1443.9 branch (same output for main branch)
$ ./build metal_iso_dev
```
STEP 1/1: FROM ghcr.io/gardenlinux/builder:3ab2bb52bc46bb200c761369c087e9413d1ce0ac
COMMIT localhost/builder
--> 1eba10d0345c
Successfully tagged localhost/builder:latest
Successfully tagged ghcr.io/gardenlinux/builder:3ab2bb52bc46bb200c761369c087e9413d1ce0ac
1eba10d0345cc6df78b7c3a6ced45da9db675d05eb20d5d286996e4f7ffb24d5
configuring rootfs metal_dev_iso-amd64-1443.9-local
[.build/metal_dev_iso-amd64-1443.9-local.tar 2024-07-19 09:13:32] exec: /builder/features/server/exec.early
[.build/metal_dev_iso-amd64-1443.9-local.tar 2024-07-19 09:13:32] Reading package lists...
[.build/metal_dev_iso-amd64-1443.9-local.tar 2024-07-19 09:13:32] Building dependency tree...
[.build/metal_dev_iso-amd64-1443.9-local.tar 2024-07-19 09:13:32] E: Unable to locate package isolinux
completed in 1 seconds

make: *** [Makefile:55: .build/metal_dev_iso-amd64-1443.9-local.tar] Error 100
```

#### on another machine with gardenlinux today, isolinux is available in gardenlinux repo
apt-cache madison isolinux 
```

  isolinux | 3:6.04~git20190206.bf6db5b4+dfsg1-3 | https://repo.gardenlinux.io/gardenlinux today/main amd64 Packages
  isolinux | 3:6.04~git20190206.bf6db5b4+dfsg1-3 | https://repo.gardenlinux.io/gardenlinux today/main all Packages
```

**How to reproduce it**:
`./build metal_dev_iso`
 
**Environment:**

i think not that important :) 

#### PS
A fix is not that important to me/us, i just updated our pipelines and found the issue because of that. But of course a working feature is always better :)  Happy to help if i can...

**Comment by 5kt** [comment]
Fixed via https://github.com/gardenlinux/repo/pull/17
