### ISSUE TITLE
Monitoring for failed package builds

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2245]
**What would you like to be added**:
Some kind of monitoring for [package builds](https://github.com/gardenlinux?q=package-&type=all&language=&sort=), so we know when a build fails.

It would be nice to integrate this into the [daily dashboard](https://github.com/gardenlinux/daily) ([web link](https://gardenlinux.github.io/daily/)) so that we know about failed builds. This should give us a list of failed package builds so we can react quickly.

The information could be collected in some github actions cron job.
It might also be possible to do it in browser javascript, but note that the github api has very strict rate limiting for requests without authentication, so this is probably not something that would scale well if we need to query many repos.

**Why is this needed**:
Recently, we had failed package builds in [systemd](https://github.com/gardenlinux/package-systemd/actions) that got unnoticed for about two weeks. This should not happen. We want to be able to address build issues as early as possible so we're always able to create a new release if needed.

**Comment by mxmxchere** [comment]
I have written an aggregator [here](https://github.com/mxmxchere/daily). If we can live with that I propose that we create a separate repo for that tool where a github-action cronjob can scrape all the data and push it to the [daily repo](https://github.com/gardenlinux/daily). We could also put the aggregation tool in the daily repo itself but then the program code will be hosted by github-pages too.

**Comment by fwilhe** [comment]
Thanks @mxmxchere, I think that's very useful. I'm sure we'll teak it over time (exclude repos, maybe tweaking the UI, ..), but that does not need an issue to track, imo. Closing this repo as resolved.
