### ISSUE TITLE
Enhance and stabilize the integration/platform test container for Garden Linux

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#2260]
**Problem(s):** Container used for building Garden Linux is based on Debian. Packages are installed in mixed way with apt and pip package managers. 

**Deliverable(s):** 
- The container image runs reliable and does not depend on multiple package sources (debian stable and testing) and multiple package managers (apt, pip) as much as possible. 
- The container contains the absolute minimum required set of packages that are really required. If it makes sense, break down the build container in multiple containers that are not mixed up.

**Proposal(s):** 
The tests run as part of every nightly job and depend on the presence of the build-container. This container mainly provides SDKs, CLI-utils and python libs for every cloud provider (AWS, Azure, GCP, AliCloud and OpenStack) in one place. This could be improved in many ways:
   - Instead of having one container as a swiss-army knife that is rather huge, maybe we can provide individual small containers containing only the bare minimum required to perform tests on the selected platform - this is useful if the tests should be run locally
   - For the tests running as part of the `nightly` pipeline, that container is an unnecessary layer. Instead, why not install the required libraries, CLI tools and SDKs directly on the runner (in the workflow step, e.g. [here](https://github.com/gardenlinux/gardenlinux/blob/main/.github/workflows/aws_tests.sh)) and launch the tests from there? This would remove the requirement for lines like [these](https://github.com/gardenlinux/gardenlinux/blob/481d532c0a131f4cbaf04bd2c60eec976c881f06/.github/workflows/aws_tests.sh#L67)...

**Comment by fwilhe** [comment]
Another issue is [this mix between debian and garden linux in the container](https://github.com/gardenlinux/gardenlinux/blob/481d532c0a131f4cbaf04bd2c60eec976c881f06/container/base-test/Dockerfile#L22)

Since in debian testing packages can disappear any day the setup is not super stable and reliable

I think having tests containerized does have advantages, both for running locally and in ci, but I also agree with @MrBatschner that getting rid of the container in ci might make things simpler. We need to take care to ensure both the local (container) and the ci (github actions vm) setup does not deviate too much.

**Comment by fwilhe** [comment]
More thoughts:

It would be nice if we had better documentation about the _types_ of tests we have, what pre-requisites they have (to run) and what qualities they ensure.

I had trouble running tests locally in the past, there is documentation but it did not work for me. Simplifying and streamlining both the test implementation and the docs would be nice.

**Comment by pnpavlov** [comment]
@gardenlinux/b1-systems , as proposed by @MrBatschner & @fwilhe , could we tackle that as part of our DevOps / GH Actions / Pipeline efforts in September? Adding to [2024-09](https://github.com/gardenlinux/gardenlinux/milestone/52) , so we can discuss it when everyone is back. Meeting invite to discuss it is sent for 27th Aug.

**Comment by yeoldegrove** [comment]
- :dog: :canned_food: garden linux to use as a base for platform tests containers is another interesting take
  - one could use the latest stable github release as a source of truth

**Comment by yeoldegrove** [comment]
@fwilhe 
> I think having tests containerized does have advantages, both for running locally and in ci, but I also agree with @MrBatschner that getting rid of the container in ci might make things simpler. We need to take care to ensure both the local (container) and the ci (github actions vm) setup does not deviate too much.

I agree with the point that running it the same way locally than int he CI has it's charm.
Maybe eliminating the frequent (re-)build of the test containers by building them outside our main workflows/pipelines would be a first quick win. Every workflow/pipeline could just consume an already existing container image that is build in a different workflow.

**Comment by yeoldegrove** [comment]
I spitted the platform test images up (based on the platform) to get an idea which components are a factor in regards to the image size.

### images from current `main` branch

| Name                          | Version  | Size   |
|-------------------------------|-------|--------|
| gardenlinux/base-test          | today | 2.02 GB|
| gardenlinux/platform-test      | today | 5.46 GB|


### images from current `platform-test-images` branch

| Name                                              | Version | Size    |
|---------------------------------------------------|---------|---------|
| gardenlinux/base-test                   | 1592.1  | 920 MB  |
| gardenlinux/platform-test-azure         | 1592.1  | 2.09 GB |
| gardenlinux/platform-test-gcp           | 1592.1  | 1.75 GB |
| gardenlinux/platform-test-kvm           | 1592.1  | 1.64 GB |
| gardenlinux/platform-test-openstack     | 1592.1  | 963 MB  |
| gardenlinux/platform-test-ali           | 1592.1  | 970 MB  |
| gardenlinux/platform-test-aws           | 1592.1  | 1.14 GB |
| gardenlinux/platform-test-firecracker   | 1592.1  | 927 MB  |

Further work to build/test these images will be done next week.

**Comment by pnpavlov** [comment]
> Another issue is [this mix between debian and garden linux in the container](https://github.com/gardenlinux/gardenlinux/blob/481d532c0a131f4cbaf04bd2c60eec976c881f06/container/base-test/Dockerfile#L22)

@yeoldegrove , can you please evaluate the options to address this one please and get OK with @fwilhe  & @gehoern . thanks!

**Comment by yeoldegrove** [comment]
#2339 includes a sum up of the changes that address the issue
