### ISSUE TITLE
Unify image ignore list for building and publishing Garden Linux images

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2265]
**What would you like to be added**:
We have an [exclude list for image variants here](https://github.com/gardenlinux/gardenlinux/blob/28621384d0157a5eb5024a5d01199893b7197b78/.github/workflows/build.yml#L162) but we don't take this into account [here](https://github.com/gardenlinux/gardenlinux/blob/28621384d0157a5eb5024a5d01199893b7197b78/.github/workflows/release-page.yml#L49).

We could now just copy that ignore list there, but this would then need maintenance in two places if anything changes. It would be nice to only maintain this ignore list in a single place.

**Why is this needed**:
Currently we have failed jobs in the 'release publish' job for 1592. This is not bad but it looks bad and is confusing. We should only attempt to publish the images we really build, but avoid hard to maintain double exclude lists.

**Comment by berendt** [comment]
@fwilhe Is it planned to publish OpenStack ARM64 in the future? We are currently in the progress of enabling ARM64 on our OpenStack cluster and would like to use shoots there as well in the future.

**Comment by fwilhe** [comment]
Hi @berendt 

thanks for letting us know that this is interesting for you. I can't make any promises, but we'll look into why we disabled this at the time.
