### ISSUE TITLE
Clean up old repositories

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2281]
package-glibc | 2024-08-16T03:06:29.673921196Z
-- | --
package-kpatch | 2024-08-16T03:06:25.375142707Z
package-ena-dkms | 2024-08-16T03:06:08.137078608Z
package-docker.io | 2024-08-16T03:06:08.014499846Z
package-xz | 2024-08-16T03:06:07.255979284Z

[package-glibc](https://github.com/gardenlinux/package-glibc/actions/workflows/build.yml)	2024-08-16T03:06:29.673921196Z
[package-kpatch](https://github.com/gardenlinux/package-kpatch/actions/workflows/build.yml)	2024-08-16T03:06:25.375142707Z
[package-ena-dkms](https://github.com/gardenlinux/package-ena-dkms/actions/workflows/build.yml)	2024-08-16T03:06:08.137078608Z
[package-docker.io](https://github.com/gardenlinux/package-docker.io/actions/workflows/build.yml)	2024-08-16T03:06:08.014499846Z
[package-xz](https://github.com/gardenlinux/package-xz/actions/workflows/build.yml)	2024-08-16T03:06:07.255979284Z

**Comment by Vincinator** [comment]
Done
