### ISSUE TITLE
Integrate TPM2 for encryption of writable persistent partitions (stage2 trustedboot)

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2285]
Incorporate the work of @brdanin (https://github.com/gardenlinux/builder/pull/62 and https://github.com/gardenlinux/builder/pull/69) into https://github.com/gardenlinux/gardenlinux/pull/2259

**Comment by nkraetzschmar** [comment]
#2259

**Comment by pnpavlov** [comment]
@nkraetzschmar , could you please review next week latest?

**Comment by nkraetzschmar** [comment]
- https://github.com/gardenlinux/gardenlinux/issues/2341
