### ISSUE TITLE
Improve CI resilience

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2288]
**What would you like to be added**:
Our CI is prone to failure with cases that are not because of any issue with our code, but with GitHub's infrastructure. See example jobs and their logs below.

We should investigate ways to make our CI more resilient, i.e. have sensible retry-logic.
I know we already have some retry logic, but maybe it can be improved to reduce the number of failed nightly builds cause by infrastructure.

**Why is this needed**:
Failed CI builds eat up our attention and divert us from the goal of being able to release every day.

Example jobs that failed:

https://github.com/gardenlinux/gardenlinux/actions/runs/10448014048/job/28929241273

```
container-arm64-1602.0-989abf9c.release.log
container-arm64-1602.0-989abf9c.manifest
container-arm64-1602.0-989abf9c.manifest.log
container-arm64-1602.0-989abf9c.oci
container-arm64-1602.0-989abf9c.oci.log
container-arm64-1602.0-989abf9c.test-log
Getting image source signatures
Copying blob sha256:327421e77d4bd64d81de125ae25c838ca8cf8c427080ecad68b93d3e67d3f711
Copying config sha256:81f3543304b765f928321902bcfdf50211a90d5a411393690c134a0205a336ef
Writing manifest to image destination
Storing signatures
Getting image source signatures
Copying blob sha256:eb7b8f29f7f27a2c73514f82cdf9b44592ff38c82f0be3d004fa2d87116d4573
Error: writing blob: uploading layer to https://ghcr.io/v2/gardenlinux/gardenlinux/blobs/upload/edf09064-437b-4826-86a8-474242870a1e?digest=sha256%3A601a28d37a1c16abe5bb8bfac82b28ccdf3a6da18bf66c2e84b7e79ed397c469: received unexpected HTTP status: 500 Internal Server Error
Error: Process completed with exit code 125.
```

https://github.com/gardenlinux/repo/actions/runs/10436349813/job/28901306888

```
+ arch=amd64
+ mkdir download
+ read -r repo tag
+ gh release download --dir download --repo gardenlinux/package-iproute2 6.10.0-1gardenlinux0
+ '[' -e download/null ']'
+ read -r repo tag
+ gh release download --dir download --repo gardenlinux/package-frr 10.0.1-0.1gardenlinux0
+ '[' -e download/null ']'
+ read -r repo tag
+ gh release download --dir download --repo gardenlinux/package-systemd 256.4-3gardenlinux0
HTTP 502: 502 Bad Gateway (https://objects.githubusercontent.com/github-production-release-asset-2e65be/750284125/8e8f7b8c-e925-48e5-93b5-6d221ac4a2e5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240818T003218Z&X-Amz-Expires=300&X-Amz-Signature=fb5bb9400b78e623cb46522941f7b3019a10cd454f11325cb725f9333ce16ed4&X-Amz-SignedHeaders=host&actor_id=41898282&key_id=0&repo_id=750284125&response-content-disposition=attachment%3B%20filename%3Dsystemd-cryptsetup_256.4-3gardenlinux0_arm64.deb&response-content-type=application%2Foctet-stream)
+ cd /
+ rm -rf /tmp/tmp.m3KjIEUF4U
Error: Process completed with exit code 1.
```

**Comment by Vincinator** [comment]
Just a thought on a implementation details: 
I think it would make sense to write a wrapper for `gh release download` cmd, so we can retry just a single failed download. 

Maybe something similar for the container upload.

**Comment by fwilhe** [comment]
Yes. Maybe we also need some kind of exponential backoff logic. If the server responds with some internal server error now, retrying 2 seconds later might not be enough, but giving it a few minutes rather.. At some point of course we'll hit timeout limits in actions, but I think we should investigate what's sensible there.

**Comment by Vincinator** [comment]
> Also, rate limiting could be an issue I guess. Have we investigated if we're actually hitting rate limits and just don't know because the error message is not clear?

not yet, good point! This is also a good argument for the need for an exponential backoff logic. 
Have only found reports where the server is returning a `HTTP 403: Forbidden` with the message `API Rate Limit Exceeded`

There is an API to check the rate_limit, which might be useful for debugging or error handling
https://api.github.com/rate_limit

**Comment by fwilhe** [comment]
> There is an API to check the rate_limit

Oh nice I was not aware of that. Yes we should definitely check that api in our pipelines, I think.
