### ISSUE TITLE
Organize the tests and add accurate naming

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2303]
Currently the https://github.com/gardenlinux/gardenlinux/tree/main/tests/ folder contains content that may have misleading naming. Please organize and document it in clear understandable way (e.g. integration folder could be named platform or platform-setup).

**Comment by yeoldegrove** [comment]
#2302 will rename every reference of "integration" to "platform" where applicable.

**Comment by pnpavlov** [comment]
@MrBatschner please review
