### ISSUE TITLE
Kernel version output is truncated for back port versions

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2306]
**What happened:**
- *Brief description of Bug*

Garden Linux 1443.10 ships with kernel `6.6.41-0gardenlinux0+bp1443` which is a longer version number compared to other kernel version we have.

The output of `uname --kernel-version` is truncated in some cases (when `PREEEMPT_DYNAMIC` flag is there) with this kernel because it has a [fixed max length](https://github.com/torvalds/linux/blob/86987d84b968b69a610fd00ab9006c13db193b4e/init/Makefile#L34).
This might cause issues [with tools that read the kernel version and try to parse it](https://github.com/microsoft/azure-pipelines-agent/blob/3d25a3479b5149b2bac8988615ef41616a79515a/tools/FindAgentsNotCompatibleWithAgent/QueryAgentPoolsForCompatibleOS.ps1#L206).

`6.6.41-0gardenlinux0+bp1443` is a special case because our other kernels don't have the `+bp1443` suffix version number.
Still we can't rule out this is needed in the future for multiple builds of the same kernel version for multiple Garden Linux versions.

In this case the 'back port' suffix was added to indicate that the [build container for this version is the container for version 1443](https://github.com/gardenlinux/package-linux/commit/3a70bc428799cf4eecbf8ad0b77c885345a8a19c).

Potential solutions (impact unclear):
- shorten `gardenlinux0` to `gl0`
  - This option has influences on other/all packages as package-linux uses the same tooling.
- Never use the `+bp1443` suffix for the kernel, instead count the integer up in `gardenlinux0`
  - This would be less readable. How do you know the difference between `6.6.41-0gardenlinux0` and `6.6.41-0gardenlinux1`?
  - The latter version is recognised as newer by apt which might cause issues potentially

**Comment by pnpavlov** [comment]
**Proposal:** Implement the proposal shorten gardenlinux0 to gl0.
**Next steps:** 
- @gardenlinux/garden-linux-maintainers are given time until Monday 2nd Sept 18:00 CET to provide better alternative or object.
- To be implemented in [2024-09](https://github.com/gardenlinux/gardenlinux/milestone/52) by @nkraetzschmar.

**Comment by fwilhe** [comment]
Just playing devils advocate:

How certain are we this fixes the problem? I'm not sure if there are other flags that might make UTS_VERSION exceed the 64 char limit.

Renaming `gardenlinux0` to `gl0` will save us 9 chars

Adding `+bp1443` does cost us 7 chars

so we're 2 down, which is good I think.

As we never before run into issues like this (as far as I'm aware) we should be good even with other kernel configs.

**Comment by pnpavlov** [comment]
Fair point @fwilhe... @nkraetzschmar @gehoern , could you please align on Mon on best design to keep us within the 64 char limit without breaking something further.

**Comment by fwilhe** [comment]
From the daily some points by @nkraetzschmar 

- The need for kernel backports is because the kernel build also contains user space tools that require a certain libc version, thus a kernel built with the build container in today might (or might not) work with gl 1443 or gl 1592
- The pure kernel itself would not require backports
- With central change in the package build code, the versions will be consistent in all gl rebuilds
- For manual rebuilds, we need to remember to use the new `gl` suffix instead of the old `gardenlinux` suffix
