### ISSUE TITLE
Fix Nightly 30th Aug

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2309]
- [x] Test FAILED gcp/test/test_users.py::test_users - AssertionError: Unexpected user account found in /etc/passwd: markus_guertler (fmi: [29463018066](https://github.com/gardenlinux/gardenlinux/actions/runs/10627652076/job/29463018066#step:15:544))
  -> @mguertler to remove key from the google cloud project.

- [x] google.api_core.exceptions.ServiceUnavailable: 503 SERVICE UNAVAILABLE ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS: The zone 'projects/***/zones/***' does not have enough resources available to fulfill the request.  '(resource type:compute)'. (fmi: [29463019308](https://github.com/gardenlinux/gardenlinux/actions/runs/10627652076/job/29463019308#step:15:16412)
  -> @MrBatschner defines a zone that is less busy.

**Comment by MrBatschner** [comment]
More permanent fix for first bullet point: PR #2310

**Comment by MrBatschner** [comment]
Nightly completed successfully.

**Comment by pnpavlov** [comment]
I see [nightly](https://github.com/gardenlinux/gardenlinux/actions/runs/10627652076) is good. @MrBatschner , can we close this one?

**Comment by fwilhe** [comment]
Issue 1 (Markus' user) seems resolved, issue 2 (ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS) hit us in today's nightly again. @gehoern @MrBatschner

**Comment by MrBatschner** [comment]
gcp platform tests currently run in `europe-west4-c` which seems out of resources on Google side. Need to change to a different zone by modifying the `GCP_ZONE` secrets at https://github.com/gardenlinux/gardenlinux/settings/secrets/actions to another zone (`a`, `b`) according to https://cloud.google.com/compute/docs/regions-zones. Note: we must not change the region to e.g. europe-west3 as this region does not offer ARM64 machine types.

**Comment by MrBatschner** [comment]
Follow up: https://github.com/gardenlinux/gardenlinux/issues/2315

**Comment by MrBatschner** [comment]
`GCP_ZONE` was set to `europe-west4-a` which seems to have solved the problem with `ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS`. Follow-up #2315 should be done do make reconfiguration of such elements easier in the future (we should not have to guess the current value as we have to when using GitHub secrets for things like `GCP_ZONE`).

**Comment by pnpavlov** [comment]
thank you @MrBatschner
