### ISSUE TITLE
Review nightly errors and results

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2328]
Seems https://github.com/gardenlinux/gardenlinux/actions/runs/10805896028   is throwing

> Annotations 68 errors upload to S3 / upload to S3 (amd64, gdch, -gardener_prod) Unable to download artifact(s): Artifact not found for name: platform-test-gdch-gardener_prod-amd64-1625.0-f549c95d Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact. For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md

**Comment by yeoldegrove** [comment]
The nightly run just ran through: https://github.com/gardenlinux/gardenlinux/actions/runs/10805896028
No issues with the pipeline.

**Comment by pnpavlov** [comment]
@yeoldegrove , yes, I see but the 68 annotations look like a real problem to me. Can you please investigate further?
E.g. I see https://github.com/gardenlinux/gardenlinux/actions/runs/10805896028/job/29975907507#step:8:17 which looks like the actual root cause or? 

![Image](https://github.com/user-attachments/assets/3c3cbba7-3190-471c-becd-df04bd4a27d5)

**Comment by yeoldegrove** [comment]
@pnpavlov #2333 Could be a potential fix fox the annotations you see.

These come from the `continue-on-error: true` step for downloading the platform-test logs on platforms that do not produce those logs.
