### ISSUE TITLE
simple way to resolve and validate garden linux versions

### ISSUE THREAD

**Issue by yeoldegrove** [gardenlinux/gardenlinux#2389]
**What would you like to be added**:
For developing CI/CD use cases we need a simple way to resolve and validate `latest`, `nightly`, `release` (e.g. 1592.1), `dev-release` (e.g. 1639.0-928117ea) garden linux versions.
By resolving, I mean to query for any of the above inputs and getting a `${release}-${commit}` string like `1592.1-ec945aa9` back. This string can than be used to query S3 artifacts to e.g. download image files.

**Why is this needed**:
- I want to be able to test `latest`, `nightly`, `release` (e.g. 1592.1), `dev-release` (e.g. 1639.0-928117ea) garden linux versions in CI/CD pipelines and download their images.
- I want to know what the `latest` gardenlinux release is.
- optional: I want to know where to download releases.

**Comment by yeoldegrove** [comment]
https://github.com/gardenlinux/gardenlinux/pkgs/container/gardenlinux will be the source of truth for latest (was agreed upon in a previous meeting) and `nightly` and any official `$release` and also `$dev-releases` can also be found there.

- An issue that remains is finding a commit for `nightly` and `$dev-releases` as they are not tagged commits in the repo.
  - One approach would be actually creating tags in the repo for `nightly`, `latest` and `$dev-releases`.
  - Another approach would be just tagging the images with their commit hashes.

I would like tagging the images better as this is less intrusive to the repo itself. It could potentially also be done for historic releases I guess.

@gehoern @pnpavlov @gardenlinux/garden-linux-maintainers Any thoughts on this?

**Comment by yeoldegrove** [comment]
@f

> Related (hacky) script to infer versions based on existence of package files: https://github.com/gardenlinux/glvd-data-ingestion/blob/main/gardenlinux-versions.py

Interesting...you query `https://packages.gardenlinux.io/gardenlinux/dists/{v}.{p}/main/binary-amd64/Packages.gz` as yet another source of truth ;)
I guess we need to align on how to approach this. 

Maybe something from the OCI space also already tries to tackle this issue?

**Comment by fwilhe** [comment]
> as yet another source of truth ;)

yeah but this is really true, not like the other fake-truths 🫠
