### ISSUE TITLE
Fix nightly broken since Fri 11th Oct

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2404]
https://github.com/gardenlinux/gardenlinux/actions/workflows/nightly.yml
Related to https://github.com/gardenlinux/gardenlinux/issues/2161

![Image](https://github.com/user-attachments/assets/41849242-61de-4147-8d0e-6fdad83d089f)

**Comment by fwilhe** [comment]
This is my mistake, I made a 'null' release for ostree to opt out of rebuilding it, and I forgot to attach a 'null' release artefact.

<img width="864" alt="Screenshot 2024-10-14 at 09 42 43" src="https://github.com/user-attachments/assets/1283f360-10b4-4212-8d21-57e702e6e863">


Added the artefact here https://github.com/gardenlinux/package-ostree/releases/tag/null and hope that resolves the problem.

**Comment by fwilhe** [comment]
I've added a release artifact to that ostree release

repo build worked https://github.com/gardenlinux/repo/actions/runs/11319000774
nightly is in progress but past the bootstrap stage https://github.com/gardenlinux/gardenlinux/actions/runs/11321841929

I think we can close this issue
