### ISSUE TITLE
Integration of OCI delivery in gardenlinux build pipelines

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#2441]
Integrate oci delivery gear into Garden Linux build pipelines.

Requirements:
- gardenlinux/python-gardenlinux-lib#26 
- gardenlinux/python-gardenlinux-lib#16 

Tasks: 
- [ ] Check and set defaults for gardenlinux/gardenlinux use case (path to pub/priv keys)
- [ ] Deploy gl-oci in pipelines (check what method is best)

**Comment by pnpavlov** [comment]
Can you please align if we can have in the final version the "standard" gardenlinux manifest so we can do like podman/docker run/pull but also pull the relevant layers in the same label? 

CC @nkraetzschmar
