### ISSUE TITLE
Add Garden Linux integrations tests for all supported cloud providers and extend existing ones.

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#246]
**What would you like to be added**:

There are currently integrations tests for AWS and GCP in https://github.com/gardenlinux/gardenlinux/tree/main/tests/integration directory. There are no integration tests for any other cloud provider. Also, it seems that tests have deteriorated due to changes in security policies for our infrastructure accounts. We need to have those tests for all cloud providers and we need to extend them based on our learnings.

**Why is this needed**:

With the last Garden Linux release we have seen roughly four issues, where two affected all cloud providers and two affected single cloud providers. We only discovered this after the release of the images which is the reason we have 318.4 (or even in one case 318.6). Manually uploading and testing the images is very time consuming and cumbersome. Testing is described in this issue, uploading is described in #247.

**Comment by marwinski** [comment]
For milestone 2021-Q3 we need to have integration tests for Azure, AWS, and GCP.

**Comment by gyptazy** [comment]
Hey @marwinski,

I think we might close this issue while we cover most tests for the supported platforms, running nightly builds on all platforms and added multiple new tests. However, I can see that're missing:
 * Tests for VMWare
 * Implement a `keen_running_on_error`

Maybe we should create dedicated issues (if still needed) and close this one?

What do you think?

**Comment by gyptazy** [comment]
I think we may close this issue. Garden Linux has everything in place for uploading and testing artifacts on all supported platforms (except of VMware) (see also https://github.com/gardenlinux/gardenlinux/blob/main/tests/README.md), now.

Currently, we can workaround the `keep_running_on_error` by setting `keep_running` - however, it might not catch race conditions but reproducible ones. If you think this is needed, feel free to reopen this issue or to create a new one (probably a new one would be a better idea).

Thanks,
gyptazy
