### ISSUE TITLE
Fix nightly Nov 11 2024

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2461]
Nightly fails in all platform tests

https://github.com/gardenlinux/gardenlinux/actions/runs/11773036637

Errors look different on the platforms, need to investigate.

**Comment by fwilhe** [comment]
Errors come from `audit-rules.service`

The first build failed on Saturday. Also, debian upgraded auditd from v3 to v4 on Saturday in testing ([see tracker](https://tracker.debian.org/news/1583711/audit-1401-3-migrated-to-testing/)). I can reproduce the issue with a local vm, building one with today and booting it gives a failed audit systemd unit, doing the same with 1592.2 does not fail that unit.

**Comment by fwilhe** [comment]
PR by @5kt #2463

**Comment by pnpavlov** [comment]
nightly is green again. done.
