### ISSUE TITLE
Fix and extend automated upload scripts for development images

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#247]
**What would you like to be added**:

There shall be stable upload scripts that upload development images to the cloud providers as a pre-requisite for running integration tests (see #246). In addition, the Garden Linux repository should be cleaned from any references to account specific settings that we are using. Those scripts or Makefile targets should be usable directly by developers as well as our build pipelines. 

**Why is this needed**:

There are automated upload scripts for almost all cloud providers triggered by the `-upload` make targets. The problem is that they (a) contain account specific information and (b) usually don't work because some environment setting or bucket name has been changed. This makes uploading and testing images a very cumbersome and time consuming task.

I as a developer usually want to make a change and quickly upload and test it for a particular cloud provider. Before a new release is triggered, we need to make sure the change does not break Garden Linux on any other cloud provider. This could be triggered though a build pipeline.

**Comment by gyptazy** [comment]
I think we may close this issue. Garden Linux has everything in place for uploading and testing artifacts on all supported platforms (see also https://github.com/gardenlinux/gardenlinux/blob/main/tests/README.md), now.

If you think this is a mistake, feel free to reopen this issue again.

Thanks,
gyptazy
