### ISSUE TITLE
Describe in-place-update tool return codes

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2504]
Provide return codes description , return code 0 - everything is fine, return code 1 or 2 depending if it is possible to solve the problem with a retry or not.

**Comment by nkraetzschmar** [comment]
| Exit Code | Meaning           | Retry-able         |
|-----------|-------------------|--------------------|
| 0         | success           | :heavy_minus_sign: |
| 1         | invalid arguments | :x:                |
| 2         | system failure    | :x:                |
| 3         | network problems  | :white_check_mark: |



So gardener should primarily check if exit code is 0 for all good, 3 for retry, and the distinction between 1 and 2 is essentially:
- 1: gardener fucked up their input
- 2: something on the OS is broken, likely beyond repair

---

https://github.com/gardenlinux/package-gardenlinux-update/pull/5

exit codes are explicitly listed in the `--help` output of the update tool:

```
Usage: ./gardenlinux-update [options] <version>

  -media-type string
        artifact media type to fetch (default "application/io.gardenlinux.uki")
  -os-release string
        alternative path where the os-release file is read from (default "/etc/os-release")
  -repo string
        OCI repository to download from (default "ghcr.io/gardenlinux/gl-oci")
  -skip-efi-check
        skip performing EFI safety checks
  -target-dir string
        directory to write artifacts to (default "/efi/EFI/Linux")

exit codes:
        0: success
        1: invalid arguments
        2: system failure
        3: network problems
```
