### ISSUE TITLE
K8s Cluster Nodes with GL 318.4 getting stuck/NotReady

### ISSUE THREAD

**Issue by dguendisch** [gardenlinux/gardenlinux#251]
**What happened**:
Running a node with GL `318.4` often gets stuck (as in becoming `NotReady`) when a certain amount of idling pods are running on it.
Nodes with GL `184.0.0` and the same load/amount-of-pods don't exhibit this behaviour.

When a node becomes `NotReady` we couldn't ssh into the node either and existing console session were stalling.
From K8s point of view we noticed various events, most prominently `Kubelet stopped posting node status`, but sometimes also from some "kernel-monitor":

```
Events:
  Type     Reason    Age    From            Message
  ----     ------    ----   ----            -------
  Warning  TaskHung  5m23s  kernel-monitor  INFO: task kswapd0:49 blocked for more than 120 seconds.
  Warning  TaskHung  5m22s  kernel-monitor  INFO: task jbd2/sda4-8:363 blocked for more than 121 seconds.
  Warning  TaskHung  5m21s  kernel-monitor  INFO: task dockerd:6500 blocked for more than 121 seconds.
  Warning  TaskHung  5m19s  kernel-monitor  INFO: task dockerd:9030 blocked for more than 122 seconds.
  Warning  TaskHung  5m17s  kernel-monitor  INFO: task dockerd:9551 blocked for more than 122 seconds.
  Warning  TaskHung  5m15s  kernel-monitor  INFO: task containerd:7378 blocked for more than 122 seconds.
  Warning  TaskHung  5m12s  kernel-monitor  INFO: task containerd:8414 blocked for more than 123 seconds.
  Warning  TaskHung  5m9s   kernel-monitor  INFO: task kubelet:3979 blocked for more than 123 seconds.
  Warning  TaskHung  5m6s   kernel-monitor  INFO: task kubelet:4211 blocked for more than 124 seconds.
  Warning  TaskHung  5m5s   kernel-monitor  (combined from similar events): INFO: task kubelet:6670 blocked for more than 124 seconds.
```

**What you expected to happen**:
GL `318.4` to not perform significantly worse than GL `184`

**How to reproduce it (as minimally and precisely as possible)**:
- Create a gardener cluster with two worker pools, one with `318.4` and one with `184`.
- Deploy a simple `Deployment` with anti-affinity:
<details><summary>deployment.yaml</summary><p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-load
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load
  template:
    metadata:
      labels:
        name: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
          # preferredDuringSchedulingIgnoredDuringExecution:
          # - podAffinityTerm:
          #     topologyKey: "kubernetes.io/hostname"
          #   weight: 100
      containers:
      - name: load
        image: nicolaka/netshoot
        command:
        - bash
        args:
          - -c
          - |
            sleep 3153600000
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      terminationGracePeriodSeconds: 1

```

</p></details>

- Scale the deployment, I could see kubelet/node flapping with about 70 pods on each worker pool (140 pods in total), e.g. `k scale deployment some-load --replicas 140`

cc @vpnachev

**Comment by marwinski** [comment]
I suspect this might be related to the new Docker version (20) in Garden Linux 318.4. All other distros appear to still use Docker 19.

**Comment by vpnachev** [comment]
Last week I failed to reproduce the problem with k8s 1.18, but now with 1.19 with just 100 pods and the node quickly went in `NotReady` state. 

I am ssh-ed on the node and kubelet seems to be working, but the container runtime is not responsive as a lot of requests are timing out. After kubelet restart, the kubelet condition on the node also show it
```
Ready                         False   Thu, 20 May 2021 22:17:04 +0300   Thu, 20 May 2021 22:11:09 +0300   KubeletNotReady                 container runtime status check may not have completed yet
```

`journalctl -u docker` generated just 10-20 lines of logs during the time when the deployment had 100 replicas. In general, only kubelet is logging errors/warnings about timeouts, while docker (docker-shim or containerd) seems to be stuck somewhere after
```
May 20 19:33:33 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:33.762762537Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/4f0977642114cb46c83507952b1bd02c9456857e4bf36eb9b523ff370810c567 pid=38000
May 20 19:33:33 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:33.794952455Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/39be19ec561a35a022d954284f3d7497bedd97912a8f11d819b027ff5527e3cd pid=38018
May 20 19:33:33 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:33.929288130Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/3c282948f88c240e1fb3a8ac2476e8eb133017014ad4da2c93a0d02bbcee2093 pid=38066
May 20 19:33:34 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:34.014810518Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/35fe6a64dbe6fcc9b8614d9f36733c8fd3f001d2b96067299c393f14d18c4bfc pid=38032
May 20 19:33:34 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:34.467649283Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/be301bfaa5721ef7e93e18a5e8e9e26458aa6bec6bbd74463f3708dde97756cf pid=38125
May 20 19:33:34 shoot--foo--gl-perf-eval-318-4-z1-6f94b-fd6vf dockerd[2953]: time="2021-05-20T19:33:34.580833868Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/79c344a0f6d9edea9827eeb1fc00875344277f0a859ef28bd5767a75a260883a pid=38151
```


Same cluster, but with node with gVisor and cotainerd have no issues to host the same 100 pods. 

So, it looks like something related to the k8s version and docker CR(I).

**Comment by vpnachev** [comment]
Upgrading to the latest available docker version `20.10.5+dfsg1` does not help.

**Comment by vpnachev** [comment]
Downgrading to the `19.03.13+dfsg1-2` which is used in GL 184.0 does not improve the situation. 
I guess there is a regression in kubernetes 1.19 when docker is used as CR(I). Will take a deeper look in this direction.

**Comment by dguendisch** [comment]
> I guess there is a regression in kubernetes 1.19 when docker is used as CR(I)

But isn't that the same k82 1.19 with docker via CRI used via GL 184 _and_ GL 318? So if we see a diff between those two GL versions, than it shouldn't be a regression in k8s itself?

**Comment by vpnachev** [comment]
Yes, you are right. This is completely the same k8s worker node setup that we are using also on 184.0 and there everything is working perfectly fine. 

Something has been changed in this k8s version that triggers the problem that we are observing with docker. I am also checking what we have changed https://github.com/gardenlinux/gardenlinux/compare/184.0...318.4. 
I need to take a deeper look into changes like:
- https://github.com/gardenlinux/gardenlinux/commit/6c047ef151bb776a5f4284ffae79bef071308b26
- https://github.com/gardenlinux/gardenlinux/commit/d7f87d7fb5b60cbe7f53fa2bcf36b06d51547162 
- https://github.com/gardenlinux/gardenlinux/commit/254f287aa20721ee550bcb8e032258e08c68030c

Additionally, almost every package have been updated compared to 184.0. 

It is such an unfortunate situation where kubelet is just timing out and docker logs nothing :disappointed: .

**Comment by vpnachev** [comment]
TL;DR - image build from main (4c7a19c5eede7ebd196426b947721185c89e8d31 on May 26 2021) is working fine and the above problem is not observed - I managed to create a deployment with 200 replicas without any issues.

#### Some more details

We are not alone with this problem. Similar difficulties are reported by others with recent versions of OS/Docker/Containerd/runC, ref:
- https://github.com/kubernetes/kubernetes/issues/45419#issuecomment-803358917
- https://github.com/rancher/rancher/issues/31793

Basically, the issue is rooted in the runC and how PLEG is using `docker ps` which is timing out, I cannot explain it better than https://github.com/kubernetes/kubernetes/issues/45419#issuecomment-823885293. 

Related containerd/runc issues:
- https://github.com/containerd/containerd/issues/5261
- https://github.com/opencontainers/runc/issues/2828

Looking into these packages versions, we see that building from main branch today provides upgrades for all packages and fix for the above issue is also included.
| GL Version    | Docker     | Containerd  | runC |
| :------------- | -----:| -----:| -----:|
| 184.0 | 19.03.13+dfsg1-2 | 1.4.1~ds1-1 | 1.0.0~rc92+dfsg1-5 |
| 318.4 | 20.10.2+dfsg1-2 | 1.4.3~ds1-1+b1| 1.0.0~rc93+ds1-1 |
| 421.0 | 20.10.5+dfsg1-1+b1 | 1.4.4~ds1-2| 1.0.0~rc93+ds1-5|

**Comment by vlerenc** [comment]
Awesome @vpnachev. Thank you!

Now, what's the plan? By now, are we trying to get 421.0 out in the hope, it will last longer than 318.4 can (that has the security vulnerabilities). In which state is 421.0? When the decision is taken, we must plan the roll-out, have someone from us ready on a weekend, combine it with the next Kubernetes minor upgrade, etc. That will take a few extra days coordination/deciding for a date/informing stakeholders in advance.

**Comment by vpnachev** [comment]
I vote for building new major version and stop investing into 318.X exactly because a lot of packages received updates which should include security and bug fixes. Also, 318 is based on debian testing state since 100+ days which is quite 
There are some issues with the build currently, for example https://github.com/gardenlinux/gardenlinux/issues/253, but this out of scope of this issue.

**Comment by vpnachev** [comment]
But if we still want to proceed with 318.X, it is possible - we just need to upgrade the runc package, docker and containerd packages.

**Comment by vlerenc** [comment]
Frankly, I wouldn't know why to continue with 318.4, so unless we hit a wall with 421.0/the latest version, I would always strive for that one and go back only if that wall is too high.

**Comment by marwinski** [comment]
I strongly suggest to go ahead with 318.x. Why? It took us more than three months to make 318 work for all cloud providers only to figure out that there is another road block - this issue here. Want a glimpse on what to expect with 4xx? See #253 - it does not even build. It contains lots of new stuff and especially a new major kernel version - honestly we need some more time and a longer "preview" period and should not push this through very quickly. This said, a 318.x with all necessary fixes can be ready today for testing, a 4xx will be quite uncertain and we start pretty much where we started with 318.

**Comment by marwinski** [comment]
The next commit on the 318 branch will contain the following versions:

```
root@garden:~# dpkg -l | grep -E 'docker.io|bind9|runc|containerd'
ii  bind9-dnsutils                        1:9.16.11-2                    amd64        Clients provided with BIND 9
ii  bind9-host                            1:9.16.11-2                    amd64        DNS Lookup Utility
ii  bind9-libs:amd64                      1:9.16.11-2                    amd64        Shared Libraries used by BIND 9
ii  containerd                            1.4.4~ds1-2                    amd64        open and reliable container runtime
ii  dnsutils                              1:9.16.11-2                    all          Transitional package for bind9-dnsutils
ii  docker.io                             20.10.5+dfsg1-1+b1             amd64        Linux container runtime
ii  runc                                  1.0.0~rc93+ds1-5               amd64        Open Container Project - runtime
```

**Comment by marwinski** [comment]
318.8 which fixes the issue has been delivered.
