### ISSUE TITLE
ext4 FS errors with a node

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#263]
**What happened**:

One of the ETCD nodes went into NotReady state with a lot of ext4 errors

```
  Warning  Ext4Warning  2m14s                  kernel-monitor  EXT4-fs warning (device nvme19n1): htree_dirblock_to_tree:997: inode #1048579: lblock 0: comm etcd: error -5 reading directory block
  Warning  Ext4Error    2m13s                  kernel-monitor  EXT4-fs error (device nvme19n1): ext4_wait_block_bitmap:517: comm etcd: Cannot read block bitmap - block_group = 34, block_bitmap = 1048578
  Warning  Ext4Error    2m13s                  kernel-monitor  EXT4-fs error (device nvme19n1): ext4_discard_preallocations:4095: comm etcd: Error -5 reading block bitmap for 34
  Warning  Ext4Error    2m13s (x2 over 2m13s)  kernel-monitor  EXT4-fs error (device nvme19n1): ext4_wait_block_bitmap:517: comm etcd: Cannot read block bitmap - block_group = 31, block_bitmap = 524303
  Warning  Ext4Error    2m13s (x2 over 2m13s)  kernel-monitor  EXT4-fs error (device nvme19n1): ext4_discard_preallocations:4095: comm etcd: Error -5 reading block bitmap for 31
  Warning  Ext4Error    2m12s (x2 over 2m13s)  kernel-monitor  EXT4-fs error (device nvme19n1): __ext4_find_entry:1531: inode #2: comm bootstrap.sh: reading directory lblock 0
  Warning  Ext4Error    2m8s                   kernel-monitor  EXT4-fs error (device nvme14n1): ext4_wait_block_bitmap:517: comm etcd: Cannot read block bitmap - block_group = 623, block_bitmap = 19922959
  Warning  Ext4Warning  2m8s                   kernel-monitor  EXT4-fs warning (device nvme14n1): htree_dirblock_to_tree:997: inode #4718595: lblock 0: comm etcd: error -5 reading directory block
  Warning  Ext4Error    2m8s                   kernel-monitor  EXT4-fs error (device nvme14n1): ext4_discard_preallocations:4095: comm etcd: Error -5 reading block bitmap for 623
  Warning  Ext4Error    2m8s                   kernel-monitor  EXT4-fs error (device nvme14n1): ext4_wait_block_bitmap:517: comm etcd: Cannot read block bitmap - block_group = 619, block_bitmap = 19922955
  Warning  Ext4Error    2m8s                   kernel-monitor  EXT4-fs error (device nvme14n1): ext4_discard_preallocations:4095: comm etcd: Error -5 reading block bitmap for 619
  Warning  Ext4Error    2m7s                   kernel-monitor  EXT4-fs error (device nvme14n1): __ext4_find_entry:1531: inode #2: comm bootstrap.sh: reading directory lblock 0
  Warning  Ext4Error    2m (x8 over 2m8s)      kernel-monitor  (combined from similar events): EXT4-fs error (device nvme2n1): __ext4_find_entry:1531: inode #2: comm bootstrap.sh: reading directory lblock 0
  Warning  Ext4Warning  2m                     kernel-monitor  EXT4-fs warning (device nvme2n1): htree_dirblock_to_tree:997: inode #3670019: lblock 0: comm etcd: error -5 reading directory block
  Warning  Ext4Warning  117s                   kernel-monitor  EXT4-fs warning (device nvme7n1): htree_dirblock_to_tree:997: inode #131075: lblock 0: comm etcd: error -5 reading directory block

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by gehoern** [comment]
Looking in the web for similar issues and there are reports about issues with NVMe disk and APST

https://wiki.archlinux.org/title/Solid_state_drive/NVMe#Controller_failure_due_to_broken_APST_support
https://bugzilla.kernel.org/show_bug.cgi?id=208123
https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1953915
All of them recommend as mitigation the kernel parameter nvme_core.default_ps_max_latency_us to be set on some value( 0 or 5500).

Checking on GL 184.0 node this parameter is not set:
```

root@ip-10-242-15-237:/# cat /etc/os-release ; sysctl -a | grep nvme_core
PRETTY_NAME="Garden Linux 184.0"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://gardenlinux.io/"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_FEATURES=base,aws,_nopkg,_prod,_readonly,_slim,base,cloud,gardener,server
GARDENLINUX_VERSION=184.0
GARDENLINUX_COMMIT_ID=e5a1576deded4cb778b178ed279c38138e384f63
VERSION_CODENAME=bullseye
root@ip-10-242-15-237:/# 
```
@D061226 could you also take a look on this filesystem issue?

**Comment by vpnachev** [comment]
cc @marwinski as he is also looking into this.

**Comment by waldiTM** [comment]
@gehoern Can you please attach the complete kernel log? It should also contain log messages for those errors within NVMe, and not only log messages from the filesystem.

**Comment by gehoern** [comment]
can someone output the value /sys/module/nvme_core/parameters/io_timeout here?

**Comment by marwinski** [comment]
@waldiTM unfortunately we don't have kernel logs except what we have above. The VM is long gone as it is recycled after 20 minutes.

**Comment by vpnachev** [comment]
```bash
$ cat /sys/module/nvme_core/parameters/io_timeout
30
$ cat /etc/os-release
PRETTY_NAME="Garden Linux 184.0"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://gardenlinux.io/"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_FEATURES=base,aws,_nopkg,_prod,_readonly,_slim,base,cloud,gardener,server
GARDENLINUX_VERSION=184.0
GARDENLINUX_COMMIT_ID=e5a1576deded4cb778b178ed279c38138e384f63
VERSION_CODENAME=bullseye

```

**Comment by dguendisch** [comment]
During the past aws outage https://www.theregister.com/2021/06/11/aws_eu_central_1_incident/ we noticed most of our VMs getting the condition `Reason:FilesystemIsReadOnly Message:EXT4-fs (nvme8n1): Remounting filesystem read-only`
Unfortunately we couldn't get logs from the VMs (they were gone already), so maybe it's related, maybe not.

**Comment by marwinski** [comment]
We have secured a running VM which ran into the issue. Problem is that a disk had originally been attached as /dev/nvme3n1 but that attachment was later changed to /dev/nvme3n2. 

We have opened a ticket with AWS for further investigation. This does not appear to be a (Garden) Linux issue.

**Comment by marwinski** [comment]
We consider this issue not to be a Garden Linux issue. We were able to reproduce the behaviour with a different Linux distribution and consider it "works as designed":

1. Attach an external volume to the host (nvme1n1). Format it and use it.
2. Detach the volume without unmounting it
3. ext4 errors can be seen as expected
4. Attach the volume again. Now it got nvme1n2

**Comment by neo-liang-sap** [comment]
Hi @marwinski , customer contacted me during my shift as DOD for this issue in https://github.tools.sap/kubernetes-live/issues-live/issues/685 , they talked with AWS support and AWS support didn't reproduce this problem in Ubuntu, could you please take a look at https://github.tools.sap/kubernetes-live/issues-live/issues/685 when you have time? thanks!
-Neo
/reopen

**Comment by neo-liang-sap** [comment]
/close
after discussion with Dieter

**Comment by dguendisch** [comment]
fyi: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1007 triggers reproducibly ext4 fs errors (when the kubelet was restarted, and a statefulset or pod with volume was force-deleted and then scheduled to that same node eventually)
