### ISSUE TITLE
Make Vmware failed to create build directory

### ISSUE THREAD

**Issue by tuxgoose** [gardenlinux/gardenlinux#274]
**What happened**:
make vmware
**What you expected to happen**:
to have rootfs.* files in the build directory under data/amd64/bullseye
**How to reproduce it (as minimally and precisely as possible)**:
make vmware

**Anything else we need to know**:

executing tiger tests
tiger detected the following errors
--FAIL-- [pass021f] Integrity of sudoers files questionable (run 'visudo -c').
failed

Tests 34 done. 1 failed

**Environment**:
Lenovo Thinkstation  32GB ram 2xE5-2650L xeon

5.4.0-77-generic
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

**Comment by mbanck** [comment]
I tried to reproduce this, and I do get `rootfs` files in `.build/vmware/20210626/amd64/bullseye/` after typing `make vmware`; was there any output after `Tests 34 done. 1 failed` and if so, what was it?

**Comment by tuxgoose** [comment]
Looks like they are there, sorry thought it would be build in build not .build

heedo@thinkstation:~/gardenlinux/.build/vmware$ ls
20210626

~/gardenlinux/.build >>> ls                                    ±[A171●][master]
gcp  kvm  vmware  vmware-dev

looks like they are there
