### ISSUE TITLE
make vmware

### ISSUE THREAD

**Issue by tuxgoose** [gardenlinux/gardenlinux#285]
**What happened**:
executing tiger tests
tiger detected the following errors
--FAIL-- [pass021f] Integrity of sudoers files questionable (run 'visudo -c'). 
failed

Tests 34 done. 1 failed

**What you expected to happen**:

all tests to succeed 

**How to reproduce it (as minimally and precisely as possible)**:

make vmware

**Anything else we need to know**:

**Environment**:
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**Comment by gehoern** [comment]
thanks for the hint. fixed.

the handling of file permissions in git is messy. In fact all files in the sudoers directory have to be 0440. That was set on the build machine but not properly checked out - also not for all files.
I was not able to fix that in git so i fix it in script.

Thanks for raising the issue.

df6fbb60ee15f6df4ce3e3de21fca83f42d9332a
b3442e70c825833c5bd2e9d8bac4905132c716e3
2a4599ab525956c1af87304c8387e81195cb0ce9

**Comment by tuxgoose** [comment]
Thanks for the fix!
