### ISSUE TITLE
Make VMWare user credentials

### ISSUE THREAD

**Issue by tuxgoose** [gardenlinux/gardenlinux#289]
**What happened**:
I note that with the make vmware scripts the vms do not auto-login

**What you expected to happen**:
Former make kvm they auto-login

**How to reproduce it (as minimally and precisely as possible)**:
make vm
load ova in vmware

**Anything else we need to know**
I feel like I am doing something wrong, is there a default cred, should I be passing credentials in the script, is there a default?

**Environment**:
esxi 7.0 Update 2

**Comment by gehoern** [comment]
there are NO credentials et all :-D ... i mean for safety, but it usually uses client tool of the hyperscaler / hypervisor to get the credentials propagated from outside.
If you build with the _dev feature it adds an autologin - either on the console drop dead stupid, or with a generated key for ssh.

**Comment by tuxgoose** [comment]
I am installing VCenter Server, I am assuming this would give me the ability to propagate credentials.

**Comment by tuxgoose** [comment]
This is a user error, when creating the vm I only used the ova, and did not include vmdk and raw file
