### ISSUE TITLE
rngd.service appears to fail on GCP

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#291]
**What happened**:

On GCP run 

```
systemctl list-units --output=json --state=failed
```

it shows a failed unit:

```
[{"unit":"rngd.service","load":"not-found","active":"failed","sub":"failed","description":"rngd.service"}]
```

In fact it did not fail to start.

**What you expected to happen**:

No error shown.

**How to reproduce it (as minimally and precisely as possible)**:

Launch a Garden Linux 318.8 VM, log in and run the command given above.

**Anything else we need to know**:

**Environment**:

**Comment by marwinski** [comment]
Just to clarify: this is a cosmetic problem. The `rngd` daemon runs and reports success in the logs.

**Comment by MrBatschner** [comment]
This message is caused by the fact that rngd still gets started and stopped by an old Sys-V init script in `/etc/init.d` with the [rng-tools-debian](https://packages.debian.org/testing/rng-tools-debian) package we are using. Creating a systemd service unit file and removing the Sys-V init script should fix this cosmetic error.

**Comment by MrBatschner** [comment]
This is from the package description of [rng-tools-debian](https://packages.debian.org/bullseye/rng-tools-debian):

_This is an unofficial version of rng-tools (as classically shipped by Debian up to and including release 10 “buster”), version 2, extensively modified to add multithreading and a lot of new functionality. **However, most users of newer or high-bandwidth HWRNGs might wish to install the latest version of upstream rng-tools (packaged as rng-tools5) instead; that package offers more performant support for those, even if it lacks the new functionality from this version.**_

And this is from [rng-tools](https://packages.debian.org/bullseye/rng-tools), a transition package:

_[...] you can continue using rng-tools-debian but please consider switching to rng-tools5 if you can, as that is the more modern solution._

Do we have a hard requirement to stick with Debians modified version 2 of rng-tools? If not, we should change to rng-tools5.

**Comment by marwinski** [comment]
from my point of view we can change this. There is a convincing argument to change
