### ISSUE TITLE
Enable fail2ban service

### ISSUE THREAD

**Issue by berendt** [gardenlinux/gardenlinux#302]
There is already a lot prepared for fail2ban. However, the fail2ban package is commented. fail2ban should be activated to secure SSH a little.

**What would you like to be added**:

fail2ban service should be enabled by default.

**Why is this needed**:

Increase the security of the nodes against attacks.

**Comment by berendt** [comment]
Probably this is not in-scope from gardenlinux project itself but from the Gardener OS extension?

**Comment by gehoern** [comment]
good point ... we want to move ssh to a container -> so no ssh on gardenlinux at all. Our support personell got scared of this. and yes in the container there is already fail2ban ... i will copy the config for the time being. You are right. but lets think about the python dependencies.

**Comment by marwinski** [comment]
As far as I remember we had fail2ban initially but it broke "something". This is the reason it is commented. Unfortunately I cannot remember the "something" bit.

**Comment by marwinski** [comment]
@gehoern: removing sshd from Garden Linux was my idea but the impact on Gardener is not yet understood. ssh access often is the only possibility to debug a node if it fails to join a cluster (which still happens surprisingly often).

**Comment by gyptazy** [comment]
I'm currently integrating this as an optional feature together with an optional sshd (#1193). By providing feature sets, it's in the operators decision.

**Comment by gyptazy** [comment]
Info: First draft PR in #1334.
