### ISSUE TITLE
Enable cgroups v2

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#310]
**What would you like to be added**:

With https://github.com/gardenlinux/gardenlinux/pull/205 we have removed cgroup v2 support for compatibility reasons. This should be enabled again.

**Why is this needed**:

A bunch of interesting features depend on it such as Rootless Kubernetes and more precise memory accounting useful for resource reservations.

**Comment by danielfoehrKn** [comment]
The Gardener perspective:

While K8s 1.18 is already [EOL](https://endoflife.date/kubernetes),  Gardener CloudProfiles can still contain a Cluster with let's say 1.17 with a later expiration date.
But the machine image version is separately updateable and can be on the latest Gardenlinux with auto-update.
If the next Gardenlinux version would just enable cgroupsv2, then updating a Cluster with K8s < 1.18 to this new Gardenlinux version would break.  

I think what Gardener needs is the following:

- The CloudProfile should have the [option to restrict a MachineImage version to certain Kubernetes versions.](https://github.com/gardener/gardener/blob/01a4b09e431c2a78b69f974bdf527c2b1469acdc/pkg/apis/core/v1beta1/types_cloudprofile.go#L119)
  - This way we could say in the Cloud Profile: Gardenlinux <new version> --> only >=1.18 K8s version
- The Maintenance controller should respect this
- Gardener API server Admission plugins should respect it

**Comment by vpnachev** [comment]
Ideally there must not be any dependency between the OS and K8S versions.
The os extension is aware of both - k8s and OS version and it can easily configure to fit them.
For example, for k8s >= 1.18 and Garden Linux >318 use cgroup v2, otherwise v1.

**Comment by danielfoehrKn** [comment]
I think you need a reboot of the OS to configure the Kernel parameter for cgroupsv1, so that might not work / is not ideal.

**Comment by marwinski** [comment]
After discussion with @MrBatschner:

- this should be done in the OS extension
- Garden Linux should enable cgroup v2 by default once this is handled by the OS extension

**Comment by danielfoehrKn** [comment]
So the OS extension would check for the desired cgroups version to be configured based on the k8s version and change + reboot if necessary?
Has anyone tried rebooting a machine during the bootstrap and knows the delay / other issues it may cause?

**Comment by danielfoehrKn** [comment]
FYI: https://deploy-preview-29015--kubernetes-io-main-staging.netlify.app/blog/2021/09/01/qos-memory-resources/

**Comment by MrBatschner** [comment]
Reopened due to different approach in Garden Linux extension that takes the discussion above into account. See https://github.com/gardener/gardener-extension-os-gardenlinux/pull/63.

**Comment by Vincinator** [comment]
I think we can close this. If you think this was a mistake, please re-open.
