### ISSUE TITLE
Set additional tags on AWS AMI Images for Security Scanning

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#315]
**What would you like to be added**:

We need an extension to the ```make-ec2-ami``` and ```ci/glci/aws.py``` code to add an additional tag to the register_image operation:

```
sec-by-def-public-image-exception:  enabled
```

**Why is this needed**:

We have security scanners in place that complain about the AMIs being public. As the images must be public this tag silences the security scan.

**Comment by MrBatschner** [comment]
still missing in make-ec2-ami
