### ISSUE TITLE
Build result should have build logs

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#316]
**What would you like to be added**:

The build results should be populated with full build logs.

**Why is this needed**:

Builds may fail at certain points in time due to changed side conditions. Builds may be erroneous but may not fail for some reason. For comparing and researching it is essential to be able to inspect build logs at a later point in time.

**Comment by jensh007** [comment]
The logs are collected and attached to the notification email.

**Comment by marwinski** [comment]
@jensh007 I don't understand. I don't get notification emails and would anyway delete them in most cases. Can't we store logs next to the build results?

**Comment by jensh007** [comment]
@marwinski Please add yourself to gardenlinux-maintainers to receive build notifications. Feel free to create an enhancement issue for storing the logs with the build result (cc: @ccwienk )

**Comment by marwinski** [comment]
build logs are already written. Need to check whether those are uploaded to s3

**Comment by marwinski** [comment]
done
