### ISSUE TITLE
Trigger waagent update in Debian

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#322]
**What would you like to be added**:

We currently build Garden Linux with a forked waagent. We need to update the waagent in Debian (either with our fix or an updated version from Microsoft).

**Why is this needed**:

We need to get rid of our fork and provide the fix for the whole Debian community.

**Comment by waldiTM** [comment]
I just uploaded waagent 2.3.1.1 to Debian.

**Comment by chrinorse** [comment]
I think, we can close this ticket, by now waagent 2.6.0.2 made it into Debian testing. We also replaced waagent with cloud-init in the Azure image.

https://tracker.debian.org/pkg/waagent
