### ISSUE TITLE
Configure Garden Linux image according to infrastructure provider recommendations [VMware]

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#328]
**What would you like to be added**:

We need to make sure we adhere to the recommendations of the infrastructure providers.

**Why is this needed**:

We have seen subtle issues with DNS resolution, clock diversions, nvme issues, etc. due to wrong or omitted configurations.

**Comment by tuxgoose** [comment]
Be curious as to what the dns provider is being used that you are seeing issues.

**Comment by marwinski** [comment]
There is currently no action item and no known improvement for this provider.
