### ISSUE TITLE
Trigger cloud-init update in Debian

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#330]
**What would you like to be added**:

The following bug describes a problem with cloud-init on Ali which was fixed in cloud-init 21.2: https://bugs.launchpad.net/cloud-init/+bug/1917875

At the moment we have pinned the Garden Linux build to an old version of cloud-init for Ali but the fix should make it into Debian for the benefit of the community.

**Why is this needed**:

Get rid of the special pinned version of cloud-init in Garden Linux.

**Comment by mbanck** [comment]
21.3 has been uploaded to unstable and hit testing on September 1st, and I verified that the patch mentioned in LP#1917875 is in there, so this should be fixed by now, closing
