### ISSUE TITLE
Clean up docs/ directory

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#338]
**What happened**:

The docs/ directory contains unstructured, and partly outdated information in german and english.

**What you expected to happen**:

Information that is still relevant updated and consistently presented in english. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by Vincinator** [comment]
While I think documentation requires active maintenance (in general), I also think that this issue is resolved. 

- No mix of German/English docs
- Restructuring
