### ISSUE TITLE
Update LICENSE file

### ISSUE THREAD

**Issue by disco-stu** [gardenlinux/gardenlinux#34]
The LICENSE file doesn't seem to be up to date:

> Copyright 2017 Tianon Gravi <tianon@debian.org>

**Comment by marwinski** [comment]
Well, yes it is not up-to-date but in a different way. The work in this repository is based on https://github.com/debuerreotype/debuerreotype so we need to include this license. The mentioning of the Garden Linux team is still missing.

**Comment by marwinski** [comment]
License has been updated and fixed quite some time ago.
