### ISSUE TITLE
Garden Linux fails to boot on VMware with with non-paravirtualized storage/SCSI

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#360]
**What happened**:

Booting the current Garden Linux on VMware only works with para-virtualized storage, not for fully virtualized storage (i.e. LSI Logic SCSI). The initrd image is missing the modules `mptspi`, `mptscsih` and `mptspi` (only `vmw_pvscsi` for paravirtualized SCSI is present).

```
$ ls -al ~/gardenlinux/.build/vmware-dev/20210915/amd64/bullseye/initrd-extracted/lib/modules/5.10.0-8-cloud-amd64/kernel/drivers/scsi

total 2068
-rw-r--r-- 1 glbuild users 106011 Sep 15 13:13 gdth.ko
-rw-r--r-- 1 glbuild users  45075 Sep 15 13:13 hv_storvsc.ko
-rw-r--r-- 1 glbuild users 287707 Sep 15 13:13 ipr.ko
-rw-r--r-- 1 glbuild users 137787 Sep 15 13:13 libiscsi.ko
-rw-r--r-- 1 glbuild users 229867 Sep 15 13:13 scsi_debug.ko
-rw-r--r-- 1 glbuild users 486955 Sep 15 13:13 scsi_mod.ko
-rw-r--r-- 1 glbuild users 133819 Sep 15 13:13 scsi_transport_fc.ko
-rw-r--r-- 1 glbuild users 264219 Sep 15 13:13 scsi_transport_iscsi.ko
-rw-r--r-- 1 glbuild users 128899 Sep 15 13:13 sd_mod.ko
-rw-r--r-- 1 glbuild users  73771 Sep 15 13:13 sg.ko
-rw-r--r-- 1 glbuild users  49811 Sep 15 13:13 sr_mod.ko
-rw-r--r-- 1 glbuild users  40163 Sep 15 13:13 virtio_scsi.ko
-rw-r--r-- 1 glbuild users  49819 Sep 15 13:13 vmw_pvscsi.ko
-rw-r--r-- 1 glbuild users  50051 Sep 15 13:13 xen-scsifront.ko
```

**What you expected to happen**:

Garden Linux boots successfully on WMware with fully virtualized SCSI.

**How to reproduce it (as minimally and precisely as possible)**:

Build Garden Linux with `make vmware-dev` and attempt to import the resulting `.vmdk` or `.ova` into VMware Player/Workstation/etc. and boot the VM. It will fail trying to mount the root partition.

**Comment by MrBatschner** [comment]
It seems that the kernel modules for the LSI SCSI adapters that VMware uses in a fully virtualized environment are not even part of the kernel package.

**Comment by marwinski** [comment]
@gehoern : can you build the next kernel with this module: mptspi. This might trigger mptscsih, mptbase and possibly others. Those are part of the non-cloud Debian kernel.

**Comment by MrBatschner** [comment]
Kernel needs to be built with `CONFIG_FUSION_SPI=m`.

**Comment by Vincinator** [comment]
Status Update: Looks relevant for our bare metal support for VMWare endeavour. Please correct me if I'm wrong @MrBatschner

**Comment by Vincinator** [comment]
Not relevant at the moment
