### ISSUE TITLE
Set session timeout for the shell

### ISSUE THREAD

**Issue by Kristian-ZH** [gardenlinux/gardenlinux#37]
**What would you like to be added**:
A secure practice is to set session timeout for the shell

**Why is this needed**:
Additional level of security

**Comment by marwinski** [comment]
Thanks, I have asked around and nobody objected. I will put it in.

**Comment by marwinski** [comment]
Fixed with https://github.com/gardenlinux/gardenlinux/commit/7c048bc78be48fd35f7d2712975502184dcc4142
