### ISSUE TITLE
Disable core dumps

### ISSUE THREAD

**Issue by Kristian-ZH** [gardenlinux/gardenlinux#38]
**What would you like to be added**:
 Set the following options in /etc/security/limits.conf:
* soft core 0
* hard core 0

**Why is this needed**:
In case of a crash the system writes a core dump to disk. These core dumps can contain critical
information that can help an attacker to prepare further attacks.

**Comment by philsbln** [comment]
I agree with ```soft core 0``` as writing core files by defaults poses a security risk.
I disagree with ```hard core 0``` as it makes debugging in development environments running garden linux unnecessary hard as it prevents processes from explicitly tuning on core dumps.

**Comment by marwinski** [comment]
Sorry for the delay. 

We enabled coredumps initially because we were chasing some nasty core dumps during the initial phase of development. I am not sure he above parameter represent the full picture as for example we have enabled systemd-coerdump (https://www.freedesktop.org/software/systemd/man/systemd-coredump.html) 

@gehoern what do you think? 

Also here, users should be able to enable this using the operating system extension.

**Comment by gyptazy** [comment]
## Overview
Let's have a short overview of the current status of core dumps in Garden Linux.

## Usage
Core dumps are activated by the `server` feature by installing (see also https://github.com/gardenlinux/gardenlinux/blob/main/features/server/pkg.include#L20) the `systemd-coredump` package. However, production releases will always be built with the flag `_prod` which excludes this package (see also https://github.com/gardenlinux/gardenlinux/blob/main/features/_prod/pkg.exclude#L1) and cleans up the override configs (see also: https://github.com/gardenlinux/gardenlinux/blob/main/features/_prod/file.exclude#L1-L2).

However, regarding the systemd docs it would fall back to default (haven't validated this one). As a result, we could just ship the legacy `sysctl` config as a droplet within the `_prod` feature.

## Summary
I'm not quite sure what @marwinski means with `users should be able to enable this using the operating system extension.`. But we could keep them for artifacts that are built without `_prod` flag and just ship the additional configs in `_prod`.

What do you think?
