### ISSUE TITLE
 Set a strict global umask value

### ISSUE THREAD

**Issue by Kristian-ZH** [gardenlinux/gardenlinux#39]
**What would you like to be added**:
umask value of `077` or minimum `027` 

**Why is this needed**:
The permissive value of `022` should not be used if possible.

**Comment by marwinski** [comment]
Fixed with https://github.com/gardenlinux/gardenlinux/commit/460ec2923000b4ca578b23f9745a773798959052

**Comment by 5kt** [comment]
The umask must be set to 077 and it should actually be set in the server feature, or better yet in base.
The test should be also be then moved to the proper feature.
