### ISSUE TITLE
Use new version AWS ENA driver in Garden Linux

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#397]
**What would you like to be added**:

The kernel used by Garden Linux shall receive a new version of the AWS ENA driver. The 5.10 LTS kernel apparently ships with AWS ENA driver 2.1.0. This version is slightly outdated as there was version 2.5.0 released on April 5th 2021. 2.1.0 was released in April 2019.

For the AWS ENA drivers see https://github.com/amzn/amzn-drivers

**Why is this needed**:

Stakeholders demand more up-to-date versions which provide additional features.

**Comment by waldiTM** [comment]
Is the version in Linux 5.15 (next LTS) new enough?

Because I see changes with DKMS, why is updating the driver in our kernel build not possible?

**Comment by waldiTM** [comment]
Yes, patch the sources and build it in-tree.

**Comment by Vincinator** [comment]
OK, actually I think **in-tree** is a good idea. Changed my mind.
- easier to integrate
- we do not have to care about an additional ena-dkms package
- no confusion if kernel comes with some other version of ena driver enabled.. 

If we need more up to date version than on Linux mainline/stable, we could also take sources from https://github.com/amzn/amzn-drivers to create a patch..

**Comment by Vincinator** [comment]
ENA Driver included in Linux Kernel and the ENA driver packaged as LKM ([available here](https://github.com/amzn/amzn-drivers)) have two separate code bases.

The version number of the ENA Driver included in Linux Kernel is not updated anymore.

See: https://github.com/amzn/amzn-drivers/issues/196

**Comment by Vincinator** [comment]
Closing issue. As briefly discussed, upstream ena version of linux 5.15 should be the target. 
Reopen this issue if needed.

Thanks
