### ISSUE TITLE
failed usr.mount 

### ISSUE THREAD

**Issue by ubi2go** [gardenlinux/gardenlinux#399]
**What happened**:
/usr/lib/dracut/modules.d/98gardenlinux# systemctl list-units --failed
  UNIT                     LOAD      ACTIVE SUB    DESCRIPTION
● sysroot-usr.mount        not-found failed failed sysroot-usr.mount
● sysroot-usr-fsck.service not-found failed failed sysroot-usr-fsck.service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
2 loaded units listed.

**What you expected to happen**:
no failed systemd services

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
usr.mount should be disabled if the usr directory is not on a seperate partition.

**Environment**:

**Comment by 5kt** [comment]
As we have switched back to fstab (#466) - this is no longer going to be an issue. Closing.
