### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#4]
Writing unit tests 

- Unit tests are tests that can be performed on the final image without really instantiating it!
- debian-cloud-images list https://salsa.debian.org/cloud-team/debian-cloud-images
-  hardening guide lines (as attached) and NO virus scanner ! NO BMC*! NO PRISMA!
[Linux Server Hardening Procedure_9b7aa66fee874fad875fdf4980522b61-060320-1724-1562.pdf](https://github.com/MalteJ/gardenlinux-manifest/files/4334614/Linux.Server.Hardening.Procedure_9b7aa66fee874fad875fdf4980522b61-060320-1724-1562.pdf)
[Container Host OS Hardening Proc_ac0e340adf014d35857f57731029c0d8-060320-1726-1564.pdf](https://github.com/MalteJ/gardenlinux-manifest/files/4334615/Container.Host.OS.Hardening.Proc_ac0e340adf014d35857f57731029c0d8-060320-1726-1564.pdf)
- no ssh keys
- tmp, proc, sys empty
- dev populated with "important" nod's
- machine-id is a file and is 0 size  and /var/lib/dbus/machine-id not exist
- no passwords
- size constrains
- no libdb
- license scan -> all compatible to SAP!
- protecode
- hardening tests (run tiger in chroot, chkrootkit in chroot, rkhunter in chroot)
- deborphan -an -> not explicit named libraries that are by accident in (apt-mark showmanual)
- debsums -> check integrity of all files on disk
- device file exist, especially console, fd, full, null, ptmx, pts, random, shm, stderr, stdin, stdout, tty, urandom, zero, ...
- make sure that autologin is not enabled for productive builds (make sure there is no autologin.conf file under /etc/systemd)

**Comment by 5kt** [comment]
@gehoern please provide some more information on what the size constraints should be.

**Comment by marwinski** [comment]
I just found an issue where not all files in /etc were owned by root (meaning a file that should have been owned by root was not). We need a test that checks that all files are owned by root (are there any exceptions?), group is root (with well known exceptions), have their respective file permissions and are not world writeable.
