### ISSUE TITLE
systemd.unified_cgroup_hierarchy=0 is not disable cgroup v2 support

### ISSUE THREAD

**Issue by ubi2go** [gardenlinux/gardenlinux#401]
**What happened**:

using the cloud feature with following config settings:
https://github.com/gardenlinux/gardenlinux/blob/ddb319b4ebef874764c3fc688d9f4856416472ed/features/cloud/file.include/etc/kernel/cmdline.d/80-cgroup.cfg

# Disable cgroup v2 support

CMDLINE_LINUX="$CMDLINE_LINUX systemd.unified_cgroup_hierarchy=0"

**What you expected to happen**:
expectation was that the cgroup v2 will be disabled, but i see following output on a test instance:

cat /proc/cmdline
BOOT_IMAGE=../Default/5.10.0-8-cloud-amd64/linux root=LABEL=ROOT ro console=ttyS0,115200 console=tty0 earlyprintk=ttyS0,115200 consoleblank=0 cgroup_enable=memory swapaccount=1 nvme_core.io_timeout=4294967295 **systemd.unified_cgroup_hierarchy=0** security=selinux initrd=../Default/5.10.0-8-cloud-amd64/initrd.img-5.10.0-8-cloud-amd64

systemd.unified_cgroup_hierarchy=0 is expected, but the following output reports something else:

cat /proc/filesystems | grep cgroup
nodev   cgroup
**nodev   cgroup2**

systemctl --version
systemd 247 (247.9-1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 **default-hierarchy=unified**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by marwinski** [comment]
This setting does not disable cgroupv2 on kernel level. We have introduced this setting as it causes Docker to use cgroupv1. This has already been problematic as we want to use new cgroupv2 features, however Kubernetes <= 1.18 does not work with cgroupv2. We would like to have something more configurable to go forward (e.g. something that we configure after the machine has been started).

**Comment by ubi2go** [comment]
Thank you for the explanation!

**Comment by gyptazy** [comment]
Hey @ubi2go,

I assume that based on @marwinski explanation regarding your request and your answer we may close this issue.
If there's still something left feel free to reopen this one again.

Thanks,
gyptazy
