### ISSUE TITLE
features/README.md is empty

### ISSUE THREAD

**Issue by mbanck** [gardenlinux/gardenlinux#404]
There is a `README.md` file in the `features` directory, but it is empty.

Maybe the content of `features/example/Readme.md` could be moved to it as a start, but documenting the interface
(when/how `exec.*` fires/run, how `files.include` works etc.) in more detail is required.

**Comment by nanory** [comment]
As discussed with @gehoern, he will upload its current draft of the features documentation.

**Comment by Vincinator** [comment]
I was browsing through the issues, and I think @dnan0s you solved this, right?
