### ISSUE TITLE
Flags Garden Linux should issue in various situations

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#408]
fips active mode enabled
needs upgrade
needs restarts
needs reboot
attestation possible (tpm)
secure booted

**Comment by gyptazy** [comment]
Hey @gehoern,

please, can you explain what is meant with this issue?

Thanks,
gyptazy

**Comment by gyptazy** [comment]
Hey @gehoern,

I'm closing this one, if you think we still need this - feel free to reopen with some more details.

Thanks,
gyptazy
