### ISSUE TITLE
upgrade the documentation about the testframework

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#456]
there is a 3 level test framework

- unit tests
- integration tests
- conformance tests

that need to be proper documented

**Comment by gyptazy** [comment]
Hey @gehoern,

I think this is already covered by https://github.com/gardenlinux/gardenlinux/tree/main/tests#readme. Especially by the "workflow chart" in https://github.com/gardenlinux/gardenlinux/tree/main/tests#chart. If you're still missing something, please let me know to cover them, too.

Thanks,
gyptazy
