### ISSUE TITLE
awscli missing in aws

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#465]
shouldn't there be an awscli in the aws image

**Comment by Vincinator** [comment]
@gehoern is awscli really needed in GardenLinux aws image?
After briefly looking awscli up, wouldn't you use the awscli to manage aws services from your developer workstation?

**Comment by MrBatschner** [comment]
I second @Vincinator 's oppinion. We would have to integrate the *-cli tools for all the other cloud-providers as well into their features to be consistent. 
`awscli` is only required to interact with the AWS API which is not required for an OS image that is meant to be slim. If anyone would need `awscli` on Gardenlinux, spinning up a container with it should be preferred.

**Comment by marwinski** [comment]
I would like to add that we did not have a single request for this.
