### ISSUE TITLE
make packages doesn't work if UID != 1000

### ISSUE THREAD

**Issue by nkraetzschmar** [gardenlinux/gardenlinux#492]
**What happened**:

make packages fails if run with any user id other than 1000, outputing the following error:

```
Now signing changes and any dsc files...
 signfile dsc apt_2.3.11gardenlinux1.dsc Garden Linux Maintainers <contact@gardenlinux.io>
gpg: error running '/usr/bin/gpg-agent': exit status 2
gpg: failed to start agent '/usr/bin/gpg-agent': General error
gpg: can't connect to the agent: General error
gpg: keydb_search failed: No agent running
gpg: skipped "Garden Linux Maintainers <contact@gardenlinux.io>": No agent running
gpg: /tmp/debsign.JrRYVx6S/apt_2.3.11gardenlinux1.dsc: clear-sign failed: No agent running
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1112:
running debsign failed
```

**What you expected to happen**:

package build should work as any user

**How to reproduce it (as minimally and precisely as possible)**:

run `make` inside the packages folder as any user with UID != 1000

**Anything else we need to know**:

- origin of this error is that package build mounts `$(gpgconf --list-dir agent-socket)` [[packages/Makefile:33](https://github.com/gardenlinux/gardenlinux/blob/052b1c78/packages/Makefile#L33)]
- this file is owned by the current user, but the build process inside the docker container is run as dev with UID 1000
  &rArr; if current UID isn't 1000 then dev does not have access permissions to it

**Workaround**:

For now running
```shell
chmod a+rw "$(gpgconf --list-dir agent-socket)"
```
prior to running make, so before entering the container, gets around the problem, but that's probably not a good long term fix 😅

**Comment by nanory** [comment]
The builds of the [packages directory](https://github.com/gardenlinux/gardenlinux/tree/main/packages) will sooner or later be replaced by the newly created package repositories and pipelines which can be found [here](https://gitlab.com/gardenlinux). 

It is important to note that the package build has been decoupled from the Garden Linux build itself and has been moved to dedicated repositories, so there is no need to keep them in this repository anymore. As a result, the mentioned bug should be fixed once the deprecated package build pipeline and its directory has been removed.

As of now, it is planned to verify the newly created package build pipelines until next week. If there are no major concerns, we may be able to remove the packages direcotry from this repo and get rid of the mentioned bug. 

I will keep you updated on this topic.

**Comment by nanory** [comment]
Once PR https://github.com/gardenlinux/gardenlinux/pull/600 has been merged, we can close this ticket. Then, package isn't a part of this repo anymore.
