### ISSUE TITLE
Ensure no sensitive content is present in images

### ISSUE THREAD

**Issue by 5kt** [gardenlinux/gardenlinux#513]
Unencrypted password safes, like .netrc, must not be in the image.

We currently test for this with tiger https://github.com/gardenlinux/gardenlinux/blob/1c78507b03d6cab9ec075878f07aa11c0c229068/features/base/test/tiger.d/tigerrc#L9 but we need to make sure everything is properly covered with this test.

**Comment by florianpaulhoberg** [comment]
Hi @5kt ,
IMHO this sounds like a valid task but the subject is quite misleading in this case. As you already mentioned before, this is already done for *.netrc* files by *Tiger*. While *Tiger* already validates this by looping through all home directories and checking every present .netrc file for credentials, we must ensure an equal process for all other possibilities where passwords are used.

I think this results in:
 * Validating where passwords/secrets are used (relates all sensitive content)
 * Avoiding the usage of them (maybe there're other approaches possible)
 * Ensuring to have them absent
 * Writing *Tiger* test files

Maybe I'm missing something more - feel free to add additional points. Let me know your opinion.

Thanks,
Florian

**Comment by marwinski** [comment]
Well, adding to this we should look for files that contain strings/data with high entropy. Sure, we will have to mask some false positives but this should provide another safety net in case the other tests don't catch it.

**Comment by florianpaulhoberg** [comment]
Ok, so are you all fine with this DoD?

 * Inspecting where sensitive content is used/integrated
 * Looking for solutions to avoid the further usage of them (if possible)
 * Ensuring to have them absent in images
 * Creating *Tiger* files for pipeline integration tests

Maybe we should rename this issue to **Ensure no sensitive content is present in images**?

Are you fine with this @5kt @marwinski?

**Comment by marwinski** [comment]
Fine with me to rename to **Ensure no sensitive content is present in images**
