### ISSUE TITLE
It takes about 20 mins for Gardenlinux to be booted on Alicloud

### ISSUE THREAD

**Issue by jia-jerry** [gardenlinux/gardenlinux#53]
**What happened**:
It takes about 20 mins for Gardenlinux to be booted on Alicloud
**What you expected to happen**:
It takes less than 1 min for Gardenlinux to be booted on Alicloud
**How to reproduce it (as minimally and precisely as possible)**:
Use master branch
**Anything else we need to know**:
Alicloud found it is stuck in step `initialize debian`. They suggested we follow the steps in this [doc](https://www.alibabacloud.com/help/doc-detail/48226.htm?spm=a2c63.p38356.b99.203.5f7a751eVcTS1f) to build a customized image. I'm not sure virtio is complied with[ what Alicloud suggested](https://www.alibabacloud.com/help/doc-detail/62423.htm?spm=a2c63.p38356.879954.8.7ac11541cVs3Nd#concept-dvq-cqs-xdb). 
**Environment**: Alicloud

**Comment by gehoern** [comment]
i guess the problem is that garden linux generates the ssh keys on first boot. Other clouds like google or aws virtualize a random number generator and we from garden linux pick it. but we have to investigate what is the situation on alicloud. Do you see the behaviour as well on second boot?

**Comment by jia-jerry** [comment]
@gehoern , you guess is right. Here is the reply from the support that it stuck in `ssh-keygen -A `.
1. When I reboot, the boot time is quite short.
2. I also created an images based on this booted machine, then I created a VM based on this image, it is quick. But still, cloud init failed and no public key is written.

**Comment by marwinski** [comment]
ssh-keygen is definitely not a problem - it takes less than 1 second. It takes about 18 minutes from launching the VM to the first kernel message.

**Comment by vlerenc** [comment]
When I saw @gehoern 's statement, it reminded me about `/dev/random` vs `/dev/urandom` (https://www.2uo.de/myths-about-urandom). If it's not `ssh-keygen`, maybe something else involving (blocking) randomness that can be changed? If not, you guys will know best how to find the code that holds off the boot process, so that is probably no helpful comment, but I wanted to make it, since I recall similar hold-offs due to blocking `/dev/random` calls.

**Comment by marwinski** [comment]
It has nothing to do with /dev/random (which indeed is a likely cause). I have asked Jerry to open a ticket with Ali and have them explain what takes 18 minutes until they start launching the image. I suspect something in the way we convert to qcow2!?

**Comment by jia-jerry** [comment]
I also tested with Raw file. It didn't work well also. It is not image format issue.

**Comment by marwinski** [comment]
maybe some properties in the disk image / image ?

**Comment by jia-jerry** [comment]
No Idea. I will check with Alicloud again. Stay tuned.

**Comment by jia-jerry** [comment]
I happened to solve this issue.

When we make a customized image for Alicloud, we have an option to set Linux OS type. Originally, we set it `Debian`, then we failed to boot the machine.

I tried with `OtherLinux`(Actually, I tried all available types), it succeeded..

**Comment by marwinski** [comment]
excellent, thanks.  I will merge Monday's changes into the main branch. If everything else is ok we can build 27.1

**Comment by vlerenc** [comment]
Thanks also from me @jia-jerry . :-)

**Comment by marwinski** [comment]
Did they provide further details? We completely overwrite the ssh configuration based on security recommendations (that from my point of view do make sense). `dpkg-reconfigure` would probably reset that.
