### ISSUE TITLE
Move applicable contents of google-compute-engine package

### ISSUE THREAD

**Issue by waldiTM** [gardenlinux/gardenlinux#549]
The GCP images contain one special Google maintained package `google-compute-engine` that does not contain any services but a part of the image config. No other platform does something similar.

We should do away with that, to avoid having vastly different settings between vendors.

**Comment by nanory** [comment]
Ok, this means we need to take a look into the configuration files that are delivered by this package and check what files are required and place them in the `features/gcp/files.include` directory then. 

I will have a look at this.

**Comment by nanory** [comment]
Ok, so I took a look into the sources of the `google-compute-engine` package  (version 20211116.00) and it seems that the following files must be added to the `features/gcp/files.include` directory:
```
.
├── etc
│   ├── apt
│   │   └── apt.conf.d
│   │       ├── 01autoremove-gce
│   │       └── 99ipv4-only
│   ├── dhcp
│   │   └── dhclient.d
│   │       └── google_hostname.sh
│   ├── dracut.conf.d
│   │   └── gce.conf
│   ├── modprobe.d
│   │   └── gce-blacklist.conf
│   ├── rsyslog.d
│   │   └── 90-google.conf
│   └── sysctl.d
│       └── 60-gce-network-security.conf
├── lib
│   └── udev
│       ├── google_nvme_id
│       └── rules.d
│           ├── 64-gce-disk-removal.rules
│           └── 65-gce-disk-naming.rules
└── usr
    └── bin
        ├── google_optimize_local_ssd
        ├── google_set_hostname
        └── google_set_multiqueue
```
There is also a `sbin/google-dhclient-script` file but according to the Debian source package, this file isn't installed, so I think we can skip this.

Moreover, there should also be a symlink between `usr/bin/google_set_hostname` and `etc/dhcp/dhclient-exit-hooks.d/google_set_hostname`.

Do we have a possibility to realize this via file.include @waldiTM ?

**Comment by nanory** [comment]
Ah nevermind, I see. I can use exec.config for this.
