### ISSUE TITLE
Update the kernel ABI when the kernel version changes

### ISSUE THREAD

**Issue by robbycochran** [gardenlinux/gardenlinux#564]
**What would you like to be added**:
Update the `KERNEL_ABI` value for the Linux kernels in the Garden Linux build process when the kernel version changes from the previous release.

**Why is this needed**:
When building kernel modules for Garden Linux, we have relied on the [kernel abi](https://wiki.debian.org/DebianKernelABIChanges) number stamped in the Garden Linux kernel image to determine when there have been kernel ABI changes. This value is commonly read with the `uname -r` command. However, on the most recent release (576.1), the kernel version was changed from `5.10.70-1gardenlinux1` to `5.10.83-1gardenlinux1` while the kernel ABI stayed the same `5.10.0-9-cloud-amd64`. 

Does the Garden Linux team plan to follow Debian kernel ABI versioning practices? As a workaround, we can rely on the kernel version itself (`uname -v`), but the kernel ABI not changing may cause issues for other users of Garden Linux.

**Comment by Vincinator** [comment]
Hi, 
our linux-image package names include the full version of the kernel on newer releases. (latest is `576.7`). 
`uname -r` returns the full version (e.g. `5.10.103-garden-amd64`) as well.

Thanks for reaching out, and sorry for the late response.
