### ISSUE TITLE
Improve the build requirements chapter in the README file

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#593]
**What would you like to be added**:
We noticed that the `Build Requirements` chapter in the README (see: https://github.com/gardenlinux/gardenlinux/blob/6d1223a03031684b0bd6ed05d3f07921ee393e46/README.md?plain=1#L51) may need some minor adjustments which would help to mitigate misunderstandings.

For example, the memory requirement of +2 GiB only applies to builds that uses the `--lessram` parameter. This should be clarified.
In addition, the README should mention that once a developer wants to install tekton via pip, he must ensure to install pip before by executing `apt install python-pip`

**Why is this needed**:
Improve documentation

**Comment by florianpaulhoberg** [comment]
Hi @nanory.

thanks for your hint. Your request is covered by PR https://github.com/gardenlinux/gardenlinux/pull/597.

Thanks,
Florian

**Comment by florianpaulhoberg** [comment]
This is merged, now.
