### ISSUE TITLE
Pipeline Buildout

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#6]
- [/] choose build server and build system
  - see https://github.com/gardenlinux/gardenlinux/tree/master/ci
  - I suggest using TektonCD / run on Gardener-CICD infrastructure
- [/] sync with the team about running grub-install, and losetup on build server
  - done.. use privileged container..
- integration in webpage
- target repo for image
  - using S3 bucket for now
- release process
- example https://alpha.release.core-os.net/amd64-usr/current/
- populate https://repo.gardenlinux.io/
- naming and version schema

**Comment by ccwienk** [comment]
@gehoern : since we by now have a _somewhat_ working cicd and release pipeline, how about closing this ticket, and creating new tickets for the remaining open topics?

**Comment by ccwienk** [comment]
@gehoern : I will close the ticket. There are still some (known) TODOs for the pipeline. However, we do have a working pipeline as of now, and software somehow tends to never really be "finished", does it not? :-)
