### ISSUE TITLE
/var/log/apt/eipp.log.xz exists

### ISSUE THREAD

**Issue by zobelhelas** [gardenlinux/gardenlinux#626]
**What happened**:
The logfile of the “External Installation Planner Protocol” (/var/log/apt/eipp.log.xz) exists in `/var/log/apt/`

**What you expected to happen**:
`/var/log/apt/` being empty

**How to reproduce it (as minimally and precisely as possible)**:
make kvm

**Anything else we need to know**:
https://unix.stackexchange.com/questions/431782/what-is-the-eipp-log-xz-file

**Environment**:

**Comment by chrinorse** [comment]
Can't reproduce. After build the kvm image, I mounted the root partition as loop back device and checked /var/log/apt, the directory is empty.

**Comment by chrinorse** [comment]
Turns out, the file is in the tar.xz archive but not in the raw image.
