### ISSUE TITLE
Complete FedRAMP feature

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#648]
**What would you like to be added**:
As of now, there is already a [FedRAMP feature](https://github.com/gardenlinux/gardenlinux/tree/main/features/fedramp) but it hasn't been completed yet. It already contains a test, that we would like to integrate in the Garden Linux build.

However, it is important that this test script is executed in the target image (rootfs) instead of executing it on the build system (container). Thereby, the script should be modified as little as possible.

Moreover, the Garden Linux image must probably be adjusted in order to fulfill the FedRAMP test. Therefore, this feature also includes adjustments made to the Garden Linux image, that enables it to fulfill the test.

**Why is this needed**:
This is needed to complete the roadmap goal "Testcases"

**Comment by zobelhelas** [comment]
When trying to complete this feature, one question arises for me:

One check is trying to ensure that we have "PermitEmptyPasswords" explicitly set to "No" in `/etc/ssh/sshd_config`. This value is default, so setting it woul theoretically not neccessary. But to make this check pass, we need to set it explicitly.

Instead of shipping an own sshd_config in the fedramp feature, i wonder if I may add this config value to the existing sshd_config file in the `server` feature, which is included in all other features anyway.

@gehoern, maybe you could comment on this?

**Comment by zobelhelas** [comment]
- [ ] clamav: no default cronjob for clamav from Debian packages
- [ ] limits: default libpam-modules does not have a maxlogin set by default; fedramp specific setting not known
- [ ] aide: no faillog in default aide configuration
- [ ] aide: cronjob via cron.daily/aide
- [ ] chrony: Referenced NTP Server IP is default internal AWS server, not available on all plattforms

**Comment by gyptazy** [comment]
Hey @gehoern,

how shall we proceed with the last two action points (under the aspect that the test script may not be touched):

**krb5_principal**
Validating for a string beginning with `krb5_principal` in `/etc/audit/auditd.conf`. This is the principal for this server. The default is "auditd". Given this default, the server will look for a key named like `auditd/hostname@EXAMPLE.COM` which isn't used in Garden Linux at all.
Check: https://github.com/gardenlinux/gardenlinux/blob/main/features/fedramp/test/test.sh#L80
Doc: https://linux.die.net/man/5/auditd.conf

**chrony NTP Server**
The `fedramp` feature will replace `systems-timesyncd` with `chrony`. The given test script validates for a NTP resource that in only accessible within the `AWS` infrastructure. According to this, the script must be changed (if it may be changed in any way).
Check: https://github.com/gardenlinux/gardenlinux/blob/main/features/fedramp/test/test.sh#L65

**app-armor**
The `fedramp` feature will replace `SELinux` with `AppArmor` in enforcing mode, now. Just as a side note; no action needed.

fyi: @Vincinator @nanory @zobelhelas

**Comment by gyptazy** [comment]
Finalizing this issue results in rebuilding `clamav` with `OpenSSL3` support (task: https://github.com/gardenlinux/gardenlinux/issues/909). Afterwards, the PR must be switched to `pkg.include` instead of using `exec.config`.
