### ISSUE TITLE
CONFIG_DEBUG_INFO_BTF is disabled in 576.3

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#649]
**What happened**:

We have introduced `CONFIG_DEBUG_INFO_BTF` with 576 and it was enabled up to 576.2 but is disabled in 576.3.

**What you expected to happen**:

Have `CONFIG_DEBUG_INFO_BTF` set to `y`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

@MrBatschner please add an integration test for this. A unit test might work as well (`/boot/config...`)

**Environment**:

**Comment by marwinski** [comment]
I don't know. I did trust the kernel without asking too many questions...

**Comment by waldiTM** [comment]
This will be fixed by https://salsa.debian.org/kernel-team/linux/-/merge_requests/449

**Comment by Vincinator** [comment]
solved in 576.4
