### ISSUE TITLE
Ability to customize dracut modules.

### ISSUE THREAD

**Issue by milvich-anvil** [gardenlinux/gardenlinux#659]
**What would you like to be added**:

A way for features to indicate additional dracut modules.

**Why is this needed**:

The `bin/makepart` script is currently using dracut to build the initrd with a hardcoded list of modules. This prevents a feature from being able to add their own module or to customize the initrd in any way.

If a feature needs to modify the early boot process such as implementing alternative file systems, netboot, encrypted volumes, etc... there is no way for the feature to include these items in the dracut build.

A potential solution would be to allow features to specify additional modules (in the `info.yaml` file) that can be included in the list of modules `bin/makepart` passes to dracut.

**Comment by 5kt** [comment]
This can be achieved by using the specific feature's _file.include_ and providing a config file for dracut under _/etc/dracut.conf.d_ in order to add a dracut module.
```
add_dracutmodules+=" exampleModule "
```
The _exampleModule_ dracut module will then get added to the initrd.
