### ISSUE TITLE
Use OS GardenLinux extension to provison OS on alicloud

### ISSUE THREAD

**Issue by jia-jerry** [gardenlinux/gardenlinux#67]
**What would you like to be added**:
In Alicloud, [CCM](https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/docs/getting-started.md) needs boot args provider-id for kubelet. It is maintained in [gardener-extension-provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/pkg/webhook/controlplane/ensurer.go#L120), which is based on assumption env `PROVIDER_ID` is provided by the system. [gardener-extension-os-coreos-alicloud](https://github.com/gardener/gardener-extension-os-coreos-alicloud/blob/master/pkg/coreos-alicloud/internal/templates/cloud-init.sh.template#L43) is responsible to provide correct value of  env `PROVIDER_ID` .

I would suggest provide env `PROVIDER_ID` built in image level.
**Why is this needed**:
We will not need a special extension as  [gardener-extension-os-coreos-alicloud](https://github.com/gardener/gardener-extension-os-coreos-alicloud). We will use a common [gardener-extension-os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux) for Alicloud.

**Comment by marwinski** [comment]
I don't understand. Should this be an environment variable or kernel parameter? What value should it be set to?

**Comment by jia-jerry** [comment]
It is an environment variable. The value should be {region_id}.{instance_id}, which could be fetched from meta-data service(100.100.100.200)

**Comment by vpnachev** [comment]
You can inject a short code that retrieves the instance id from the metadata service in the kubelet service. Just see how something similar is done for GCP https://github.com/gardener/gardener-extension-provider-gcp/blob/bf6f2bd2305e88b5de29ecc17e7e79afdedde0b9/pkg/webhook/controlplane/ensurer.go#L352

**Comment by jia-jerry** [comment]
> You can inject a short code that retrieves the instance id from the metadata service in the kubelet service. Just see how something similar is done for GCP https://github.com/gardener/gardener-extension-provider-gcp/blob/bf6f2bd2305e88b5de29ecc17e7e79afdedde0b9/pkg/webhook/controlplane/ensurer.go#L352

It is a nice solution. Better than hack in the image. Will do it!
