### ISSUE TITLE
Unable to use networking with QEMU hostfwd on kvm-dev when dm-verity is active

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#677]
**What happened**:
Networking with QEMU in hostfwd mode does not work with *kvm(-dev)* images when feature *dm-verity* is active.

**What you expected to happen**:
Networking should work in every way.

**How to reproduce it (as minimally and precisely as possible)**:
Just create a shiny new fresh image of *kvm-dev* from current *main* branch.
Afterwards, start the image by the shipped tool *start-vm* that starts the image with *hostfwd* option. Within the guest the networking isn't working.

**Anything else we need to know**:
Disable the feature *_fstab_verity* from *kvm* and recreate an image. Afterwards, this works again.

A functional networking will be needed to solve:
https://github.com/gardenlinux/gardenlinux/issues/647
https://github.com/gardenlinux/gardenlinux/issues/648

The current implementation of *verity* seems to be still very buggy and blocks us in several ways - especially for the *kvm* images. Therefore, we should temporary deactivate this and reimplement this later. I'll add a PR in the evening.

**Comment by zobelhelas** [comment]
Freshly build and booted image shows:

```
root@localhost:~# networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP    
  1 lo     loopback carrier     unmanaged
  2 enp0s5 ether    off         failed   

2 links listed.
```

**Comment by gyptazy** [comment]
@zobelhelas thanks for confirming. After patching it works again:
```
root@localhost:~# ifconfig 
ens6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::67:2ff:fed8:94ac  prefixlen 64  scopeid 0x20<link>
        inet6 fec0::67:2ff:fed8:94ac  prefixlen 64  scopeid 0x40<site>
        ether 02:67:02:d8:94:ac  txqueuelen 1000  (Ethernet)
        RX packets 9  bytes 1369 (1.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32  bytes 2986 (2.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@localhost:~# networkctl
IDX LINK TYPE     OPERATIONAL SETUP     
  1 lo   loopback carrier     unmanaged
  2 ens6 ether    routable    configured

2 links listed.
```

I'll attach the PR within a few minutes.
