### ISSUE TITLE
Integrate verity feature (readonly filesystem)

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#679]
**What would you like to be added**:
This feature needs to be reintegrated since it got removed with https://github.com/gardenlinux/gardenlinux/issues/677 (PR: https://github.com/gardenlinux/gardenlinux/pull/678). It got temporary removed because the current integration was very buggy and caused several problems and made the *kvm-dev* image more or less useless. Within the next iteration of integration we need to make sure to have this fully working before activating again. This implies we need to identify and cover all files that could be changed later and to handle the *overlayfs* correctly.

**Notes**:
This was already temporary integrated but caused trouble during the integration of other features. As a result, this got temporary removed again. Furthermore, the reintegration should cover a useful integration for *kvm-dev* images in way, that you may use debug tools.

Related:
https://github.com/gardenlinux/gardenlinux/issues/677
https://github.com/gardenlinux/gardenlinux/issues/613

**Comment by gehoern** [comment]
just side notes:
- dm-verity key must be integrated with secure boot @nkraetzschmar  and the new boot concept of systemd @5kt
- there was a problem with the overlay fs -> please take a look in the _pxe feature because there is also an overlayfs used, you can probably recycle stuff @5kt
