### ISSUE TITLE
Capability test for /usr/bin/ping faulty

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#687]
**What happened**:
Execution of capability test for */usr/bin/ping* is faulty and results in a failure:
https://github.com/gardenlinux/gardenlinux/runs/5423121255?check_suite_focus=true#step:4:4793
```
test capabilities is enabled by the following features: server base 
testing for needed capabilities
FAIL - capabilities don't match
       expected: /usr/bin/ping cap_net_raw=ep
       got     : 
failed
```

**What you expected to happen**:
The test should be fine.

**Anything else we need to know**:
Actually, this is defined and ok for the image itself. This can be validated by booting the image:
```
root@localhost:~# uname -a && getcap /usr/bin/ping
Linux localhost 5.10.102-garden-cloud-amd64 #1 SMP Debian 5.10.102-0gardenlinux2 (2022-02-24) x86_64 GNU/Linux
/usr/bin/ping cap_net_raw=ep
```

This issue is raised when the *chroot* is copied to a new image where the capabilities got lost. However, I think we should test this within a booted image instead of the currently used *chroot*.

This could be solved by using the following solution: https://github.com/gardenlinux/gardenlinux/issues/682.

My proposal to proceed on this:
 * Remove checks for capability with #682
 * Merge #684
 * Integrate new *startvm* check within this issue #687

**Comment by marwinski** [comment]
This is being tested for quite some time in https://github.com/gardenlinux/gardenlinux/blob/main/tests/integration/test_gardenlinux.py#L212. How could this go wrong?

**Comment by marwinski** [comment]
Well, the tests tests from within a running image. If unset the test will fail.

**Comment by gyptazy** [comment]
Ok, my fault. I could find the the issue in handling the tar ball without *xattrs* (including the security capabilities).
