### ISSUE TITLE
SAP Owned Debian Repo

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#7]
- standard debian mirror
- our files (e.g. new pakages for libdb - less builds) on top
- recreated debian index files with our files integrated
- in fact: standard mirror blended with our files :-D
- include full debian set stable, testing, unstable 
- and probably other sources (e.g. frr, docker)

**Comment by liorokman** [comment]
Take a look at the `reprepro` tools ( https://wiki.debian.org/DebianRepository/SetupWithReprepro ).

It allows setting up a Debian repository that is fed by multiple sources (upstream repositories like the Debian base) and overrides or adds specific packages that don't exist upstream.

**Comment by gehoern** [comment]
yes we should go for reprepro but in a container (look in hack/docker-compose.yaml)

- make it to use a custom signature
- implement a whole workflow for running this (incomming -> publish -> delete)
- have multiple repos (either with one instance (preferred) or multiple instances -> security, default, sources)

**Comment by lhw** [comment]
I think https://www.aptly.info/ is also a very popular choice for this kind of setup.
