### ISSUE TITLE
Requirements.txt for integration_tests

### ISSUE THREAD

**Issue by dnan0s** [gardenlinux/gardenlinux#713]
**What would you like to be added**:

a requirements.txt for pytest inside `/integration_tests`
**Why is this needed**:

as a new user to pytest i installed pytest by `pip3 install pytest`, which brought me a non functioning pytest. I suppose, other users might also run into this issue. I think, Installing the right working versions is a good idea, so a requirements.txt with versions might benefit this issue.

**Comment by Vincinator** [comment]
While I agree, I think the `integration_tests` folder is pipeline specific. 
I would recommend to use `tests/` for a non-pipeline user.

**Comment by gyptazy** [comment]
As @Vincinator already said the recommended `integration_tests` are located in `tests/` for non pipeline usage. Please find the README.md (https://github.com/gardenlinux/gardenlinux/blob/main/tests/README.md) that describes further usage.

Short: A dedicated Docker container will be created and everything runs inside this container. All needed dependencies are fulfilled within this container. There're two new platforms (`KVM` and `CHROOT`) to run tests locally without any further requirements regarding cloud providers. If you need any assistance, feel free to ask (and we may improve the docs).
