### ISSUE TITLE
introduce an "unsupported" flag

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#72]
there should be a constant monitoring of the state of garden linux and its primary use case: to run kubernetes with gardener.
so e.g. if there are states (e.g. loaded nfsd module) that are problematic, we need to flag whole gardenlinux state as "unsupported" so people know they have to change their way to use garden linux

this is needed to raise the general security level of the whole setup.

what do we need to monitor (plz extend)
- unwanted kernel modules
- outdated image use

**Comment by vlerenc** [comment]
Why would we consider it "unsupported"? Key stakeholders of ours that are using for instance `nfsd` wouldn't understand/accept that. Then they wouldn't use it and we would be back at square one.

But let's entertain the idea for a moment nonetheless. It may make sense to do it similar like for instance the NodeProblemDetector (daemon set) does it. It adds conditions to the node resources that can be evaluated then from the outside, be it the dashboard or the monitoring.

**Comment by marwinski** [comment]
Well, nfsd is really not a good idea and there are even better user space solutions available: https://github.com/nfs-ganesha/nfs-ganesha/wiki

It might be more problematic where no "proper" solution is available. nfsd is not it.

**Comment by gehoern** [comment]
nfs is a very good example! the customer using this delivers its own user space utilitis not checking for any of our kernel interfaces and now since 5.x kernels you have the problem: if you load a module with docker the module is loaded in a namespace and nfs is not yet supporting this - it crashes the kernel while doing this. so customer complain anyhow. atm we fix this by preloading nfsd and increase our attack surface (found in pentest) much more elegant would be: kernel has loaded nfsd -> this is unsupported flagged red = customer has the choice to fix this. And i guess there are more examples like this. If we allow to load modules via --privileged this is a security "full loss". i think it is our resposibility to help our customers to make it right (not to forbid and prohibit).

**Comment by marwinski** [comment]
I am lost. This discussion now open for more than 1 year without update. There is now a similar issue #303 with a solution proposal to configure this via the shoot manifest.

As this is a bigger discussion I'd propose to establish an enhancement proposal process similar to https://github.com/gardener/gardener/blob/master/docs/proposals/README.md. We won't be able to capture this in several distributed and inconsistent tickets.

**Comment by gehoern** [comment]
i agree with the comments above and Gardenlinux evolved:
- we have proper maintained kernels 
  - all modules work as we know
  - we have reduced the amount of modules in kernels even further
- also the gardenlinux "contract" evolved: if the package is in the gardenlinux repo it is supported, if you download packages from somewhere else e.g. debian you are on your own "unsupported"
