### ISSUE TITLE
Mutual Exclusive Features

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#739]
**What would you like to be added**:
Mutual exclusive features. 
Currently we explicitly specify combination of features that work well together in the makefile targets. 

**Why is this needed**:
A build safeguard for users and pipelines to avoid creation of illegal/faulty feature combinations if `build.sh` is used manually or a new makefile target is proposed.

**Comment by gyptazy** [comment]
Hi @Vincinator,

great idea and I think this is urgently needed to make sure we do not build faulty artifacts with specific combinations of features. As already discussed, I think we already have a proper idea how to solve this.

If you wish, I could proceed with this after finishing the CIS integration tests.
