### ISSUE TITLE
Documentation Request: Garden Linux Repos

### ISSUE THREAD

**Issue by dnan0s** [gardenlinux/gardenlinux#740]
**What would you like to be added**:

A Documentation for Garden Linux Repositories is missing. 

Also, write about special Packages, for example the difference of
        
        # apt-cache search linux-image-5.10
        ...
        linux-image-5.10.109-garden-amd64 - Linux 5.10 for 64-bit PCs (signed)
        linux-image-5.10.109-garden-amd64-unsigned - Linux 5.10 for 64-bit PCs
        linux-image-5.10.109-garden-cloud-amd64 - Linux 5.10 for x86-64 cloud (signed)
        linux-image-5.10.109-garden-cloud-amd64-unsigned - Linux 5.10 for x86-64 cloud
        ...

**Comment by Vincinator** [comment]
Yes, good point. 

- The `dev` distribution contains always the latest packages build via the gitlab pipelines
- Additionally, a gardenlinux epoch distribution will be published on repo.gardenlinux.io every day
    - containing the packages for that day
    - for example the gardenlinux epoch 576: `deb http://repo.gardenlinux.io 576 main`. 
    - Gardenlinux epoch is the number of days since first gardenlinux release 
- the repository contains own packages, and a selected set of packages mirrored from debian testing
    - garden packages are being built in our gitlab pipelines
 - 576 is an exception, it still uses some local package builds. More recent versions of gardenlinux (e.g. current main branch) pull packages from the repo.gardenlinux.io apt repository during build time
 - For the linux kernel we use the full version in the package name
     - currently we keep old packages in `dev` dist, and I think we are keeping it that way for now. 


**With regards to the example:**
The cloud kernel has an optimised set of kernel configs https://salsa.debian.org/kernel-team/linux/-/blob/master/debian/config/config.cloud

I don't know a use for the unsigned images 🤔

**Comment by gyptazy** [comment]
Solved by PR #753. Further adjustments regarding the docs will be integrated by PR #1377.
