### ISSUE TITLE
Check integration tests, some are constantly failing

### ISSUE THREAD

**Issue by chrinorse** [gardenlinux/gardenlinux#757]
**What happened**:
Some integration tests in tests/integration/test_gardenlinux.py are constantly failing.
```
FAILED integration/test_gardenlinux.py::test_ntp - AssertionError: no error="...
FAILED integration/test_gardenlinux.py::test_metadata_connection_non_az_non_ali
FAILED integration/test_gardenlinux.py::test_loadavg - AssertionError: Expect...
FAILED integration/test_gardenlinux.py::test_systemctl_no_failed_units - json...
FAILED integration/test_gardenlinux.py::test_startup_time - AssertionError: n...
FAILED integration/test_gardenlinux.py::test_docker - AssertionError: no erro...
FAILED integration/test_gardenlinux.py::test_apparmor - AssertionError: no er...
```
**What you expected to happen**:
That the tests pass or are skipped.
**How to reproduce it (as minimally and precisely as possible)**:
Run the integration tests.
**Anything else we need to know**:

**Environment**:
Edit: Happens in the chroot and kvm integration test environment.

**Comment by MrBatschner** [comment]
Do they? I was running the tests just yesterday on all the Cloud providers and they come out fine. Can you try reproduce the tests with build that originated from the `rel-576` branch?

**Comment by chrinorse** [comment]
Okay, I should have been more precise, the test failures occur in the chroot and kvm integration test environment. Since the environment are new and test integration tests have not been tested in that environments we should take a look why the tests fail and exclude the failed test or adjust the environment to be able to pass the test. Updated the issue.
