### ISSUE TITLE
Kernel with CONFIG_IKHEADERS for BPF tools on Kubernetes

### ISSUE THREAD

**Issue by alban** [gardenlinux/gardenlinux#76]
**What would you like to be added**:

I would like the Garden Linux kernel to be compiled with [CONFIG_IKHEADERS](https://github.com/torvalds/linux/blob/435faf5c218a47fd6258187f62d9bb1009717896/init/Kconfig#L610-L617).

**Why is this needed**:

[BCC tools](https://github.com/iovisor/bcc) need to have access to kernel headers. It can be done either by installing `linux-headers` packages or by having a kernel compiled with `CONFIG_IKHEADERS` so that enough information can be retrieved via `/sys/kernel/kheaders.tar.xz`.

BCC tools are used in [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget/), a collection of tools for developers of Kubernetes applications. I would like Inspektor Gadget to support Gardener clusters when it uses Garden Linux.

/cc @mauriciovasquezbernal @domdom82 @vasu1124 @gehoern  @MalteJ

**Comment by marwinski** [comment]
@gehoern: can you add this?

**Comment by gehoern** [comment]
I guess it is not a good idea to have the headers included since it would end up in 1MB more space in the kernel and that in each and every kernel ... the alternative in debian is to just pull linux-headers ... i know atm. till we have our own repo it is kind of unhandy but that will be fixed soon

https://snapshot.debian.org/archive/debian/20200213T231921Z/pool/main/l/linux/linux-headers-5.4.0-4-amd64_5.4.19-1_amd64.deb

**Comment by gehoern** [comment]
on the other hand 1MB is not much ... but away from the debian standard. @MalteJ @marwinski

**Comment by gehoern** [comment]
@alban is that what you looked for?

**Comment by alban** [comment]
Do you have an update on this?

FYI I filed a similar issue in Minikube: https://github.com/kubernetes/minikube/issues/8556

**Comment by alban** [comment]
Last year, @mauriciovasquezbernal  had the following workaround for this issue:
```
# remount /usr with write permissions
mount | grep -v rw
/dev/nvme0n1p3 on /usr type ext4 (ro,relatime)
mount -o remount,rw /dev/nvme0n1p3

mkdir home/admin/sources && cd home/admin/sources/

# download kernel headers and other dependencies
wget https://snapshot.debian.org/archive/debian/20200213T231921Z/pool/main/l/linux/linux-headers-5.4.0-4-common_5.4.19-1_all.deb
wget https://snapshot.debian.org/archive/debian/20200213T231921Z/pool/main/l/linux/linux-kbuild-5.4_5.4.19-1_amd64.deb
wget https://snapshot.debian.org/archive/debian/20200213T231921Z/pool/main/l/linux/linux-compiler-gcc-9-x86_5.4.19-1_amd64.deb
wget https://snapshot.debian.org/archive/debian/20200213T231921Z/pool/main/l/linux/linux-headers-5.4.0-4-cloud-amd64_5.4.19-1_amd64.deb

dpkg -i *.deb
```

Similar instructions could be used now but it is difficult to find the deb packages with the correct version.

**Comment by teenivcse** [comment]
Do you have an update on this?

**Comment by marwinski** [comment]
@gehoern we will see a lot more requests for this. Any objection including the headers? It is just 1MB as you wrote.

**Comment by mauriciovasquezbernal** [comment]
> What about BPF CO-RE and BTF:
> https://www.brendangregg.com/blog/2020-11-04/bpf-co-re-btf-libbpf.html
> https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html
> 
> Is there a preferred way to address compatibility problems of eBPF programs across kernel versions.

The preferred way is CO-RE and BTF nowadays. In this case the tools are **not** compiled in the target machine, hence the kernel headers are not needed. In this case it is needed to have the `CONFIG_DEBUG_INFO_BTF` enabled in the machine where the tool is run. 

> How does IKHEADERS relate to this?

`IKHEADERS` headers is a way to provide the kernel headers without need to install any package in the target host. It's useful for supporting eBPF tools that need to be compiled in the target machine (like BCC tools). 

> As far as I understand, BTF is intended to solve the problem mentioned here. I'm currently working on migrating the eBPF program which has been built by kinvolk to be used in tc-bpf for egress filtering to be BTF based. https://github.com/kinvolk/egress-filtering-benchmark/blob/master/pkg/filters/tc-bpf/datapath/bpf.c

I'm wondering why you want to use BTF with that program. That's a networking program that receives an `struct __sk_buff *skb` that is stable among the different kernel versions, so I don't think BTF plays any important role there. It should be possible to compile that program in a machine and deploy in others without any issues. 


I'd say that enabling `CONFIG_DEBUG_INFO_BTF` should be a priority now as it's a fundamental piece of the future of eBPF and almost all major distros have enabled it by now.

**Comment by frnksgr** [comment]
>I'm wondering why you want to use BTF with that program. That's a networking program that receives an struct __sk_buff *skb that is stable among the different kernel versions, so I don't think BTF plays any important role there. It should be possible to compile that program in a machine and deploy in others without any issues.

Yes, your are right. We want to build something similar that does work across different kernel versions. I thought BTF might be helpful. As you mentioned, we might not need it. Also, the kernels we have to support don't have "CONFIG_DEBUG_INFO_BTF yes" and we don't want to customize the kernel. I run a customized 5.11 kernel with BTF support locally.

**Comment by alban** [comment]
Hi! I noticed that Debian includes Linux 5.10.5-1 with `CONFIG_DEBUG_INFO_BTF` (see [Debian bug 973870](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973870#32)) and I was wondering if Garden Linux has that kernel with that option too now.

On one hand, I see [this commit](https://github.com/gardenlinux/gardenlinux/commit/d4f13b8ce0c3c14c8a6607daefa27ff2a9615334#diff-a64ac06c131f50a17b80159c1d60e048854e98668a911245b28e4ab55e778abd) that includes 5.10, but on the other hand when I try the last release for Azure listed on https://github.com/gardenlinux/gardenlinux/blob/main/docs/releases.md#microsoft-azure-az (318.8.0), then I get a 5.4.0-6-cloud-amd64. Do I miss something?

**Comment by Vincinator** [comment]
heyhey @alban 

> On one hand, I see [this commit](https://github.com/gardenlinux/gardenlinux/commit/d4f13b8ce0c3c14c8a6607daefa27ff2a9615334#diff-a64ac06c131f50a17b80159c1d60e048854e98668a911245b28e4ab55e778abd) that includes 5.10.0-7, but on the other hand when I try the last release for Azure listed on https://github.com/gardenlinux/gardenlinux/blob/main/docs/releases.md#microsoft-azure-az (318.8.0), then I get a 5.4.0-6-cloud-amd64. Do I miss something?

Side note, in gardenlinux ```318.8``` you only have a 5.4 kernel. This commit  you were referencing  is a commit for higher gardenlinux version.

In general, we base our kernel configuration on debian kernel (salsa). 
With gardenlinux ```576``` we use the 5.10.70 kernel definitions from[ salsa](https://salsa.debian.org/kernel-team/linux/-/tree/debian/5.10.70-1/debian
)

```CONFIG_DEBUG_INFO_BTF``` is enabled in [5.10.70-1 debian kernel config ](https://salsa.debian.org/search?utf8=✓&search=CONFIG_DEBUG_INFO_BTF&group_id=2107&project_id=18670&scope=&search_code=true&snippets=false&repository_ref=debian%2F5.10.70-1&nav_source=navbar)

If possible, I would use the gardenlinux kernel headers.  Building them manually: 
```bash
# checkout the target gardenlinux version via git tags 
cd packages
make manual
# enter container
make linux-5.10
# exit container
```
.deb packages including headers should be placed in ```.packages/main/l/linux/```

**Comment by alban** [comment]
Thanks! It works, tested with:
```
$ az vm create -n $NAME -g $RG --image sap:gardenlinux:greatest:576.0.0
```

And then, on the machine:
```
$ uname -a
Linux albangardenlinux 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1gardenlinux1 (2021-10-26) x86_64 GNU/Linux
$ ls -lh /sys/kernel/btf/vmlinux 
-r--r--r--. 1 root root 3.2M Dec  9 13:57 /sys/kernel/btf/vmlinux
```

**Comment by waldiTM** [comment]
So do we need something more here? BFT is the way the ökosystem is going as far as I see.

**Comment by Vincinator** [comment]
Please let us know if you need further assistance. Thank you!
