### ISSUE TITLE
Issues to address with recent GL and cloud providers

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#765]
**What happened**:

Running the integration/platform tests with a recent build from Garden Linux (tested with 757, committish 3d9150af21449a3c7b1ddbe5bbd47da78391c77b) revealed several problems that need to be addressed.

**GCP**:
- [x] VM cannot be connected to at all, SSH keys are not getting injected
  - Reason: Garden Linux changed to upstream packages for `google-guest-agent` from Debian testing which lacks systemd units for `google-guest-agent.service`, `google-startup-scripts.service` and `google-shutdown-scripts.service`. As a result, metadata such as SSH keys does not get injected into the image. This is linked to issue #585.

**ALI**:
- [x] VM cannot be connected to at all, SSH keys are not getting injected

**Azure**:
- [x] *test_hostname_azure* fails with `"Server:\t\t168.63.129.16\nAddress:\t168.63.129.16#53\n\n** server can't find vm-gl-test-20220412144632: NXDOMAIN\n\n"`

**all**:
- [x] as SELinux became the default LSM, the test for active AppArmor fails and needs to be adapted

**What you expected to happen**:

Platform tests to succeed on all platforms without problems on recent builds.

**Comment by nanory** [comment]
Quick update to this issue. We were able to fix the issue which led to the `test_hostname_azure` failure via #925.

**Comment by nanory** [comment]
As discussed with @MrBatschner , there are no known issues regarding the cloud providers as of now so we can close this issue then.
