### ISSUE TITLE
switch back to pipenv package

### ISSUE THREAD

**Issue by chrinorse** [gardenlinux/gardenlinux#776]
**What happened**:
pipenv was removed from the bookworm repository, therefore it is now installed via pip. Switch back to the bookworm package as soon as it is back in the repository. See #772
https://tracker.debian.org/pkg/pipenv
**What you expected to happen**:
that pipenv is installed from the bookworm repository
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by gehoern** [comment]
it does not seem to move at all on debian side. Do we really need this or can we circumvent by using virtualenv ?

**Comment by chrinorse** [comment]
As a work around we are installing pipenv via pip.
