### ISSUE TITLE
Snapshot Server

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#8]
- look at snapshot.debian.org
- probably use technology from there: https://salsa.debian.org/snapshot-team/snapshot
- make sure to use our debian mirror as source -> having our "additions" to debian added as well
- target: being auditable, being fast (we build against this server!)

**Comment by ccwienk** [comment]
@jensh007 @AndreasBurger : please update current status

**Comment by marwinski** [comment]
@gehoern : isn't this covered by #321. Maybe we should make one item more concrete and close the other.
