### ISSUE TITLE
Build Failures on Hosts Running `SELinux`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#802]
**What happened**:
Building GL on a host system running `SELinux` in `enforcing` mode will fail when `chcon` commands are triggered within the `chroot` env.

**What you expected to happen**:
This should work.

**How to reproduce it (as minimally and precisely as possible)**:
Just have any system running `SELinux` in `enforcing` mode and run the GL build from scratch.

**Anything else we need to know**:
This issue was reported by @Vincinator and @gyptazy 

**Environment**:
 * RHEL based system with `SELinux` in `enforcing` mode
 * Garden Linux host with `SELinux` in `permissive` mode

**Comment by Vincinator** [comment]
I had the issue on a `Garden Linux` environment with SELinux in `permissive` mode. 

```
 sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             default
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```

**Comment by gyptazy** [comment]
With the changes from https://github.com/gardenlinux/gardenlinux/issues/1014 this issues doesn't exist anymore. However, this got deactivated for the same reason as this case. An upcoming solution in #1014 will fix this one as well.
