### ISSUE TITLE
Pytest: Migrate feature test `dev`

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#805]
**What would you like to be added**:
The following test should be migrated to a pytest unit:
* [features/base/test/dev](https://github.com/gardenlinux/gardenlinux/blob/main/features/base/test/dev)

Thereby, there are already some pytest units ([here](https://github.com/gardenlinux/gardenlinux/tree/main/tests/helper/tests)), which can be used as blueprints for the migrated test.

**Why is this needed**:
We want to migrate each feature test to a corresponding pytest. Once we have done this, we can make the `chroot` and `kvm` platform tests the new default tests for Garden Linux builds.

**Comment by 5kt** [comment]
This test was supposed to verify the special files created under /dev by the installer (debootstrap) - anything other than a predefined list should end in an error. 
As this test is now run only chrooted or inside a VM, this test is no longer valid.
