### ISSUE TITLE
Release Notes handling

### ISSUE THREAD

**Issue by ccwienk** [gardenlinux/gardenlinux#87]
# Motivation

Users may be interested in relevant changes between gardenlinux versions. The usual way to transport this kind of information is through release notes.

# Implementation Hints

- define a contract allowing us to collect, and publish release notes between the last and current (to-be-released) version of gardenlinux; preferrably in an automated fashion
- establish some conventions (e.g. mark breaking changes, features, fixes, .. in a consistent manner)

**Comment by marwinski** [comment]
duplicate (more or less) of #318

@ccwienk  Can we close this one and move the discussion to the above issue?

**Comment by gyptazy** [comment]
Closing this almost 2 years old issue as a duplicate in favor of #318.
