### ISSUE TITLE
Bring back `ignition` from `bookworm`

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#891]
**What happened**:
The `ignition` package has been removed from `debian/testing`. Since the `_pxe` feature requires the `ignition` package, we had to provide a replacement by uploading a self build variant of `ignition`:
* https://gitlab.com/gardenlinux/gardenlinux-package-ignition

It has been removed from `bookworm´ because one of its build dependencies has been removed as well:
* golang-github-pin-tftp

If we want to go back to the offical Debian package, we must ensure that `golang-github-pin-tftp` is available in testing again, so that `ignition` can be added again, too.

**What you expected to happen**:
The current solution is just a workaround to keep the Github Actions running. We should switch to the `ignition` package once it is available in `debian/testing` again.

**Comment by chrinorse** [comment]
Created an issue for the ignition dependency `golang-github-pin-tftp`.
https://github.com/pin/tftp/issues/68

Also created a patch for the `golang-github-pin-tftp` package to remove the problematic tests. Waiting for access to the project on Debian salsa to push the patch and create a merge request.

**Comment by chrinorse** [comment]
Done. Patch was excepted and `golang-github-pin-tftp` is back in Debian Sid.

**Comment by nanory** [comment]
Hi @chrinorse,

`golang-github-pin-tftp` is back in Debian testing again:
* https://tracker.debian.org/news/1326471/golang-github-pin-tftp-220-3-migrated-to-testing/

In addition, `ignition` returned to Debian testing with a new version, too:
* https://tracker.debian.org/news/1326719/ignition-2130ds1-4-migrated-to-testing/

This would allow us to remove our self-build `ignition` package and return to the Debian testing one. However, there is still the issue with `golang-github-smartystreets-assertions`, which is in Debian testing but will get removed on 13th of June if the following bug does not get resolved:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008443

It seems that the issue has been identified and that an upstream issue has already been opened:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008443#25

However, the problematic unit test is still part of the current Debian testing package.

**Comment by chrinorse** [comment]
Ignition and it's dependencies are back in Debian testing. Mission accomplished.
