### ISSUE TITLE
Custom permissions for files from file.include

### ISSUE THREAD

**Issue by 5kt** [gardenlinux/gardenlinux#920]
**What would you like to be added**:
A way to configure custom permissions for files included via file.include from the feature.
This could be done, of course, via exec.config, but maybe it would be nicer to have something like file.include.stat, similar to dpkg statoverride where one would specify the owner/group and whatever permissions are wanted.

**Why is this needed**:
This can also be considered a bug. This is needed because at the moment all files provided via file.include are going to be owned by root:root and have whatever permissions those files have on the build machine.

**Comment by gyptazy** [comment]
Hey @5kt,

you may review my PR in #1331 which would add this feature. Unfortunately, I missed this feature, too.

Regards,
gyptazy
