### ISSUE TITLE
rename dev version/timestamp to today

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#934]
**What would you like to be added**:
- [ ] Rename suite `dev` of repo.gardnelinux.io to today 
- [ ] Refactor [bin/garden-version ](https://github.com/gardenlinux/gardenlinux/blob/main/bin/garden-version 
) to use `today` instead of `dev`
- [ ] ... TBD ... 

**Why is this needed**:
- `dev` is ambiguous. 
  - _dev feature
  - dev user
  - dev apt repo suite & gardenlinux version 
  - /dev filesystem
-  using a term like `today` for daily versions is more fitting
    - easier to understand when the version was build, since today will be updated daily

**Comment by Vincinator** [comment]
Feel free to add tasks and edit the issue

**Comment by nanory** [comment]
The required change has been done in PR #1059
