### ISSUE TITLE
GL tool `start-vm` may not work with cpu type `host` in virtualized envs without `KVM` (rel. Apple Silicon)

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#957]
**What happened**:
While creating an artifact of Garden Linux works pretty fine on native `arm64` systems, the `start-vm` may fail to spawn a QEMU instance to run the final artifact. The following cmd is created by `start-vm`:
```
qemu-system-aarch64 -runas nobody -smp 2 -m 2048 -watchdog i6300esb -nodefaults 
    -device virtio-balloon -device virtio-rng-pci,rng=rng0 
    -object rng-random,id=rng0,filename=/dev/random -uuid 12345678-0000-0000-0000-02c30be5de6c 
    -chardev socket,path=/root/gardenlinux/bin/02c30be5de6c.guest,server=on,wait=off,id=qga0 
    -device virtio-serial -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 
    -cpu host -machine virt -monitor unix:/root/gardenlinux/bin/02c30be5de6c.monitor,server,nowait 
    -nographic -serial mon:stdio 
    -drive if=pflash,format=raw,unit=0,file=/usr/share/AAVMF/AAVMF_CODE.fd,readonly=on 
    -drive if=pflash,format=raw,unit=1,file=/root/gardenlinux/bin/02c30be5de6c.vars 
    -device virtio-net-pci,netdev=net0,mac=02:c3:0b:ee:dd:ee 
    -netdev user,id=net0,hostfwd=tcp::2223-:22,hostname=garden 
```
In this case it detects the native `arm64` support by defining `-cpu host` but may fail later with `qemu-system-aarch64: The 'host' CPU type can only be used with KVM`. This may depend on the users setup, e.g. the running virtualizer and options, but this should be detected and avoided. This can probably easily be done by testing:
```
root@debian:~/gardenlinux# dmesg | grep -i kvm
[    0.400425] kvm [1]: HYP mode not available
```

**What you expected to happen**:
A VM should be spawned.

**Environment**:
 * Apple Silicon ARM64
 * UTM Virtualizer
 * Linux Debian ARM64 as used OS

**Comment by gyptazy** [comment]
Probably I can deliver a fix for this on the weekend.

**Comment by gehoern** [comment]
Full support from my side. Can you also take a look if the whole build process will run on an apple at all (maybe separate issue)?
