### ISSUE TITLE
Allow non-root users to use dmesg

### ISSUE THREAD

**Issue by liorokman** [gardenlinux/gardenlinux#96]
**What would you like to be added**:

Remove the restriction on `dmesg` that makes it only usable for root.

**Why is this needed**:

1. Allowing non-root users to use `dmesg` makes it easier to identify various kernel-level errors, the most common of which (in Kubernetes containers) are situations in which the kernel OOM-killer cause processes to be killed.
1. Allows for easier diagnostics in case of driver and hardware issues.
1. Provides compatibility with CoreOS, which didn't restrict `dmesg` from non-root users.

Without this PR, identifying kernel-related issues would require pushing a privileged container to Kubernetes to run dmesg. If the issue is related to stability then it might not be possible to do after the fact, while with the PR any container that is still running on the host could be used to diagnose the issue.

**Comment by marwinski** [comment]
While I don't see a problem with this pull request for a container host our security guys do. What is your precise use case? I usually use something like ````gardenctl shell```` or ````gardenctl ssh````. The first one gives me immediate root access and the second can do ````sudo````. This is also not needed here.

**Comment by liorokman** [comment]
> I usually use something like gardenctl shell or gardenctl ssh. 

This is not possible for run-of-the-mill developers. AFAIK `gardenctl` is only available if you have access to the Gardener seed. 

> What is your precise use case? 

I run some workload on a cluster, and it crashes on OOM. Using Kubernetes tools I can tell that the OOM happened. Using `dmesg`, I can see the process-list in the container before the OOM Killer did its thing, and I can get a better indication of what went wrong.

When there's an kernel OOM event and the OOM killer doesn't kill PID 1 in the container, Kubernetes doesn't always notice that the OOM event even happened. The only way to know that it did is to use `dmesg`.
