### ISSUE TITLE
Garden Linux Firewall: Replace `iptables` by a more common solution

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#972]
**What would you like to be added**:
Currently, Garden Linux uses `iptables` for the basic firewall services. While `iptables` works for this it may not fit our way of implementations for further rule sets. Therefore, we should discuss to switch to a more common and comfortable solution like:
 * ferm
 * ufw
 * [...]

**Why is this needed**:
I'd prefer `ferm` with further `ferm.d` (drop-in) support. This would also allow us to inject rules for unit tests via Pytest later instead of all time present static rules.

Opinions here?

**Comment by MrBatschner** [comment]
For Gardener and Kubernetes, we definitely need iptables. kube-proxy uses iptables to set up Kubernetes Services. Calico also heavily relies on iptables. In addition, a regular Garden Linux that runs with Gardener on major cloud providers should not have a firewall at all. Disregard this comment if "replace" does not mean to get rid of it altogether.

**Comment by gyptazy** [comment]
Hey @MrBatschner,

as you already correctly said, it's not directly a replacement for `iptables` itself - so no worries here for any kind of support regarding any K8s CNIs, Gardener support etc. It's more meant to be a replacement for the current [firewalling solution](https://github.com/gardenlinux/gardenlinux/tree/main/features/firewall) in Garden Linux which is required for:
 * Stand Alone Solution on the Operator's Decision if needed
 * Feature: FedRAMP
 * Feature: CIS

So this task is just to discuss if we should take some effort to adjust the current firewalling solution to a better fitting solution for managing rule sets with a proper frontend like `ferm`, `ufw`,...

**Comment by gehoern** [comment]
Hi,

did we think about nft? I think it is the successor of iptables and has borrowed a lot of ferm. It also has a /etc/nftables.d/ directory to store standard elements for reuse.
