### ISSUE TITLE
Enable SGX in GardenLinux Kernel

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#986]
make sure SGX is supported in our Kernels. The Debian upstream kernels since 5.15 (that support this feature) have this actively turned off.

Maybe we should file this back to Debian?

**Comment by Vincinator** [comment]
We also explicitly enable it in `config.gardenlinux`
https://gitlab.com/gardenlinux/gardenlinux-package-linux-5.15/-/blob/main/debian/config/config.gardenlinux#L63

Every `CONFIG_*` entry listed in `config.gardenlinux` is checked if automatically if it is included in the final kernel image.
