### ISSUE TITLE
Re-evaluate the need of multiqueue and local SSD optimization in GCP

### ISSUE THREAD

**Issue by nanory** [gardenlinux/gardenlinux#988]
**What would you like to be added**:
The current `google-guest-agent` version of Garden Linux comes from `debian/testing`:
* https://packages.debian.org/bookworm/google-guest-agent 

This version disables the `set_multiqueue` and `optimize_local_ssd` feature of `google-guest-agent`. This is because these two feature require additional scripts to work properly that are not part of the package itself.

These scripts are part of the `google-compute-engine` package. As of now, it is fine to keep these two features disabled but we should re-evaluate the situation in some weeks and decide if we will still keep them disabled or not.

In case that we want to activate this features, we must ensure that these two scripts are included via `file.include` of the gcp feature. This is because we do not use the `google-compute-engine` package in Garden Linux but have all its files included via the `file.include` mechanism (See #549)

**Why is this needed**:
It is needed in order to verify if Garden Linux should support `set_multiqueue` or `optimize_local_ssd` in future.

**Comment by chrinorse** [comment]
After discussing this in the team, we thing, this not needed anymore.
`google-compute-engine` was removed from Debian unstable in January 2022.
