### ISSUE TITLE
CIS Feature: SELinux Policy - `systemd-sysuser`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#997]
**What happened**:
While booting a Garden Linux image with enabled `cis` feature we may encounter the following `SELinux` message:

```
avc:  denied  { search } for  pid=277 comm="systemd-sysuser" name="var" dev="sda7" ino=15402 scontext=system_u:system_r:systemd_sysusers_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
```

**What you expected to happen**:
We should add this to our SELinux policy.

**Comment by chrinorse** [comment]
Updated the gardenlinux-selinux-module.
