### ISSUE TITLE
CIS Feature: SELinux Policy - `systemd-crontab`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#998]
**What happened**:
While booting a Garden Linux image with enabled `cis` feature we may encounter the following `SELinux` message:

```
avc:  denied  { search } for  pid=236 comm="systemd-crontab" name="ssl" dev="sda7" ino=827 scontext=system_u:system_r:systemd_generator_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=0
```

**What you expected to happen**:
We should add this to our SELinux policy.

**Comment by chrinorse** [comment]
Updated the gardenlinux-selinux-module.
