### ISSUE TITLE
CIS Feature: SELinux Policy - `systemd-gpt-aut`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#999]
**What happened**:
While booting a Garden Linux image with enabled `cis` feature we may encounter the following `SELinux` message:

```
avc:  denied  { sys_rawio } for  pid=241 comm="systemd-gpt-aut" capability=17  scontext=system_u:system_r:systemd_generator_t:s0 tcontext=system_u:system_r:systemd_generator_t:s0 tclass=capability permissive=0
```

**What you expected to happen**:
We should add this to our SELinux policy.

**Comment by chrinorse** [comment]
Updated the gardenlinux-selinux-module.
